exec(open('99-scratch/crawl.py').read().split('for user, seeds in [')[0])
seen, bad = crawl('u-sarah', ['/today','/crm','/listings','/pipeline','/training','/marketing','/assistant'])
print(f"=== u-sarah — {len(seen)} URLs ===")
for c,u,s in sorted(bad, key=str): print(f"   {c}  {u}   (linked from {s})")
if not bad: print("   all 200")
seen, bad = crawl(None, ['/','/join','/login'])
print(f"=== public — {len(seen)} URLs ===")
for c,u,s in sorted(bad, key=str): print(f"   {c}  {u}   (linked from {s})")
if not bad: print("   all 200")
