'use client'
import {useState} from 'react'
import {CinematicFilm} from './CinematicFilm'
import './cinematic-gallery.css'
const films=[
 {key:'coast',label:'The coast',title:'A different kind of everyday.',description:'A little space to imagine what comes next. Explore the textures, light, and moments that make a place feel like home.',credit:'Nino Souza / Pexels',sourceUrl:'https://www.pexels.com/video/4193133/',sceneNote:'Editorial inspiration: the Algarve coast, Portugal. This film does not depict an RCRE property or an Alabama or Florida location.'},
 {key:'shoreline',label:'By the water',title:'Make room for a slower moment.',description:'The rhythm of the shoreline. A fresh perspective before you start your next chapter.',credit:'ArtHouse Studio / Pexels',sourceUrl:'https://www.pexels.com/video/4631568/',sceneNote:'Editorial inspiration: California shoreline footage. Not an Alabama or Florida location, or a representation of property availability.'},
 {key:'architecture',label:'Spaces to imagine',title:'There’s a story behind every door.',description:'Light, proportion, and a place to gather. Bring your own priorities to the search for a home.',credit:'just a hobby / Pexels',sourceUrl:'https://www.pexels.com/video/34698342/',sceneNote:'Editorial architectural footage. This residence is not an RCRE listing; location and availability are not represented.'},
]
export function CinematicGallery({journal=false}:{journal?:boolean}){const [index,setIndex]=useState(0);const film=films[index];return <div id={journal?'journal-films':'rcre-films'} className={'cinematic-gallery '+(film.key==='architecture'?'portrait-film':'')}><div className="cinematic-gallery-tabs" aria-label="Choose a film">{films.map((f,i)=><button key={f.key} aria-pressed={index===i} onClick={()=>setIndex(i)}><span aria-hidden="true">0{i+1}</span>{f.label}</button>)}</div><CinematicFilm key={film.key} src={'/brand/cinematic/video-'+film.key+'.mp4'} poster={'/brand/cinematic/video-'+film.key+'-poster.webp'} title={film.title} description={film.description} credit={film.credit} sourceUrl={film.sourceUrl} licenseUrl="https://www.pexels.com/license/" sceneNote={film.sceneNote} autoPlay={!journal} background/></div>}
