'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {metroJournals,metroArticles,journalStories,type MetroJournal as Journal,type MetroArticle} from '@/lib/public/metro-journal'
import {articles,type PublishedContent} from '@/lib/public/content'
import {MetroPhotoCredit} from './MetroPhotoCredit'
import './metro-journal.css'
import {BlogPhotography} from './BlogPhotography'
export const metroImageAlt=(slug:string)=>slug==='birmingham'?'Birmingham Alabama skyline, 2026':slug==='jacksonville'?'Historical Jacksonville skyline in 2014, including the former Jacksonville Landing':'Miami skyline from Biscayne Bay, 2011'
type Agent={slug:string;name:string;image:string|null;role:string}
export function MetroJournalIndex({hidden=[],overrides={},title,description}:{hidden?:string[];overrides?:Record<string,PublishedContent>;title?:string;description?:string}){const [query,setQuery]=useState(''),[metro,setMetro]=useState('all'),[category,setCategory]=useState('all');const visible=journalStories(articles,overrides,hidden);
useEffect(()=>{const load=()=>{const p=new URLSearchParams(window.location.search);setQuery((p.get('q')||'').slice(0,160));const region=p.get('region');setMetro(region&&[...metroJournals.map(m=>m.slug),'brokerage'].includes(region)?region:'all');setCategory(p.get('topic')||'all')};load();window.addEventListener('popstate',load);return()=>window.removeEventListener('popstate',load)},[]);
function change(next:{query?:string;metro?:string;category?:string}){const q=next.query??query,m=next.metro??metro,c=next.category??category;setQuery(q);setMetro(m);setCategory(c);const p=new URLSearchParams();if(q)p.set('q',q);if(m!=='all')p.set('region',m);if(c!=='all')p.set('topic',c);window.history.replaceState(null,'',window.location.pathname+(p.size?'?'+p.toString():''))}
const shown=visible.filter(a=>(metro==='all'||a.metroSlug===metro)&&(category==='all'||a.category===category)&&[overrides['/blog/'+a.slug]?.title||a.title,a.description,metroJournals.find(m=>m.slug===a.metroSlug)?.name].join(' ').toLowerCase().includes(query.toLowerCase()));return <section className="metro-journal"><div className="metro-kicker">THE RCRE JOURNAL</div><div className="metro-intro"><h1>{title||<>Every move has<br/>a local story.</>}</h1><p>{description||"Read by region. Ask better questions. Find the people and perspective to make your next chapter feel closer."}</p></div><nav className="metro-regions" aria-label="Regional journals">{metroJournals.filter(m=>!hidden.includes('/blog/metros/'+m.slug)).map((m,i)=><article key={m.slug}><Link href={'/blog/metros/'+m.slug}><img src={overrides['/blog/metros/'+m.slug]?.image?.src||'/brand/metros/'+m.slug+'.webp'} alt={overrides['/blog/metros/'+m.slug]?.image?.alt||metroImageAlt(m.slug)} width={1600} height={900}/><span>0{i+1} / {m.state}</span><h3>{overrides['/blog/metros/'+m.slug]?.title||m.name}</h3><p>{overrides['/blog/metros/'+m.slug]?.description||m.description}</p><b>Explore the journal ↗</b></Link>{(!overrides['/blog/metros/'+m.slug]?.image?.src||overrides['/blog/metros/'+m.slug]?.image?.src==='/brand/metros/'+m.slug+'.webp')&&<MetroPhotoCredit metro={m.slug}/>}</article>)}</nav><div className="metro-filters"><label>Search the journal<input type="search" value={query} maxLength={160} onChange={e=>change({query:e.target.value})} placeholder="Topic, place, or question"/></label><label>Region<select value={metro} onChange={e=>change({metro:e.target.value})}><option value="all">All regions</option>{metroJournals.map(m=><option value={m.slug} key={m.slug}>{m.name}</option>)}<option value="brokerage">Brokerage</option></select></label><label>Topic<select value={category} onChange={e=>change({category:e.target.value})}><option value="all">All topics</option>{[...new Set(visible.map(a=>a.category))].sort().map(t=><option key={t}>{t}</option>)}</select></label></div><p className="metro-count" aria-live="polite">{shown.length} {shown.length===1?'story':'stories'}</p><div className="metro-stories">{shown.map(a=><MetroStoryCard article={a} override={overrides['/blog/'+a.slug]} key={a.slug}/>)}</div>{!shown.length&&<div className="metro-empty"><h3>No stories match that search.</h3><button onClick={()=>change({query:'',category:'all',metro:'all'})}>Clear filters</button></div>}</section>}
export function MetroStoryCard({article:a,override}:{article:MetroArticle;override?:PublishedContent}){return <Link className="metro-story" href={'/blog/'+a.slug}><BlogPhotography slug={a.slug} category={a.category} override={override} compact/><span>{metroJournals.find(m=>m.slug===a.metroSlug)?.name||'Brokerage'} · {a.category}</span><h3>{override?.title||a.title}</h3><p>{override?.description||a.description}</p><b>{a.readMinutes} minute read <span aria-hidden>↗</span></b></Link>}
export function MetroHub({metro:m,agents,edited,hidden=[],overrides={}}:{metro:Journal;agents:Agent[];edited?:PublishedContent;hidden?:string[];overrides?:Record<string,PublishedContent>}){return <section className="metro-journal"><div className="metro-kicker">REGIONAL JOURNAL / {m.state}</div><div className="metro-intro"><h1>{edited?.title||m.name}</h1><p>{edited?.description||m.description}</p></div><figure className="metro-wide-photo"><img src={edited?.image?.src||'/brand/metros/'+m.slug+'.webp'} alt={edited?.image?.alt||metroImageAlt(m.slug)} width={1600} height={900}/>{(!edited?.image?.src||edited.image.src==='/brand/metros/'+m.slug+'.webp')&&<figcaption><MetroPhotoCredit metro={m.slug}/></figcaption>}</figure><div className="metro-hub-body">{edited?.body?edited.body.split('\n\n').map((p,i)=><p key={i}>{p}</p>):<p>Begin with your questions about buying, selling, and moving. These original guides connect the RCRE county footprint with the practical decisions that belong on your own shortlist.</p>}</div><div className="metro-stories">{journalStories(articles,overrides,hidden).filter(a=>a.metroSlug===m.slug).map(a=><MetroStoryCard key={a.slug} article={a} override={overrides['/blog/'+a.slug]}/>)}</div><MetroPeople metro={m} agents={agents}/><div className="metro-counties"><h2>Explore the county guides</h2>{m.counties.filter(c=>!hidden.includes('/neighborhoods/'+c)).map(c=><Link key={c} href={'/neighborhoods/'+c}>{c.replace(/-/g,' ')} ↗</Link>)}</div><MetroSources sources={m.sources}/></section>}
export function MetroPeople({metro,agents}:{metro:Journal;agents:Agent[]}){const matched=agents.filter(a=>metro.agentSlugs.includes(a.slug));return <section className="metro-people"><h2>{matched.length?'People to start a conversation with':'Find the right local connection'}</h2><p>{metro.evidenceNote}</p>{matched.length?<div>{matched.map(a=><Link key={a.slug} href={'/agent/'+a.slug}>{a.image?<img src={a.image} alt={a.name} width={72} height={72}/>:<span className="metro-initials" aria-hidden>{a.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>}<span><strong>{a.name}</strong><small>{a.role}</small></span><b aria-hidden>↗</b></Link>)}</div>:<Link className="public-button secondary" href="/contact">Ask RCRE about this market ↗</Link>}</section>}
export function MetroSources({sources}:{sources:{label:string;url:string}[]}){return <aside className="metro-sources"><h2>Source notes</h2><p>Original RCRE editorial guidance. Regional coverage and profile connections were checked against the brokerage’s public pages on September 8, 2026. No live listing, price forecast, or agent availability is inferred.</p>{sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a>)}</aside>}
