'use client'
import {useCallback,useEffect,useMemo,useRef,useState,type PointerEvent} from 'react'
import {useSearchParams} from 'next/navigation'
import Link from 'next/link'
import {ListingVisual} from '@/components/ListingVisual'
import type {PropertyListing,PropertySearchFilters,SearchResult} from '@/lib/property/types'
import {fitZoom,geoPoint,viewportBounds,worldPixel,wrappedTileX} from '@/lib/property/geo'
type FormFilters={q:string;state:string;city:string;county:string;postalCode:string;subdivision:string;mls:string;minPrice:string;maxPrice:string;beds:string;baths:string;type:string;subtype:string;minSqft:string;maxSqft:string;acres:string;yearBuilt:string;maxYearBuilt:string;minLotArea:string;maxDom:string;garage:string;pool:string;waterfront:string;newConstruction:string;openHouse:string;priceReduced:string;status:string;sort:string}
type SavedSearch={id:string;name:string;filters:Record<string,string>}
const empty:FormFilters={q:'',state:'',city:'',county:'',postalCode:'',subdivision:'',mls:'',minPrice:'',maxPrice:'',beds:'',baths:'',type:'',subtype:'',minSqft:'',maxSqft:'',acres:'',yearBuilt:'',maxYearBuilt:'',minLotArea:'',maxDom:'',garage:'',pool:'',waterfront:'',newConstruction:'',openHouse:'',priceReduced:'',status:'',sort:'newest'}
const dollar=(n?:number)=>n===undefined?'Price unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)
const address=(p:PropertyListing)=>[p.streetNumber,p.streetName,p.unitNumber].filter(Boolean).join(' ')||'Address not supplied'
const location=(p:PropertyListing)=>[p.city,p.stateOrProvince,p.postalCode].filter(Boolean).join(', ')
function paramsFor(f:FormFilters,page:number,bounds?:PropertySearchFilters['bounds']){const p=new URLSearchParams();const keys:Record<string,string>={q:'q',state:'state',city:'city',county:'county',postalCode:'postalCode',subdivision:'subdivision',mls:'mls',minPrice:'minPrice',maxPrice:'maxPrice',beds:'beds',baths:'baths',type:'type',subtype:'subtype',minSqft:'minSqft',maxSqft:'maxSqft',acres:'acres',yearBuilt:'yearBuilt',maxYearBuilt:'maxYearBuilt',minLotArea:'minLotArea',maxDom:'maxDom',garage:'garage',pool:'pool',waterfront:'waterfront',newConstruction:'newConstruction',openHouse:'openHouse',priceReduced:'priceReduced',status:'status',sort:'sort'};for(const key of Object.keys(keys)){const value=f[key as keyof FormFilters];if(value)p.set(keys[key]!,value)}p.set('page',String(page));p.set('pageSize','18');if(bounds){p.set('north',String(bounds.north));p.set('south',String(bounds.south));p.set('east',String(bounds.east));p.set('west',String(bounds.west))}return p.toString()}
function fromUrl(url:URLSearchParams):FormFilters{const f={...empty};for(const key of Object.keys(f) as Array<keyof FormFilters>){const value=url.get(key);if(value)f[key]=value}const market=url.get('market');if(!f.state&&market)f.state=/alabama/i.test(market)?'AL':/florida/i.test(market)?'FL':'';if(url.get('max'))f.maxPrice=url.get('max')||'';return f}
function savedFilters(f:FormFilters){return Object.fromEntries(Object.entries(f).filter(([k,v])=>v&&k!=='sort')) as Record<string,string>}
const propertyAddress=(p:PropertyListing)=>[p.streetNumber,p.streetName,p.unitNumber].filter(Boolean).join(' ')||'Address unavailable'
const cityState=(p:PropertyListing)=>[p.city,p.stateOrProvince,p.postalCode].filter(Boolean).join(', ')
function PropertyMap({items,onSelect,selected,onSearchArea}:{items:PropertyListing[];onSelect:(id:string)=>void;selected:string|null;onSearchArea:(bounds:PropertySearchFilters['bounds'])=>void}){
 const width=900,height=490,tileSize=256
 const points=items.filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude))
 const geos=points.map(p=>({latitude:p.latitude!,longitude:p.longitude!}))
 const initial=geos.length?{latitude:geos.reduce((sum,p)=>sum+p.latitude,0)/geos.length,longitude:geos.reduce((sum,p)=>sum+p.longitude,0)/geos.length}:{latitude:31.8,longitude:-84.3}
 const [zoom,setZoom]=useState(()=>fitZoom(geos)),[center,setCenter]=useState(initial)
 const drag=useRef<{x:number;y:number;centerX:number;centerY:number;pointerId:number}|null>(null)
 const world=2**zoom,centerPixel=worldPixel(center,zoom),left=centerPixel.x-width/2,top=centerPixel.y-height/2
 const firstX=Math.floor(left/tileSize),lastX=Math.floor((left+width)/tileSize),firstY=Math.floor(top/tileSize),lastY=Math.floor((top+height)/tileSize)
 const tiles:React.ReactNode[]=[]
 for(let y=firstY;y<=lastY;y++)for(let x=firstX;x<=lastX;x++){if(y<0||y>=world)continue;const tileX=wrappedTileX(x,zoom);const template=process.env.NEXT_PUBLIC_RCRE_MAP_TILE_URL||'https://tile.openstreetmap.org/{z}/{x}/{y}.png';const src=template.replace('{z}',String(zoom)).replace('{x}',String(tileX)).replace('{y}',String(y));tiles.push(<image key={zoom+':'+x+':'+y} href={src} x={x*tileSize-left} y={y*tileSize-top} width={tileSize} height={tileSize} preserveAspectRatio="none"/>) }
 const pins=points.map(p=>{const pixel=worldPixel({latitude:p.latitude!,longitude:p.longitude!},zoom);return{p,x:pixel.x-centerPixel.x+width/2,y:pixel.y-centerPixel.y+height/2}}).filter(pin=>pin.x>=0&&pin.x<=width&&pin.y>=0&&pin.y<=height)
 const pan=(dx:number,dy:number)=>setCenter(geoPoint({x:centerPixel.x+dx,y:centerPixel.y+dy},zoom))
 function beginDrag(event:PointerEvent<HTMLDivElement>){const rect=event.currentTarget.getBoundingClientRect();drag.current={x:event.clientX,y:event.clientY,centerX:centerPixel.x,centerY:centerPixel.y,pointerId:event.pointerId};event.currentTarget.setPointerCapture(event.pointerId);void rect}
 function moveDrag(event:PointerEvent<HTMLDivElement>){const start=drag.current;if(!start||start.pointerId!==event.pointerId)return;const rect=event.currentTarget.getBoundingClientRect();setCenter(geoPoint({x:start.centerX-(event.clientX-start.x)*width/rect.width,y:start.centerY-(event.clientY-start.y)*height/rect.height},zoom))}
 function searchViewport(){onSearchArea(viewportBounds(center,zoom,width,height))}
 const attribution=process.env.NEXT_PUBLIC_RCRE_MAP_ATTRIBUTION||'© OpenStreetMap contributors'
 return <div className="property-map-panel"><div className="property-map-top"><div><strong>Map view</strong><span>Pan the map, zoom, or select a home to open its details.</span></div><div className="property-map-actions"><button type="button" className="property-small-button" aria-label="Zoom in" onClick={()=>setZoom(value=>Math.min(17,value+1))}>+</button><button type="button" className="property-small-button" aria-label="Zoom out" onClick={()=>setZoom(value=>Math.max(4,value-1))}>−</button><button type="button" className="property-small-button" onClick={searchViewport}>Search this area</button></div></div><div className="property-map-canvas" role="group" aria-label="Property results map" onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><svg viewBox={'0 0 '+width+' '+height} preserveAspectRatio="none" aria-hidden="true" className="property-map-tiles">{tiles}</svg>{pins.map(({p,x,y})=>{const price=p.listPrice===undefined?'View':dollar(p.listPrice).replace(/,000$/,'k');return <button key={p.id} type="button" onClick={()=>onSelect(p.id)} aria-label={dollar(p.listPrice)+' in '+cityState(p)} aria-pressed={selected===p.id} className={'property-map-pin'+(selected===p.id?' selected':'')} style={{left:(x/width*100)+'%',top:(y/height*100)+'%'}}>{price}</button>})}{!points.length&&<div className="property-map-empty">Map coordinates will appear when an approved source provides them.</div>}</div><div className="property-map-bottom"><span>{pins.length} mapped results · Zoom {zoom}</span><span><a href="https://www.openstreetmap.org/copyright" rel="noreferrer" target="_blank">{attribution}</a> · Map tiles are replaceable by configuration.</span></div></div>
}
export function PropertySearch({sold=false,account=false,agentId:agentProp}:{sold?:boolean;account?:boolean;agentId?:string}){
 const searchParams=useSearchParams()
 const [filters,setFilters]=useState<FormFilters>({...empty,status:sold?'Closed':''}),[result,setResult]=useState<SearchResult|null>(null),[view,setView]=useState<'list'|'map'|'split'>('list'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[favorites,setFavorites]=useState<string[]>([]),[saved,setSaved]=useState<SavedSearch[]>([]),[onlyFavorites,setOnlyFavorites]=useState(account),[savedName,setSavedName]=useState(''),[statusText,setStatusText]=useState(''),[selected,setSelected]=useState<string|null>(null),[page,setPage]=useState(1),[filtersOpen,setFiltersOpen]=useState(false),[bounds,setBounds]=useState<PropertySearchFilters['bounds']>()
 const agentId=agentProp||searchParams.get('agent')||undefined
 useEffect(()=>{setFilters(fromUrl(new URLSearchParams(searchParams.toString())));setPage(1)},[searchParams])
 const loadState=useCallback(async()=>{try{const r=await fetch('/api/property-search-state',{cache:'no-store'});if(r.ok){const s=await r.json();setFavorites(s.favorites||[]);setSaved(s.searches||[])}}catch{setStatusText('Saved items are temporarily unavailable.')}},[])
 useEffect(()=>{void loadState()},[loadState])
 useEffect(()=>{const ctrl=new AbortController(),timer=window.setTimeout(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/properties?'+paramsFor(filters,page,bounds),{signal:ctrl.signal,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Property search is unavailable.');setResult(data);}catch(e){if(!ctrl.signal.aborted)setError((e as Error).message)}finally{if(!ctrl.signal.aborted)setLoading(false)}},140);return()=>{window.clearTimeout(timer);ctrl.abort()}},[filters,page,bounds])
 const update=(key:keyof FormFilters,value:string)=>{const next={...filters,[key]:value};setFilters(next);setPage(1);const params=new URLSearchParams(savedFilters(next));if(next.sort!=='newest')params.set('sort',next.sort);if(agentId)params.set('agent',agentId);window.history.replaceState(null,'',window.location.pathname+(params.size?'?'+params:''))}
 async function persist(nextFavorites:string[],nextSaved:SavedSearch[]){setStatusText('Saving…');try{const r=await fetch('/api/property-search-state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({favorites:nextFavorites,searches:nextSaved})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save.');setFavorites(data.favorites);setSaved(data.searches);setStatusText('Saved. Listing alerts remain off until the appropriate provider and notification path are approved.')}catch(e){setStatusText((e as Error).message)}}
 async function saveProperty(id:string){await persist(favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id],saved)}
 const visible=useMemo(()=>onlyFavorites?(result?.items.filter(p=>favorites.includes(p.id))??[]):result?.items??[],[onlyFavorites,result,favorites])
 function searchArea(viewport:PropertySearchFilters['bounds']){if(!viewport){setStatusText('Search this area needs geocoded source results.');return}setBounds(viewport);setPage(1)}
 const isFixture=result?.sourceMode==='fixtures'
 const hasInventory=isFixture||result?.sourceMode==='live'
 return <section className="property-search-experience"><div className="property-search-intro"><div><p className="public-kicker">RCRE Property Search</p><h1>Find a place that feels like yours.</h1><p>Explore homes across Alabama and Florida. Listings appear as verified options become available in each market.</p></div><div className="property-source-status" aria-live="polite"><span className={'property-source-dot '+(result?.sourceMode==='live'?'live':'pending')}/><div><strong>{result?.sourceMode==='live'?'Live home search':isFixture?'Local review data':'Home search opening soon'}</strong><span>{result?.sourceMode==='live'?'Listings available for this market':isFixture?'Fixture mode · no active listings are represented':'We are preparing verified listings for this area.'}</span></div></div></div>
 {isFixture&&<div className="property-review-note">Local review environment · records shown here are illustrative property fixtures, not live listing inventory.</div>}
 {result?.sourceMode!=='pending'&&<form className="property-search-bar" onSubmit={e=>{e.preventDefault();setPage(1)}}><label className="property-search-location"><span>Location or MLS number</span><input type="search" value={filters.q} onChange={e=>update('q',e.target.value)} placeholder="City, county, ZIP, subdivision, address…" aria-label="Search by city, county, postal code, subdivision, address or MLS number"/></label><label><span>State</span><select value={filters.state} onChange={e=>update('state',e.target.value)}><option value="">Alabama & Florida</option><option value="AL">Alabama</option><option value="FL">Florida</option></select></label><label><span>Price range</span><div className="property-range"><input aria-label="Minimum price" inputMode="numeric" placeholder="Min $" value={filters.minPrice} onChange={e=>update('minPrice',e.target.value)}/><input aria-label="Maximum price" inputMode="numeric" placeholder="Max $" value={filters.maxPrice} onChange={e=>update('maxPrice',e.target.value)}/></div></label><button type="button" className="public-button property-filter-trigger" onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}>Filters <span>{filtersOpen?'−':'+'}</span></button><button className="public-button property-search-submit">Search</button></form>}
 {result?.sourceMode!=='pending'&&filtersOpen&&<div className="property-filter-panel"><div className="property-filter-grid">
 <label>City<input value={filters.city} onChange={e=>update('city',e.target.value)} placeholder="Any city"/></label><label>County<input value={filters.county} onChange={e=>update('county',e.target.value)} placeholder="Any county"/></label><label>Postal code<input value={filters.postalCode} onChange={e=>update('postalCode',e.target.value)} placeholder="ZIP"/></label><label>Subdivision<input value={filters.subdivision} onChange={e=>update('subdivision',e.target.value)} placeholder="Any subdivision"/></label><label>MLS number<input value={filters.mls} onChange={e=>update('mls',e.target.value)} placeholder="MLS #"/></label>
 <label>Minimum bedrooms<select value={filters.beds} onChange={e=>update('beds',e.target.value)}><option value="">Any</option>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>Minimum bathrooms<select value={filters.baths} onChange={e=>update('baths',e.target.value)}><option value="">Any</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Property type<select value={filters.type} onChange={e=>update('type',e.target.value)}><option value="">Any type</option>{['Residential','Residential Lease','Land','Farm','Commercial','Manufactured','Multi-Family'].map(x=><option key={x}>{x}</option>)}</select></label><label>Subtype<input value={filters.subtype} onChange={e=>update('subtype',e.target.value)} placeholder="House, condo, acreage…"/></label>
 <label>Min. living area<input type="number" min="0" value={filters.minSqft} onChange={e=>update('minSqft',e.target.value)} placeholder="sq ft"/></label><label>Max. living area<input type="number" min="0" value={filters.maxSqft} onChange={e=>update('maxSqft',e.target.value)} placeholder="sq ft"/></label><label>Minimum lot area (sq ft)<input type="number" min="0" value={filters.minLotArea} onChange={e=>update('minLotArea',e.target.value)} placeholder="Any"/></label><label>Minimum lot acres<input type="number" min="0" step=".1" value={filters.acres} onChange={e=>update('acres',e.target.value)} placeholder="Any"/></label><label>Year built from<input type="number" min="1600" max="2200" value={filters.yearBuilt} onChange={e=>update('yearBuilt',e.target.value)} placeholder="Any"/></label><label>Year built to<input type="number" min="1600" max="2200" value={filters.maxYearBuilt} onChange={e=>update('maxYearBuilt',e.target.value)} placeholder="Any"/></label><label>Maximum days on market<input type="number" min="0" max="10000" value={filters.maxDom} onChange={e=>update('maxDom',e.target.value)} placeholder="Any"/></label><label>Garage spaces<input type="number" min="0" max="50" value={filters.garage} onChange={e=>update('garage',e.target.value)} placeholder="Any"/></label>
 <label>Status<select value={filters.status} onChange={e=>update('status',e.target.value)}><option value="">Any permitted</option>{['Active','Coming Soon','Pending','Closed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Sort<select value={filters.sort} onChange={e=>update('sort',e.target.value)}><option value="newest">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="beds">Bedrooms</option><option value="baths">Bathrooms</option><option value="living-area">Living area</option><option value="days-on-market">Days on market</option></select></label>
 <label className="property-check"><input type="checkbox" checked={filters.pool==='true'} onChange={e=>update('pool',e.target.checked?'true':'')}/> Pool</label><label className="property-check"><input type="checkbox" checked={filters.waterfront==='true'} onChange={e=>update('waterfront',e.target.checked?'true':'')}/> Waterfront</label><label className="property-check"><input type="checkbox" checked={filters.newConstruction==='true'} onChange={e=>update('newConstruction',e.target.checked?'true':'')}/> New construction</label><label className="property-check"><input type="checkbox" checked={filters.openHouse==='true'} onChange={e=>update('openHouse',e.target.checked?'true':'')}/> Open house</label><label className="property-check"><input type="checkbox" checked={filters.priceReduced==='true'} onChange={e=>update('priceReduced',e.target.checked?'true':'')}/> Price reduced where source history supports it</label>
 <button type="button" className="property-reset" onClick={()=>{setFilters({...empty,status:sold?'Closed':''});setBounds(undefined);setPage(1);setOnlyFavorites(false);window.history.replaceState(null,'',window.location.pathname+(agentId?'?agent='+encodeURIComponent(agentId):''))}}>Clear all filters</button></div></div>}
 {result?.sourceMode!=='pending'&&(<div className="property-results-toolbar"><p aria-live="polite"><strong>{loading?'Searching…':onlyFavorites?favorites.length:result?.total??0}</strong> {onlyFavorites?'saved properties':result?.total===1?'property':'properties'}{result?.coverage==='partial'?' · Partial provider coverage':''}</p><div className="property-view-controls"><button type="button" onClick={()=>setView('list')} aria-pressed={view==='list'} className="property-view-button">List</button><button type="button" onClick={()=>setView('map')} aria-pressed={view==='map'} className="property-view-button">Map</button><button type="button" onClick={()=>setView('split')} aria-pressed={view==='split'} className="property-view-button">Split</button><button type="button" onClick={()=>setOnlyFavorites(!onlyFavorites)} aria-pressed={onlyFavorites} className="property-view-button">Saved homes · {favorites.length}</button><label className="property-inline-sort">Sort by <select value={filters.sort} onChange={e=>update('sort',e.target.value)}><option value="newest">Newest</option><option value="price-asc">Price low to high</option><option value="price-desc">Price high to low</option><option value="beds">Bedrooms</option><option value="living-area">Square feet</option></select></label></div></div>)}
 {error&&<div role="alert" className="property-error">{error}</div>}
 {result?.sourceMode==='pending'&&<div className="property-pending"><p className="public-kicker">Home search opening soon</p><h2>We’re preparing live listings for this market.</h2><p>Homes are not available in this area just yet. Contact our team and we’ll help you get started while listings are being added.</p><Link href="/contact" className="public-button">Talk with an RCRE agent</Link><Link href="/markets/florida" className="property-secondary-link">Explore Florida markets</Link><Link href="/markets/alabama" className="property-secondary-link">Explore Alabama markets</Link></div>}
 {hasInventory&&<div className={'property-results-layout '+(view==='split'?'is-split':'')+(view==='map'?' is-map':'')}><div className={'property-results-grid '+(view==='map'?'is-hidden':'')}>{visible.map(p=><article key={p.id} className="property-result-card"><Link className="property-result-main" href={'/homes/'+encodeURIComponent(p.id)+(agentId?'?agent='+encodeURIComponent(agentId):'')}><div className="property-result-image">{!isFixture&&p.photos?.[0]?.url?.startsWith('https://')?<img className="property-result-art" src={p.photos[0].url} alt={'Property in '+cityState(p)} loading="lazy"/>:<ListingVisual seed={p.id} className="property-result-art"/>}<span className="property-status-pill">{isFixture?'Local review':p.standardStatus}</span></div><div className="property-result-copy"><p className="property-result-price">{dollar(p.listPrice)}</p><h2>{propertyAddress(p)}</h2><p className="property-result-place">{cityState(p)}{p.countyOrParish?' · '+p.countyOrParish+' County':''}</p><div className="property-result-facts"><span>{p.bedroomsTotal??'—'} bd</span><span>{p.bathroomsTotal??'—'} ba</span><span>{p.livingArea?.toLocaleString()??'—'} sq ft</span><span>{p.lotSizeAcres?p.lotSizeAcres.toFixed(1)+' ac':''}</span></div><p className="property-result-type">{p.propertySubType||p.propertyType||'Property type unavailable'}</p></div></Link><button className="property-save-button" type="button" aria-pressed={favorites.includes(p.id)} onClick={()=>void saveProperty(p.id)} aria-label={(favorites.includes(p.id)?'Remove saved home ':'Save home ')+propertyAddress(p)}>{favorites.includes(p.id)?'♥ Saved':'♡ Save home'}</button></article>)}{!visible.length&&<div className="property-no-results"><h2>{onlyFavorites?'No saved homes match.':'No homes match these filters.'}</h2><p>Adjust the location or filters, or clear them to broaden the search.</p></div>}</div>{view!=='list'&&<PropertyMap key={filters.state+':'+filters.city+':'+filters.q} items={visible} selected={selected} onSelect={setSelected} onSearchArea={searchArea}/>}</div>}
 {hasInventory&&result.pages>1&&<nav className="property-pagination" aria-label="Property search pages"><button className="property-small-button" type="button" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {result.page} of {result.pages}</span><button className="property-small-button" type="button" disabled={page>=result.pages} onClick={()=>setPage(page+1)}>Next</button></nav>}
 {hasInventory&&<section className="property-saved-searches"><div><p className="public-kicker">Your saved searches</p><h2>Keep your search organized.</h2><p>Your saved homes and searches stay together here. Listing notifications remain off until an MLS agreement and notification path are confirmed.</p></div><form onSubmit={e=>{e.preventDefault();if(!savedName.trim())return;void persist(favorites,[...saved,{id:crypto.randomUUID(),name:savedName.trim(),filters:savedFilters(filters)}]).then(()=>setSavedName(''))}}><label>Search name<input required value={savedName} onChange={e=>setSavedName(e.target.value)} placeholder="My Florida shortlist"/></label><button className="public-button" type="submit">Save this search</button></form>{saved.length>0&&<ul>{saved.map(s=><li key={s.id}><strong>{s.name}</strong><div><button type="button" className="property-small-button" onClick={()=>{setFilters({...empty,...s.filters} as FormFilters);setOnlyFavorites(false);setPage(1)}}>Open</button><button type="button" className="property-small-button" onClick={()=>void persist(favorites,saved.filter(item=>item.id!==s.id))}>Remove</button></div></li>)}</ul>}<p aria-live="polite" className="property-save-status">{statusText}</p></section>}
 </section>
}
