import {randomUUID} from 'node:crypto'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import path from 'node:path'
import {storageRoot,getRecord,putRecord,readRecords} from './platform/store'
import type {PlatformActor} from './platform/auth'
import {academyManager,courseAllowed,progressFor,type AcademyDraft} from './academy-service'
import {academy} from '@/data/academy'
export type Upload={id:string;organizationId:string;ownerId:string;name:string;type:string;bytes:number}
export function createAcademyUpload(a:PlatformActor,name:string,type:string,buffer:Buffer){if(!academyManager(a))throw new Error('Trainer permission required');if(!buffer.length||buffer.length>100*1024*1024)throw new Error('File must be between 1 byte and 100 MB');const valid=(type==='application/pdf'&&buffer.subarray(0,5).toString()==='%PDF-')||(type==='image/png'&&buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(type==='image/jpeg'&&buffer[0]===255&&buffer[1]===216)||(type==='video/mp4'&&buffer.subarray(4,8).toString()==='ftyp')||(type==='text/vtt'&&buffer.subarray(0,6).toString()==='WEBVTT')||(type==='text/plain'&&!buffer.includes(0));if(!valid)throw new Error('Use a valid PDF, PNG, JPEG, MP4, VTT or plain text resource');const r={id:randomUUID(),organizationId:a.organizationId,ownerId:a.id,name:name.replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,100)||'lesson-resource',type,bytes:buffer.length};const dir=path.join(storageRoot,'academy-uploads');mkdirSync(dir,{recursive:true,mode:0o700});writeFileSync(path.join(dir,r.id),buffer,{mode:0o600});return putRecord('academy_upload',r)}
export function academyUploadFor(a:PlatformActor,id:string){const r=getRecord<Upload>('academy_upload',id);if(!r||r.organizationId!==a.organizationId)throw new Error('Resource unavailable');if(!academyManager(a)&&!readRecords<AcademyDraft>('academy_course').some(c=>c.organizationId===a.organizationId&&c.status==='published'&&courseAllowed(a,c.id)&&c.resources?.some(f=>f.id===id)&&(!c.prerequisite||academy.lessons.filter(l=>l.courseId===c.prerequisite).every(l=>progressFor(a).completedLessonIds.includes(l.id)))))throw new Error('Resource access denied');return {record:r,bytes:readFileSync(path.join(storageRoot,'academy-uploads',id))}}
