import { randomUUID } from 'node:crypto'
import { getRecord, putRecord, readRecords } from './platform/store'
import { PERSONAS,directory, type PlatformActor } from './platform/auth'
import { getSetting } from './platform/service'
import { academy } from '@/data/academy'
import type { AcademyProgress } from '@/data/academy-types'
export const academyManager = (a: PlatformActor) => ['trainer','broker_owner'].includes(a.role)
export type CoursePolicy = {id:string;organizationId:string;roles:string[];publicPreview:boolean}
export function courseAllowed(a:PlatformActor, courseId:string) {
 const p=getRecord<CoursePolicy>('academy_policy', `${a.organizationId}:${courseId}`)
 return !p || p.roles.length===0 || p.roles.includes(a.role) || academyManager(a)
}
export type Progress = AcademyProgress & {id:string;organizationId:string;ownerId:string;bookmarks:string[];positions:Record<string,number>;updatedAt:string}
export function progressFor(a:PlatformActor):Progress { return getRecord<Progress>('academy_progress',`${a.organizationId}:${a.id}`) ?? {id:`${a.organizationId}:${a.id}`,organizationId:a.organizationId,ownerId:a.id,completedLessonIds:[],bookmarks:[],positions:{},updatedAt:new Date().toISOString()} }
export function updateProgress(a:PlatformActor,input:{lessonId:string;complete?:boolean;bookmark?:boolean;seconds?:number}) {
 const custom=getRecord<AcademyDraft>('academy_course',input.lessonId)
 const lesson=academy.lessons.find(l=>l.id===input.lessonId) ?? (custom && custom.organizationId===a.organizationId && custom.status==='published' ? {id:custom.id,courseId:custom.id} : undefined)
 if(!lesson || !courseAllowed(a,lesson.courseId)) throw new Error('Lesson unavailable')
 if(custom?.prerequisite){const prerequisite=academy.lessons.filter(l=>l.courseId===custom.prerequisite);const progress=progressFor(a);if(prerequisite.some(l=>!progress.completedLessonIds.includes(l.id)))throw new Error('Complete the prerequisite course first')}
 const p=progressFor(a)
 for(const [key,value] of [['completedLessonIds',input.complete],['bookmarks',input.bookmark]] as const) if(typeof value==='boolean') p[key]=value ? [...new Set([...p[key],lesson.id])] : p[key].filter(id=>id!==lesson.id)
 if(input.seconds!==undefined) {if(!Number.isFinite(input.seconds)||input.seconds<0||input.seconds>86400)throw new Error('Invalid position');p.positions[lesson.id]=input.seconds}
 p.lastViewedLessonId=lesson.id;p.updatedAt=new Date().toISOString();return putRecord('academy_progress',p)
}
export type AcademyDraft = {lastEditedBy?:string;submittedBy?:string;resources?:{id:string;name:string;type:string}[];reviewedBy?:string;id:string;organizationId:string;ownerId:string;title:string;body:string;status:'draft'|'review'|'published'|'archived';version:number;order:number;prerequisite:string;revisions:{version:number;title:string;body:string;at:string;resources?:{id:string;name:string;type:string}[];order?:number;prerequisite?:string}[]}
export function academyReviews(a:PlatformActor){return academyManager(a)?readRecords<AcademyDraft>('academy_course').filter(c=>c.organizationId===a.organizationId&&c.status==='review').map(c=>({id:'academy:'+c.id,title:c.title,kind:'Course publication',state:(c.submittedBy??c.lastEditedBy??c.ownerId)===a.id?'Awaiting an independent reviewer':'Ready for your review',version:c.version,href:'/training/manage#'+encodeURIComponent(c.id)})):[]}
export type Assignment = {id:string;organizationId:string;ownerId:string;courseId:string;targetType:string;target:string;due:string;exemptions:string[];remindedAt?:string}
export function assignmentsFor(a:PlatformActor) {return readRecords<Assignment>('academy_assignment').filter(r=>r.organizationId===a.organizationId&&(academyManager(a)||r.targetType==='all'||(r.targetType==='lead_source'&&readRecords<{organizationId:string;ownerId:string;source:string}>('contacts').some(c=>c.organizationId===a.organizationId&&c.ownerId===a.id&&c.source===r.target))||({agent:a.id,role:a.role,market:a.market,office:a.officeId,team:a.teamId} as Record<string,string>)[r.targetType]===r.target)&&!r.exemptions.includes(a.id))}
export function manageAcademy(a:PlatformActor,b:Record<string,unknown>) {
 if(!academyManager(a))throw new Error('Trainer permission required')
 if(b.action==='policy') {const courseId=String(b.courseId);if(!academy.courses.some(c=>c.id===courseId)&&!readRecords<AcademyDraft>('academy_course').some(c=>c.id===courseId&&c.organizationId===a.organizationId))throw new Error('Unknown course');if(b.publicPreview===true&&!academy.courses.some(c=>c.id===courseId&&c.publicPreview))throw new Error('Source rights do not permit a public preview of this course');return putRecord('academy_policy',{id:`${a.organizationId}:${courseId}`,organizationId:a.organizationId,roles:Array.isArray(b.roles)?b.roles.map(String):[],publicPreview:b.publicPreview===true})}
 if(b.action==='assignment') {if(!academy.courses.some(c=>c.id===b.courseId)&&!readRecords<AcademyDraft>('academy_course').some(c=>c.id===b.courseId&&c.organizationId===a.organizationId&&c.status==='published'))throw new Error('Choose a published course');if(!['all','agent','role','market','office','team','lead_source'].includes(String(b.targetType)))throw new Error('Invalid assignment target');if(!/^\d{4}-\d{2}-\d{2}$/.test(String(b.due))||!Number.isFinite(Date.parse(String(b.due)))||new Date(String(b.due)).toISOString().slice(0,10)!==String(b.due))throw new Error('Due date required');return putRecord('academy_assignment',{id:randomUUID(),organizationId:a.organizationId,ownerId:a.id,courseId:String(b.courseId),targetType:String(b.targetType),target:String(b.target||''),due:String(b.due),exemptions:[]})}
 if(b.action==='remind'||b.action==='exempt') {const r=getRecord<Assignment>('academy_assignment',String(b.id));if(!r||r.organizationId!==a.organizationId)throw new Error('Assignment unavailable');if(b.action==='remind'){r.remindedAt=new Date().toISOString();for(const person of directory(a.organizationId).filter(p=>!p.disabled&&assignmentMatches(p,r))){const settings=getSetting(person,'personal').value;const hour=Number(new Intl.DateTimeFormat('en-US',{hour:'numeric',hourCycle:'h23',timeZone:settings.timezone||'America/New_York'}).format(new Date()));const start=Number(settings.quietStart??22),end=Number(settings.quietEnd??7);const quiet=start>end?(hour>=start||hour<end):(hour>=start&&hour<end);const title=academy.courses.find(c=>c.id===r.courseId)?.title??getRecord<AcademyDraft>('academy_course',r.courseId)?.title??'Assigned course';putRecord('notifications',{id:randomUUID(),organizationId:a.organizationId,ownerId:person.id,assignmentId:r.id,title:`Training reminder: ${title} · due ${r.due}`,href:'/training/manage',at:r.remindedAt,suppressed:quiet||settings.inAppNotifications===false,read:false})}}else r.exemptions=[...new Set([...r.exemptions,String(b.learnerId)])];return putRecord('academy_assignment',r)}
 if(b.action==='config'){const categories=Array.isArray(b.categories)?b.categories.map(String).map(x=>x.trim()).filter(Boolean):[];if(!categories.length||categories.length>20||categories.some(c=>c.length>70))throw new Error('Provide 1–20 short category names');const order=Array.isArray(b.order)?b.order.map(String):[];if(order.length!==academy.courses.length||new Set(order).size!==academy.courses.length||order.some(id=>!academy.courses.some(c=>c.id===id)))throw new Error('Course order must contain each imported course exactly once');return putRecord('academy_config',{id:a.organizationId,categories,order})}
 const old=b.id?getRecord<AcademyDraft>('academy_course',String(b.id)):null
 if(old&&old.organizationId!==a.organizationId)throw new Error('Course unavailable')
 if(old&&Number(b.version)!==old.version)throw new Error('This draft changed. Reload before saving.')
 const title=String(b.title||'').trim(),body=String(b.body||'').trim();if(!title||!body||body.length>50000)throw new Error('Title and lesson text are required')
 const order=Number(b.order)||1;if(!Number.isInteger(order)||order<1||order>1000)throw new Error('Course order must be between 1 and 1000');const prerequisite=String(b.prerequisite||'');if(prerequisite&&!academy.courses.some(c=>c.id===prerequisite))throw new Error('Unknown prerequisite course')
 const status=String(b.status||'draft');if(!['draft','review','published','archived'].includes(status))throw new Error('Invalid state')
 if(status==='published'&&(!old||old.status!=='review'||(old.submittedBy??old.lastEditedBy??old.ownerId)===a.id))throw new Error('A different instructor or broker owner must publish a submitted review version')
 if(status==='published'&&old&&(title!==old.title||body!==old.body||order!==old.order||prerequisite!==old.prerequisite))throw new Error('Changed content must be submitted for review again')
 const resources=Array.isArray(b.resources)?b.resources.map((resource)=>{const id=String(typeof resource==='object'&&resource?('id' in resource?resource.id:''):resource);const file=getRecord<{id:string;name:string;type:string;organizationId:string;ownerId:string}>('academy_upload',id);if(!file||file.organizationId!==a.organizationId)throw new Error('Resource unavailable');return {id:file.id,name:file.name,type:file.type}}):old?.resources??[]
 if(status==='published'&&JSON.stringify(resources)!==JSON.stringify(old?.resources??[]))throw new Error('Changed resources must be submitted for review again')
 return putRecord('academy_course',{lastEditedBy:status==='published'?(old?.lastEditedBy??old?.ownerId):a.id,submittedBy:status==='review'?a.id:status==='published'?(old?.submittedBy??old?.lastEditedBy??old?.ownerId):undefined,resources,reviewedBy:status==='published'?a.id:undefined,id:old?.id??randomUUID(),organizationId:a.organizationId,ownerId:old?.ownerId??a.id,title,body,status,version:(old?.version??0)+1,order,prerequisite,revisions:[...(old?.revisions??[]),...(old?[{version:old.version,title:old.title,body:old.body,resources:old.resources,order:old.order,prerequisite:old.prerequisite,at:new Date().toISOString()}]:[])]})
}

export function assignmentMatches(a:PlatformActor,r:Assignment){return r.organizationId===a.organizationId&&!r.exemptions.includes(a.id)&&(r.targetType==='all'||(r.targetType==='lead_source'&&readRecords<{organizationId:string;ownerId:string;source:string}>('contacts').some(c=>c.organizationId===a.organizationId&&c.ownerId===a.id&&c.source===r.target))||({agent:a.id,role:a.role,market:a.market,office:a.officeId,team:a.teamId} as Record<string,string>)[r.targetType]===r.target)}
export const defaultCategories=['General Discussion','AI Questions','Lead Follow Up','Marketing','Listings','AI Tools','Wins','Training','RCRE Updates']
export function academyConfig(org='rcre-local'){return getRecord<{id:string;categories:string[];order:string[]}>('academy_config',org)??{id:org,categories:defaultCategories,order:academy.courses.map(c=>c.id)}}
export function publicCourseAllowed(courseId:string,organizationId='rcre-local'){return academy.courses.some(c=>c.id===courseId&&c.publicPreview)&&getRecord<CoursePolicy>('academy_policy',`${organizationId}:${courseId}`)?.publicPreview===true}

export function visibleAcademyCourses(a:PlatformActor){const progress=progressFor(a);return readRecords<AcademyDraft>('academy_course').filter(c=>c.organizationId===a.organizationId&&(academyManager(a)||(c.status==='published'&&courseAllowed(a,c.id)&&(!c.prerequisite||academy.lessons.filter(l=>l.courseId===c.prerequisite).every(l=>progress.completedLessonIds.includes(l.id)))))).sort((x,y)=>x.order-y.order).map(c=>academyManager(a)?c:{...c,revisions:[]})}
