import { actorOrNull } from './platform/auth'
import { demoEnabled } from './platform/auth'
import { getRepository } from './db'
import { repositoryRoleForPlatform } from './auth/role-mapping'
import {getSetting} from './platform/service'
import {getRecord} from './platform/store'
import { USERS, type DemoUser } from '@/data/demo'
export { SESSION_COOKIE } from './platform/auth'
export async function currentUser():Promise<(DemoUser & {platformRole:import('./platform/auth').PlatformRole})|null>{const a=await actorOrNull();if(!a)return null;if(!demoEnabled()){const repo=await getRepository();const profile=await repo.getDomainRecord<Record<string,unknown>>({userId:a.id,organizationId:a.organizationId,role:repositoryRoleForPlatform(a.role)},'member_profiles',a.id);const name=a.name;const markets=Array.isArray(profile?.data.markets)?(profile!.data.markets as unknown[]).filter((v):v is string=>typeof v==='string'):[];const title=typeof profile?.data.professionalTitle==='string'&&profile.data.professionalTitle?profile.data.professionalTitle:a.role.replaceAll('_',' ');return {id:a.id,name,firstName:name.split(' ')[0],initials:name.split(/\s+/).map(n=>n[0]).join('').slice(0,3),title,market:markets.join(', ')||a.market,role:['broker_owner','managing_broker','team_leader'].includes(a.role)?'broker':'agent',platformRole:a.role,photo:profile?.data.headshotAssetId?'/api/profile/photo':undefined,stats:null}}const prefs=getSetting(a,'personal').value;const original=USERS.find(u=>u.id===a.id)??USERS[2];return {...original,id:a.id,name:prefs?.name||a.name,firstName:(prefs?.name||a.name).split(' ')[0],initials:a.name.split(' ').map(n=>n[0]).join(''),photo:getRecord('profile_photos',a.organizationId+':'+a.id)?'/api/profile/photo':undefined,title:a.role.replaceAll('_',' '),market:a.market,role:['broker_owner','managing_broker','team_leader'].includes(a.role)?'broker':'agent',platformRole:a.role}}
