import {CinematicGallery} from '@/components/public/CinematicGallery'
import type {Metadata} from 'next'
import Link from 'next/link'
import {PublicShell} from '@/components/public/PublicShell'
import {HomeMetroJournal} from '@/components/public/HomeMetroJournal'
import {MarketExplorer} from '@/components/public/MarketExplorer'
import {notFound} from 'next/navigation'
import {getPublished,getPublicRecord} from '@/lib/public/server'
export const dynamic='force-dynamic'
const defaultMetadata:Metadata={title:'RCRE Group | Homes, people & possibility in Alabama and Florida',description:'Buy, sell, and build your real estate career with River City Real Estate Group. Explore Alabama and Florida, meet the team, and plan your next move.',alternates:{canonical:'https://rcregroup.com/'}}
export async function generateMetadata():Promise<Metadata>{const p=await getPublished('/');return {...defaultMetadata,robots:{index:p?.noIndex!==true,follow:true},openGraph:{title:p?.seoTitle||p?.title||String(defaultMetadata.title),description:p?.description||defaultMetadata.description||undefined,images:p?.image?.src?[{url:'https://rcregroup.com'+p.image.src,alt:p.image.alt}]:undefined},title:p?.seoTitle||p?.title||defaultMetadata.title,description:p?.description||defaultMetadata.description,alternates:{canonical:p?.canonical||'https://rcregroup.com/'}}}
export default async function Home(){if((await getPublicRecord('/'))?.status==='archived')notFound();const edited=await getPublished('/');return <PublicShell><MarketExplorer title={edited?.title} description={edited?.description} image={edited?.image}/>{edited?.body&&<section className="public-wrap public-prose"><p>{edited.body}</p></section>}<section className="public-paths public-wrap">{[['01','Buy with clarity','Turn your priorities into a thoughtful shortlist, then move forward with an informed plan.','/buying','Explore buying'],['02','Sell with purpose','Understand the market, prepare the property, and evaluate the whole offer.','/selling','Explore selling'],['03','Grow with RCRE','Structure, coaching, training, and a connected team for the business you want to build.','/join','Build your career']].map(([n,title,text,href,cta])=><article key={n}><span className="public-number">{n}</span><h2>{title}</h2><p>{text}</p><Link href={href} className="public-text-link">{cta} ↗</Link></article>)}</section><CinematicGallery/><HomeMetroJournal/><section className="public-wrap public-feature"><div><p className="public-kicker">A relationship, not a transaction</p><h2>The right people<br/>make the difference.</h2><p>Work with a team that listens first and keeps the next step clear. Meet the professionals behind River City Real Estate Group.</p><Link href="/team" className="public-button secondary">Meet our people ↗</Link></div><div className="public-leader-pair"><Link href="/agent/julio-arango"><img src="/brand/people/julio-arango.jpg" alt="Julio Arango" width="320" height="360"/><h3>Julio Arango</h3><p>Qualifying Broker</p></Link><Link href="/agent/taquilla-allen"><img src="/brand/people/taquilla-allen.jpg" alt="Taquilla Allen" width="320" height="360"/><h3>Taquilla Allen</h3><p>Managing Broker</p></Link></div></section><section className="public-lender-band public-wrap"><p className="public-kicker">Your financing, explained</p><h2>A home search is better<br/>with a financing plan.</h2><p>Meet Jeremy McDonald, RCRE’s Preferred Lender. Compare the options, understand the costs, and ask the questions that matter to you.</p><Link className="public-button" href="/financing">Meet Jeremy McDonald ↗</Link><small>You are free to choose any lender. Using Jeremy McDonald or Loan Factory is not required to work with RCRE or purchase a property.</small></section><section className="public-wrap public-resource-links"><h2>A little knowledge.<br/>A more confident next step.</h2><div><Link href="/first-time-buyers">Buying your first home <span>↗</span></Link><Link href="/relocation">Moving to a new market <span>↗</span></Link><Link href="/blog">Local insights & resources <span>↗</span></Link></div></section></PublicShell>}
