'use client'
import {useCallback,useEffect,useState} from 'react'
type Profile={id:string;name:string;publicTitle:string;phone:string;email:string;license:string;market:'Alabama'|'Florida'|'Alabama & Florida';bio:string;specialties:string[];socialLinks:{instagram:string;facebook:string;linkedin:string};websiteTemplate:string;publicVisible:boolean;version:number;image:string|null}
const templates=[['signature','RCRE Signature'],['luxury','Luxury'],['rural-land','Rural and Land'],['investor','Investor'],['urban-modern','Urban Modern'],['suburban-family','Suburban Family'],['new-construction','New Construction'],['historic-heritage','Historic Heritage']]
const field='w-full rounded border border-hair bg-ink-raised px-3 py-2 text-chalk'
export function AgentProfileAdmin(){
 const [profiles,setProfiles]=useState<Profile[]>([]),[selected,setSelected]=useState(''),[form,setForm]=useState<Profile|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setError('');try{const r=await fetch('/api/admin/agent-profiles',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setProfiles(d.profiles);const next=d.profiles.find((p:Profile)=>p.id===selected)??d.profiles[0];if(next){setSelected(next.id);setForm(next)}}catch(e){setError((e as Error).message)}},[selected])
 useEffect(()=>{void load()},[load])
 function edit<K extends keyof Profile>(key:K,value:Profile[K]){setForm(f=>f?({...f,[key]:value}):f)}
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setError('');setNotice('');try{const r=await fetch('/api/admin/agent-profiles/'+encodeURIComponent(form.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw Error(d.error);setForm({...form,...d.profile});setProfiles(p=>p.map(x=>x.id===form.id?{...x,...d.profile}:x));setNotice('Public profile saved in local development storage. Hosted production persistence is not connected.')}catch(e){setError((e as Error).message)}}
 return <section className="mx-auto max-w-7xl px-5 pt-8 sm:px-8" aria-labelledby="agent-profile-admin-title"><div className="border-b border-hair pb-5"><p className="eyebrow">Leadership · canonical roster</p><h2 id="agent-profile-admin-title" className="font-display text-h3 mt-2">Agent identity and public profiles</h2><p className="text-sm text-chalk-muted mt-2 max-w-3xl">Edits apply to the canonical public roster entry. Public marketing title is separate from internal operating permissions. Profile edits here are local until hosted PostgreSQL is connected.</p></div>
 {error&&<p role="alert" className="my-4 border border-red-500 p-3">{error}</p>}{notice&&<p role="status" className="my-4 border border-hair p-3">{notice}</p>}
 {profiles.length===0&&!error&&<p className="py-5 text-chalk-muted">No profiles in your authorized scope.</p>}
 {form&&<div className="grid gap-6 py-6 lg:grid-cols-[15rem_minmax(0,1fr)]"><nav aria-label="Canonical agent profiles" className="space-y-1">{profiles.map(p=><button type="button" key={p.id} aria-current={selected===p.id?'true':undefined} className="block w-full rounded px-3 py-2 text-left hover:bg-ink-raised" onClick={()=>{setSelected(p.id);setForm(p);setNotice('')}}>{p.name}<span className="block text-xs text-chalk-muted">{p.market} · {p.publicVisible?'Public':'Hidden'}</span></button>)}</nav>
 <form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><h3 className="font-display text-h4 sm:col-span-2">{form.name}</h3><label>Public title<input className={field+' mt-1'} value={form.publicTitle} onChange={e=>edit('publicTitle',e.target.value)}/></label><label>Public phone<input className={field+' mt-1'} value={form.phone} onChange={e=>edit('phone',e.target.value)}/></label><label>Public email<input type="email" className={field+' mt-1'} value={form.email} onChange={e=>edit('email',e.target.value)}/></label><label>License numbers<input className={field+' mt-1'} value={form.license} onChange={e=>edit('license',e.target.value)} aria-describedby="license-hint"/><span id="license-hint" className="block text-xs text-chalk-muted">Enter only verified license identifiers.</span></label><label>Public market<select className={field+' mt-1'} value={form.market} onChange={e=>edit('market',e.target.value as Profile['market'])}><option>Alabama</option><option>Florida</option><option>Alabama &amp; Florida</option></select></label><label>Website design<select className={field+' mt-1'} value={form.websiteTemplate} onChange={e=>edit('websiteTemplate',e.target.value)}>{templates.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label className="sm:col-span-2">Biography<textarea className={field+' mt-1 min-h-32'} maxLength={5000} value={form.bio} onChange={e=>edit('bio',e.target.value)}/></label><label className="sm:col-span-2">Verified specialties, comma separated<input className={field+' mt-1'} value={form.specialties.join(', ')} onChange={e=>edit('specialties',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>{(['instagram','facebook','linkedin'] as const).map(k=><label className="capitalize" key={k}>{k}<input type="url" className={field+' mt-1'} value={form.socialLinks[k]} onChange={e=>edit('socialLinks',{...form.socialLinks,[k]:e.target.value})} placeholder="https://"/></label>)}<label className="flex items-center gap-3 sm:col-span-2"><input type="checkbox" checked={form.publicVisible} onChange={e=>edit('publicVisible',e.target.checked)}/> Show in active public roster and profile pages</label><div className="flex gap-3 sm:col-span-2"><button className="btn-primary">Save canonical profile</button><button type="button" className="btn-ghost" onClick={()=>void load()}>Reload</button></div><p className="text-xs text-chalk-muted sm:col-span-2">Operational role and account access are managed separately in Settings → People. This editor cannot promote users or change internal permissions.</p></form></div>}
 </section>
}
