'use client'
import { useCallback, useEffect, useState } from 'react'

type License = { state: 'Alabama' | 'Florida'; number: string }
type Member = { userId: string; canonicalPersonId: string | null; email: string; name: string; platformRole: string; active: boolean; accountStatus: string; officeId: string; teamId: string; market: string; lastLoginAt: string | null; publicVisible: boolean | null; onboardingComplete: boolean; onboardingStepsComplete: number; licenses: License[]; websiteTemplate: string | null; websiteSlug: string | null; professionalTitle: string; biography: string; specialties: string[]; markets: string[] }
const roles = ['agent', 'team_leader', 'managing_broker', 'broker_owner', 'transaction_coordinator', 'marketing_admin', 'trainer']
const field = 'rounded border border-hair bg-ink-raised px-2 py-2 text-sm text-chalk'
export function AgentLifecycleAdmin({ managingBroker = false }: { managingBroker?: boolean }) {
  const [rows, setRows] = useState<Member[]>([]), [edits, setEdits] = useState<Record<string, Partial<Member>>>({}), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const load = useCallback(async () => { setError(''); try { const response = await fetch('/api/admin/agents', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRows(data.agents) } catch (cause) { setError((cause as Error).message) } }, [])
  useEffect(() => { void load() }, [load])
  function patch(id: string, value: Partial<Member>) { setEdits(current => ({ ...current, [id]: { ...current[id], ...value } })) }
  async function save(row: Member) {
    const value = { ...row, ...edits[row.userId] }; setBusy(row.userId); setNotice(''); setError('')
    try {
      const response = await fetch(`/api/admin/agents/${encodeURIComponent(row.userId)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role: value.platformRole, officeId: value.officeId, teamId: value.teamId, market: value.market, active: value.active, publicVisible: value.publicVisible ?? false, licenses: value.licenses ?? [], professionalTitle: value.professionalTitle, biography: value.biography, specialties: value.specialties, markets: value.markets }) })
      const data = await response.json(); if (!response.ok) throw new Error(data.error)
      setEdits(current => { const next = { ...current }; delete next[row.userId]; return next }); await load(); setNotice(`${row.name} profile and account settings saved.`)
    } catch (cause) { setError((cause as Error).message) } finally { setBusy('') }
  }
  async function revoke(row: Member) { setBusy(row.userId); setError(''); setNotice(''); try { const response = await fetch(`/api/admin/agents/${encodeURIComponent(row.userId)}/revoke-sessions`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setNotice(`${data.revoked} active session(s) revoked for ${row.name}.`) } catch (cause) { setError((cause as Error).message) } finally { setBusy('') } }
  const value = <K extends keyof Member>(row: Member, key: K) => (edits[row.userId]?.[key] ?? row[key]) as Member[K]
  return <section className="mt-8 rounded border border-hair bg-ink-raised/50 p-4 sm:p-6" aria-labelledby="agent-lifecycle-title">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">People operations</p><h2 id="agent-lifecycle-title" className="mt-2 font-display text-h3">Agent accounts and onboarding</h2><p className="mt-2 max-w-3xl text-sm text-chalk-muted">Manage account access and the canonical profile record. Role changes do not create or relink canonical people automatically.</p></div><button className="btn-ghost" onClick={() => void load()} disabled={!!busy}>Refresh</button></div>
    {error && <p className="my-4 rounded border border-red-500/50 p-3 text-sm" role="alert">{error}</p>}{notice && <p className="my-4 rounded border border-hair p-3 text-sm" role="status">{notice}</p>}
    <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1080px] border-collapse text-left text-sm"><thead><tr className="border-b border-hair text-chalk-muted"><th className="p-2">Agent</th><th className="p-2">Account / last login</th><th className="p-2">Role / office / market</th><th className="p-2">Licenses</th><th className="p-2">Profile / public</th><th className="p-2">Actions</th></tr></thead><tbody>{rows.map(row => {
      const licenses = value(row, 'licenses') ?? []
      return <tr key={row.userId} className="border-b border-hair align-top"><td className="p-2"><strong>{row.name}</strong><div className="text-xs text-chalk-muted">{row.email}</div><div className="mt-1 text-xs text-chalk-muted">{row.canonicalPersonId ? `Verified person: ${row.canonicalPersonId}` : 'Canonical person link: unknown'}</div></td>
        <td className="p-2"><select className={field} aria-label={`${row.name} account status`} value={value(row, 'active') ? 'active' : 'inactive'} onChange={e => patch(row.userId, { active: e.target.value === 'active' })}><option value="active">Active</option><option value="inactive">Inactive</option></select><div className="mt-2 text-xs text-chalk-muted">{row.lastLoginAt ? `Last login ${new Date(row.lastLoginAt).toLocaleString()}` : 'Last login: not recorded'}</div></td>
        <td className="p-2"><select className={field+' block w-full'} aria-label={`${row.name} role`} value={value(row, 'platformRole')} onChange={e => patch(row.userId, { platformRole: e.target.value })}>{roles.filter(role => !managingBroker || ['agent', 'team_leader', 'transaction_coordinator'].includes(role)).map(role => <option key={role} value={role}>{role.replaceAll('_', ' ')}</option>)}</select><div className="mt-2 flex gap-1"><select className={field} aria-label={`${row.name} office`} value={value(row, 'officeId')} onChange={e => patch(row.userId, { officeId: e.target.value, teamId: e.target.value, market: e.target.value === 'al' ? 'Alabama' : e.target.value === 'fl' ? 'Florida' : value(row, 'market') })}>{(managingBroker ? ['al'] : ['al', 'fl', 'all']).map(office => <option key={office} value={office}>{office === 'al' ? 'Alabama' : office === 'fl' ? 'Florida' : 'All offices'}</option>)}</select><input className={field+' min-w-32'} aria-label={`${row.name} market`} value={value(row, 'market')} onChange={e => patch(row.userId, { market: e.target.value })}/></div></td>
        <td className="p-2"><div className="space-y-1">{licenses.map((license, index) => <div key={index} className="flex gap-1"><select className={field} aria-label={`${row.name} license state ${index+1}`} value={license.state} onChange={e => patch(row.userId, { licenses: licenses.map((item, i) => i === index ? { ...item, state: e.target.value as License['state'] } : item) })}><option>Alabama</option><option>Florida</option></select><input className={field+' w-32'} aria-label={`${row.name} license number ${index+1}`} value={license.number} onChange={e => patch(row.userId, { licenses: licenses.map((item, i) => i === index ? { ...item, number: e.target.value } : item) })}/><button className="btn-ghost" aria-label={`Remove ${row.name} license ${index+1}`} onClick={() => patch(row.userId, { licenses: licenses.filter((_, i) => i !== index) })}>×</button></div>)}<button className="btn-ghost" onClick={() => patch(row.userId, { licenses: [...licenses, { state: 'Alabama', number: '' }] })}>Add license</button></div></td>
        <td className="p-2"><input className={field+' block w-48'} aria-label={`${row.name} professional title`} placeholder="Professional title" value={value(row, 'professionalTitle')} onChange={e => patch(row.userId, { professionalTitle: e.target.value })}/><select className={field+' block mt-2'} aria-label={`${row.name} public roster visibility`} value={value(row, 'publicVisible') === null ? 'unknown' : value(row, 'publicVisible') ? 'visible' : 'hidden'} onChange={e => patch(row.userId, { publicVisible: e.target.value === 'unknown' ? null : e.target.value === 'visible' })}><option value="unknown">Not set</option><option value="visible">Visible</option><option value="hidden">Hidden</option></select><textarea className={field+' mt-2 min-h-20 w-48'} aria-label={`${row.name} biography`} value={value(row, 'biography')} onChange={e => patch(row.userId, { biography: e.target.value })} placeholder="Biography"/><input className={field+' mt-2 block w-48'} aria-label={`${row.name} specialties`} value={(value(row, 'specialties') ?? []).join(', ')} onChange={e => patch(row.userId, { specialties: e.target.value.split(',').map(x => x.trim()).filter(Boolean) })} placeholder="Specialties, comma separated"/><input className={field+' mt-2 block w-48'} aria-label={`${row.name} markets served`} value={(value(row, 'markets') ?? []).join(', ')} onChange={e => patch(row.userId, { markets: e.target.value.split(',').map(x => x.trim()).filter(Boolean) })} placeholder="Markets served"/><div className="mt-2 text-xs text-chalk-muted">Onboarding {row.onboardingStepsComplete}/5 · {row.onboardingComplete ? 'Complete' : 'In progress'}<br/>Website {row.websiteTemplate ?? 'not selected'}{row.websiteSlug ? ` · ${row.websiteSlug}` : ''}</div></td>
        <td className="p-2"><div className="flex flex-col items-start gap-2"><button className="btn-primary" disabled={busy === row.userId} onClick={() => void save(row)}>{busy === row.userId ? 'Working…' : 'Save changes'}</button><button className="btn-ghost" disabled={busy === row.userId || !row.active} onClick={() => void revoke(row)}>Revoke sessions</button></div></td></tr>
    })}</tbody></table>{rows.length === 0 && <p className="p-5 text-sm text-chalk-muted">No authorized member records are currently available.</p>}</div>
    <p className="mt-4 text-xs text-chalk-muted">Deactivation revokes active sessions. Historical records remain. Production headshot upload stays disabled until private storage and malware scanning are configured.</p>
  </section>
}
