'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import type {AgentInspection} from '@/lib/agent-inspector'
const date=(s:string|null|undefined)=>s?new Date(s).toLocaleString():'Unknown / not recorded'
export function AgentInspector({agentId}:{agentId?:string}){
 const [data,setData]=useState<AgentInspection|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all')
 async function load(){try{const r=await fetch('/api/agent-inspector'+(agentId?'?agentId='+encodeURIComponent(agentId):''));const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[agentId]);const a=data?.agent
 const field='border border-hair rounded-control bg-ink-raised px-3 py-2 text-chalk'
 return <div className="mx-auto max-w-7xl p-5 sm:p-8 lg:p-10"><p className="eyebrow">Broker workspace · Synthetic local records</p><h1 className="font-display text-h2 mt-3">{a?a.name:'Agent inspection'}</h1><p className="text-chalk-muted mt-3 max-w-3xl">Inspect recorded evidence, commitments and training in one place. Missing events indicate a coverage gap; they do not prove that a person never made contact.</p>{error&&<div role="alert" className="border border-red-500 p-4 mt-5">{error}<button className="underline ml-4" onClick={()=>void load()}>Retry</button></div>}<nav className="flex flex-wrap gap-3 my-6"><Link className="btn-ghost" href="/command">Command</Link>{agentId&&<Link className="btn-ghost" href="/agents">All scoped agents</Link>}<button className="btn-ghost" onClick={()=>void load()}>Refresh evidence</button>{a&&<a className="btn-ghost" href={'/api/agent-inspector?agentId='+encodeURIComponent(a.id)+'&download=1'}>Download scoped inspection</a>}</nav>
 {!data&&!error&&<p role="status">Loading scoped records…</p>}{data&&!a&&<><label className="block">Find an agent<input className={field+' block w-full max-w-md mt-2'} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or market"/></label><div className="mt-6 divide-y divide-hair">{data.roster.filter(r=>`${r.name} ${r.market}`.toLowerCase().includes(query.toLowerCase())).map(r=><article key={r.id} className="py-5 flex flex-wrap justify-between gap-4"><div><h2 className="font-display text-h3"><Link href={'/agents/'+r.id}>{r.name}</Link></h2><p className="text-chalk-muted">{r.market} · {r.leads} scoped leads · {r.overdueTasks} overdue tasks</p></div><Link className="btn-ghost" href={'/agents/'+r.id}>Inspect agent →</Link></article>)}</div>{!data.roster.length&&<p>No agents in your authorized office scope.</p>}</>}
 {a&&<><p className="text-label text-chalk-muted">{a.market} · Evidence refreshed {date(a.generatedAt)}</p><dl className="grid grid-cols-2 lg:grid-cols-3 gap-6 my-8">{Object.entries(a.summary).map(([k,v])=><div key={k} className="border-t border-hair pt-3"><dt className="text-label text-chalk-muted">{({leads:'Current leads',noRecordedFirstOutreach:'No recorded first outreach',contactedInactive:`Contacted, inactive over ${a.inactiveDays} days`,recordedCallAttempts:'Recorded outbound call events',explicitConnectedConversations:'Explicit connected conversations',overdueTasks:'Overdue tasks'} as Record<string,string>)[k]}</dt><dd className="font-display text-h3 mt-2">{v}</dd></div>)}</dl>
 <section className="mt-10"><div className="flex flex-wrap gap-4 justify-between items-center"><h2 className="font-display text-h3">Leads and outreach evidence</h2><select aria-label="Outreach evidence filter" className={field} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All leads</option><option value="never">No recorded first outreach</option><option value="inactive">Contacted, now inactive</option></select></div>{a.contacts.filter(c=>filter==='never'?!c.firstTouchAt:filter==='inactive'?c.firstTouchAt&&(!c.lastOutboundAt||Date.now()-Date.parse(c.lastOutboundAt)>a.inactiveDays*86400000):true).map(c=><article key={c.id} className="py-4 border-b border-hair"><Link className="font-semibold underline" href={c.href}>{c.name}</Link><p className="text-chalk-muted text-label mt-1">{c.source} · {c.stage} · Current stage entered {date(c.stageEnteredAt)}</p><p className="text-label mt-1">Last recorded outbound: {date(c.lastOutboundAt)}</p>{a.stageEvidence.find(p=>p.contactId===c.id)?.reasons.map(r=><p className="text-label text-chalk-muted mt-1" key={r}>{r}</p>)}</article>)}{!a.contacts.length&&<p className="py-5 text-chalk-muted">No assigned leads.</p>}</section>
 <div className="grid lg:grid-cols-2 gap-10 mt-10"><section><h2 className="font-display text-h3">Tasks and commitments</h2>{a.tasks.map(t=><article key={t.id} className="border-b border-hair py-4"><p>{t.done?'Completed · ':''}{t.title}</p><p className="text-label text-chalk-muted">Due {date(t.dueAt)}</p><Link className="underline text-label" href={t.contactId?'/crm/'+t.contactId:'/command'}>Open source task</Link></article>)}{!a.tasks.length&&<p className="mt-4 text-chalk-muted">No recorded tasks.</p>}</section><section><h2 className="font-display text-h3">Calendar commitments</h2>{a.appointments.map(e=><article key={e.id} className="border-b border-hair py-4"><p>{e.title}</p><p className="text-label text-chalk-muted">{date(e.startsAt)} – {date(e.endsAt)}</p><p className="text-label">{e.kind==='proposed block'?'Proposed block; not a confirmed client appointment':'Local calendar appointment'}</p><Link className="underline text-label" href="/calendar">Open calendar</Link></article>)}{!a.appointments.length&&<p className="mt-4 text-chalk-muted">No recorded calendar appointments.</p>}</section></div>
 <section className="mt-10"><h2 className="font-display text-h3">Transaction concerns</h2>{a.transactionConcerns.map(t=><article key={t.id} className="border-b border-hair py-5"><Link href={t.href} className="font-semibold underline">{t.address}</Link><p className="text-label text-chalk-muted mt-2">{t.status} · Closing {t.closingDate||'not confirmed'} · {t.tcAssigned?'TC assigned':'TC not assigned'} · {t.pendingApprovals} pending approvals</p>{t.deadlines.map((d,i)=><details key={i} className="mt-3"><summary>{d.label}: {d.date||'Cannot calculate'}</summary><p className="text-label text-chalk-muted mt-2">{d.reason}</p><p className="text-label mt-2">Source term: {d.sourceTerm||'Missing'}</p></details>)}<p className="text-label mt-3">Incomplete checklist: {t.missingItems.join(', ')||'No incomplete items'}</p></article>)}{!a.transactionConcerns.length&&<p className="mt-4 text-chalk-muted">No assigned transactions in your scope.</p>}</section>
 <section className="mt-10"><h2 className="font-display text-h3">Actual training progress</h2><p className="mt-4">{a.training.completedLessonCount} completed lesson/course records · {a.training.totalImportedLessons} imported lessons available.</p><p className="text-label text-chalk-muted mt-2">Completion is a learner-recorded action, not proof of learning or certification.</p>{a.training.assignments.map(t=><article key={t.id} className="border-b border-hair py-4"><Link className="underline" href={/^c\d+$/.test(t.courseId)?'/training/classroom/'+t.courseId:'/training/manage#'+t.courseId}>{t.title}</Link><p className="text-label">Due {t.due} · {t.complete?'Completed':'Not yet complete'}</p></article>)}{!a.training.assignments.length&&<p className="text-chalk-muted mt-3">No current training assignments.</p>}</section>
 <section className="mt-10"><h2 className="font-display text-h3">Recorded activity ledger</h2><p className="text-label text-chalk-muted mt-3">Most recent {Math.min(a.events.length,100)} of {a.events.length} events. The scoped export includes all events.</p>{a.events.slice(0,100).map(e=><article key={e.evidenceId} className="border-b border-hair py-3"><Link className="underline" href={e.href}>{e.contactName}</Link><p className="mt-1">{e.label}</p><p className="text-label text-chalk-muted">{date(e.at)} · {e.kind} · {e.direction}</p></article>)}{!a.events.length&&<p className="text-chalk-muted mt-4">No captured activity. External history coverage is unknown.</p>}</section><section className="mt-10"><h2 className="font-display text-h3">Assignment responsibility history</h2>{a.assignmentHistory.map((h,i)=><p key={i} className="py-3 border-b border-hair text-label"><Link className="underline" href={'/crm/'+h.contactId}>Contact assignment</Link> · {data.roster.find(r=>r.id===h.from)?.name||h.from} → {data.roster.find(r=>r.id===h.to)?.name||h.to} · {date(h.at)}</p>)}{!a.assignmentHistory.length&&<p className="text-chalk-muted mt-3">No reassignment event is recorded for the currently assigned leads. Original receipt is not proof of final-assignment responsibility.</p>}</section><section className="mt-10 border-t border-hair pt-6"><h2 className="font-display text-h3">Source coverage</h2>{a.sourceCoverage.map(s=><p key={s.source} className="mt-3 text-label text-chalk-muted"><strong>{s.source}: {s.records} records.</strong> {s.coverage}</p>)}<p className="mt-4 text-label text-chalk-muted">SMS delivery does not establish a read receipt. Call attempts are distinct from connected conversations. Historical responsibility remains in assignment events and is not attributed automatically to the current agent.</p></section></>}
 </div>
}
