'use client'
import {useState,useEffect} from 'react'
const workflows:Record<string,{fields:string[];channel:string;compose:(v:Record<string,string>)=>string}>={
Listing:{fields:['Property address','Verified features','Asking price','Showing instructions'],channel:'Instagram',compose:v=>`${v['Property address']}\n${v['Verified features']}\nOffered at ${v['Asking price']}. ${v['Showing instructions']}\nVerify current availability and all listing facts before use.`},
'Open house':{fields:['Property address','Event date and time','Verified features','Visitor instructions'],channel:'Print',compose:v=>`OPEN HOUSE\n${v['Property address']}\n${v['Event date and time']}\n${v['Verified features']}\n${v['Visitor instructions']}\nLocal plan: confirm access, prepare sign-in consent, and schedule approved follow-up.`},
Social:{fields:['Topic','Verified takeaway','Next step'],channel:'Instagram',compose:v=>`${v.Topic}\n\n${v['Verified takeaway']}\n\n${v['Next step']}`},
Buyer:{fields:['Buyer question','Helpful guidance','Consultation next step'],channel:'Email',compose:v=>`Subject: Your next step toward homeownership\n\nYou asked: ${v['Buyer question']}\n${v['Helpful guidance']}\n\n${v['Consultation next step']}\nYou are free to choose any lender.`},
Seller:{fields:['Property context','Preparation priorities','Consultation next step'],channel:'Email',compose:v=>`Subject: Preparing for your sale\n\n${v['Property context']}\nPriorities to review together:\n${v['Preparation priorities']}\n\n${v['Consultation next step']}\nA suggested price requires a current comparative market review.`},
'Past client':{fields:['Relationship context','Useful update','Invitation'],channel:'Email',compose:v=>`Subject: A quick real estate check-in\n\n${v['Relationship context']}\n${v['Useful update']}\n\n${v.Invitation}`},
Database:{fields:['Audience','Relevant topic','Useful resource','Next step'],channel:'Email',compose:v=>`Subject: ${v['Relevant topic']}\n\nFor ${v.Audience}:\n${v['Useful resource']}\n\n${v['Next step']}\nUse only an audience with the required communication permission.`},
Recruiting:{fields:['Career goal','Verified brokerage benefit','Confidential next step'],channel:'Email',compose:v=>`Subject: Let's talk about your next chapter\n\n${v['Career goal']}\n${v['Verified brokerage benefit']}\n\n${v['Confidential next step']}\nNo commission split or fee promise is represented.`},
Email:{fields:['Subject','Audience','Message','Call to action'],channel:'Email',compose:v=>`Subject: ${v.Subject}\n\n${v.Audience},\n\n${v.Message}\n\n${v['Call to action']}`},
'Video script':{fields:['Opening question','Three talking points','Closing invitation'],channel:'YouTube',compose:v=>`OPENING\n${v['Opening question']}\n\nEXPLANATION\n${v['Three talking points']}\n\nCLOSE\n${v['Closing invitation']}\n\nProduction notes: record original footage, add captions, and review all claims.`},
'Personal branding':{fields:['Professional focus','Verified experience','How you help','Contact invitation'],channel:'Print',compose:v=>`${v['Professional focus']}\n${v['Verified experience']}\n${v['How you help']}\n\n${v['Contact invitation']}`},
}
export function MarketingComposer({onDraft,attribution,brandRules}:{onDraft:(draft:any)=>void;attribution:string;brandRules:string}){const [workflow,setWorkflow]=useState('Listing');const [listing,setListing]=useState<any>(null);useEffect(()=>{const id=new URLSearchParams(location.search).get('listing');if(id)fetch('/api/platform/listings').then(r=>r.ok?r.json():[]).then(rows=>setListing(rows.find((r:any)=>r.id===id)))},[]);const config=workflows[workflow];const initial=(f:string)=>!listing?'':f==='Property address'?listing.address:f==='Asking price'?String(listing.price):f==='Verified features'?(listing.description??listing.features?.join(', ')??''):'';return <details open={listing?true:undefined} className="border border-hair p-5 my-6"><summary className="font-display text-xl cursor-pointer">Compose a campaign from verified inputs</summary><p className="text-sm text-chalk-muted my-4">Deterministic templates. Your facts become an editable draft; this does not call a model or certify legal compliance.</p><label className="block text-sm">Workflow<select className="border border-hair bg-ink w-full p-2 mt-2" value={workflow} onChange={e=>setWorkflow(e.target.value)}>{Object.keys(workflows).map(w=><option key={w}>{w}</option>)}</select></label><p className="text-sm text-chalk-muted whitespace-pre-wrap my-4">Brand guidance for this draft: {brandRules}</p><form key={workflow+(listing?.id??'')} className="space-y-4 mt-5" onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;onDraft({listingId:listing?.id,source:listing?'Synthetic local listing':'User supplied composition inputs',workflow,channel:config.channel,title:workflow+' draft',body:config.compose(values)+'\n\n'+attribution,status:'draft'})}}>{config.fields.map(f=><label key={f} className="block text-sm text-chalk-muted">{f}<textarea className="block w-full bg-ink border border-hair p-2 mt-2 text-chalk" required name={f} defaultValue={initial(f)} maxLength={1500}/></label>)}<button className="border border-hair px-4 py-2">Prepare editable draft</button></form></details>}
