'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
type License={state:'Alabama'|'Florida';number:string}
type Profile={phone:string;licenses:License[];markets:string[];specialties:string[];biography:string;socialLinks:{instagram:string;facebook:string;linkedin:string};websiteTemplate:string;websiteSlug:string;steps:{identityConfirmed:boolean;profileReviewed:boolean;licenseReviewed:boolean;marketsReviewed:boolean;websiteSelected:boolean};version:number}
const templates=[['signature','RCRE Signature'],['luxury','Luxury'],['rural-land','Rural and Land'],['investor','Investor'],['urban-modern','Urban Modern'],['suburban-family','Suburban Family'],['new-construction','New Construction'],['historic-heritage','Historic Heritage']]
const empty:Profile={phone:'',licenses:[],markets:[],specialties:[],biography:'',socialLinks:{instagram:'',facebook:'',linkedin:''},websiteTemplate:'signature',websiteSlug:'',steps:{identityConfirmed:false,profileReviewed:false,licenseReviewed:false,marketsReviewed:false,websiteSelected:false},version:0}
const input='w-full rounded border border-hair bg-ink-raised px-3 py-2 text-chalk'
export function OnboardingWorkspace({name}:{name:string}){
 const [profile,setProfile]=useState<Profile>(empty),[photo,setPhoto]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 async function load(){setError('');try{const r=await fetch('/api/onboarding',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setProfile({...empty,...d.profile,socialLinks:{...empty.socialLinks,...d.profile.socialLinks},steps:{...empty.steps,...d.profile.steps}});setPhoto(d.photoUploaded)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[])
 function patch<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>({...p,[key]:value}))}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/onboarding',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),d=await r.json();if(!r.ok)throw Error(d.error);setProfile({...profile,...d.profile});setNotice('Progress saved in this local environment. It is not connected to hosted brokerage storage.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{const f=new FormData();f.set('photo',file);const r=await fetch('/api/profile/photo',{method:'POST',body:f}),d=await r.json();if(!r.ok)throw Error(d.error);setPhoto(true);setNotice('Photo saved in this local environment.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const checked=Object.values(profile.steps).filter(Boolean).length,sections=[['identityConfirmed','Confirm your identity'],['profileReviewed','Review your contact profile'],['licenseReviewed','Add licensing details'],['marketsReviewed','Choose markets and specialties'],['websiteSelected','Choose your website style']] as const
 return <main className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><header className="border-b border-hair pb-6"><p className="eyebrow">First day setup</p><h1 className="font-display text-h2 mt-3">Build your RCRE profile</h1><p className="mt-3 max-w-3xl text-chalk-muted">Work through these steps at your pace. Your progress is saved locally for this review environment; profile publication and hosted persistence are not configured here.</p><p className="mt-4 text-sm">Signed in as <strong>{name}</strong> · {checked} of 5 steps reviewed{photo?' · Headshot uploaded':''}</p><progress aria-label={checked+' of 5 onboarding steps reviewed'} max="5" value={checked} className="mt-3 w-full"/></header>
 {error&&<div role="alert" className="my-5 rounded border border-red-500 p-4">{error}<button className="ml-3 underline" onClick={()=>void load()}>Reload</button></div>}{notice&&<p role="status" className="my-5 rounded border border-hair p-4">{notice}</p>}
 <form onSubmit={save} className="grid gap-8 py-8 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="space-y-8">
 <section className="border-b border-hair pb-7"><h2 className="font-display text-h3">Identity and contact</h2><p className="text-sm text-chalk-muted mt-2">The signed-in identity name is supplied by your account and cannot be changed here.</p><label className="block mt-4">Display name<input className={input+' mt-1'} readOnly value={name}/></label><label className="block mt-4">Professional phone<input className={input+' mt-1'} value={profile.phone} onChange={e=>patch('phone',e.target.value)} autoComplete="tel"/></label><label className="flex gap-3 items-center mt-4"><input type="checkbox" checked={profile.steps.identityConfirmed} onChange={e=>patch('steps',{...profile.steps,identityConfirmed:e.target.checked})}/> I confirm this is the account I intend to use for RCRE work.</label><label className="flex gap-3 items-center mt-3"><input type="checkbox" checked={profile.steps.profileReviewed} onChange={e=>patch('steps',{...profile.steps,profileReviewed:e.target.checked})}/> I reviewed my contact information.</label>
 <div className="mt-5"><label className="block font-medium">Professional headshot</label><input className="mt-2 block" type="file" accept="image/png,image/jpeg" onChange={e=>void upload(e.target.files?.[0])}/><p className="text-xs text-chalk-muted mt-1">{photo?'A profile image is saved.':'Optional. PNG/JPEG up to 2 MB; you can add this later.'}</p></div></section>
 <section className="border-b border-hair pb-7"><h2 className="font-display text-h3">Licensing and service areas</h2><p className="text-sm text-chalk-muted mt-2">Enter only current license details. These selections are saved as your profile input and do not certify a license or authorize public display.</p><div className="space-y-3 mt-4">{profile.licenses.map((l,i)=><div key={i} className="grid gap-2 sm:grid-cols-[9rem_1fr_auto]"><select aria-label={'License state '+(i+1)} className={input} value={l.state} onChange={e=>patch('licenses',profile.licenses.map((x,j)=>i===j?{...x,state:e.target.value as License['state']}:x))}><option>Alabama</option><option>Florida</option></select><input aria-label={'License number '+(i+1)} className={input} value={l.number} onChange={e=>patch('licenses',profile.licenses.map((x,j)=>i===j?{...x,number:e.target.value}:x))} placeholder="License number"/><button type="button" className="btn-ghost" onClick={()=>patch('licenses',profile.licenses.filter((_,j)=>i!==j))}>Remove</button></div>)}<button type="button" className="btn-ghost" onClick={()=>patch('licenses',[...profile.licenses,{state:'Alabama',number:''}])}>Add license</button></div><label className="block mt-5">Markets you serve<input className={input+' mt-1'} value={profile.markets.join(', ')} onChange={e=>patch('markets',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Separate markets with commas"/></label><label className="block mt-4">Specialties<input className={input+' mt-1'} value={profile.specialties.join(', ')} onChange={e=>patch('specialties',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Only specialties you are prepared to represent"/></label><label className="flex gap-3 items-center mt-4"><input type="checkbox" checked={profile.steps.licenseReviewed} onChange={e=>patch('steps',{...profile.steps,licenseReviewed:e.target.checked})}/> I reviewed the license information entered.</label><label className="flex gap-3 items-center mt-3"><input type="checkbox" checked={profile.steps.marketsReviewed} onChange={e=>patch('steps',{...profile.steps,marketsReviewed:e.target.checked})}/> I reviewed my markets and specialties.</label></section>
 <section className="border-b border-hair pb-7"><h2 className="font-display text-h3">Biography and social profiles</h2><label className="block mt-4">Biography<textarea className={input+' mt-1 min-h-32'} maxLength={5000} value={profile.biography} onChange={e=>patch('biography',e.target.value)}/></label>{(['instagram','facebook','linkedin'] as const).map(k=><label className="block mt-4 capitalize" key={k}>{k}<input type="url" className={input+' mt-1'} value={profile.socialLinks[k]} onChange={e=>patch('socialLinks',{...profile.socialLinks,[k]:e.target.value})} placeholder="https://"/></label>)}</section>
 <section><h2 className="font-display text-h3">Personal website</h2><label className="block mt-4">Starting design<select className={input+' mt-1'} value={profile.websiteTemplate} onChange={e=>{patch('websiteTemplate',e.target.value);patch('steps',{...profile.steps,websiteSelected:true})}}>{templates.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="block mt-4">Preferred URL slug<input className={input+' mt-1'} value={profile.websiteSlug} onChange={e=>patch('websiteSlug',e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} placeholder="Your requested name"/></label><p className="text-xs text-chalk-muted mt-2">Template choice and URL request are saved as preferences. Publishing and custom-domain activation require brokerage setup.</p><label className="flex gap-3 items-center mt-4"><input type="checkbox" checked={profile.steps.websiteSelected} onChange={e=>patch('steps',{...profile.steps,websiteSelected:e.target.checked})}/> I selected a starting template.</label></section></div>
 <aside className="lg:sticky lg:top-8 h-fit rounded border border-hair p-5"><h2 className="font-display text-h4">Next steps</h2><p className="text-sm text-chalk-muted mt-2">Optional profile details do not prevent access to your workspace.</p><ol className="mt-4 space-y-3 text-sm">{sections.map(([key,label])=><li key={key}>{profile.steps[key]?'✓':'○'} {label}</li>)}<li>{photo?'✓':'○'} Add a headshot</li></ol><button disabled={busy} className="btn-primary mt-6 w-full">{busy?'Saving…':'Save onboarding progress'}</button><Link className="btn-ghost block text-center mt-3" href="/today">Continue to RCRE Today</Link><p className="text-xs text-chalk-muted mt-4">Onboarding data remains local until production Google identity and hosted database services are connected.</p></aside></form></main>
}
