'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {LeadCampaign} from './LeadCampaign'
import {ProfilePhoto} from './ProfilePhoto'
import {InvitationManager} from './InvitationManager'
import type {PlatformActor} from '@/lib/platform/auth'
const input='w-full border border-hair rounded-control bg-ink px-3 py-2 text-chalk'
const button='border border-hair rounded-control px-4 py-2 hover:border-brass-fill text-sm'
type Field={key:string;label:string;type?:string;choices?:string[];default?:any;min?:number;max?:number}
const groups:Record<string,{title:string;effect:string;fields:Field[]}>={
personal:{title:'Personal preferences',effect:'Profile display, timezone, quiet hours and visual preferences apply to your workspace. Test quiet-hour delivery in Notifications.',fields:[{key:'name',label:'Display name'},{key:'email',label:'Contact email',type:'email'},{key:'phone',label:'Contact phone'},{key:'market',label:'Preferred market',choices:['Florida','Alabama']},{key:'timezone',label:'Timezone',choices:['America/New_York','America/Chicago','America/Denver','America/Los_Angeles'],default:'America/New_York'},{key:'workStart',label:'Work starts',type:'time',default:'09:00'},{key:'workEnd',label:'Work ends',type:'time',default:'17:00'},{key:'theme',label:'Theme',choices:['light','dark'],default:'light'},{key:'reducedMotion',label:'Reduce motion',type:'checkbox'},{key:'largeText',label:'Larger interface text',type:'checkbox'},{key:'quietStart',label:'Quiet hours start (0–23)',type:'number',default:22,min:0,max:23},{key:'quietEnd',label:'Quiet hours end (0–23)',type:'number',default:7,min:0,max:23},{key:'calendarReminders',label:'Local calendar reminders',type:'checkbox',default:true},{key:'reminderMinutes',label:'Calendar reminder lead time (minutes)',type:'number',default:15,min:0,max:1440},{key:'calendarView',label:'Default calendar view',choices:['week','day']},{key:'shareRecruiting',label:'Share recorded learning activity with recruiting',type:'checkbox',default:false},{key:'inAppNotifications',label:'In-app notifications',type:'checkbox',default:true}]},
account:{title:'Account and sessions',effect:'Revoke any active local session below. Passwords, identity-provider sign-in and external recovery are unavailable until a real provider is approved.',fields:[]},
brokerage:{title:'Brokerage and Preferred Lender',effect:'Public Preferred Lender contact details and the financing form recipient read this record. Changes are local drafts requiring review before production.',fields:[{key:'displayName',label:'Brokerage display name',default:'River City Real Estate Group'},{key:'legalName',label:'Legal name',default:'RCRE Group'},{key:'publicEmail',label:'Public email',type:'email'},{key:'publicPhone',label:'Public phone'},{key:'alOfficeAddress',label:'Verified Alabama office address',default:'1 Chase Corporate Dr # 400, Birmingham AL 35244'},{key:'flOfficeAddress',label:'Verified Florida office address (leave blank if unconfirmed)'},{key:'flPhone',label:'Florida public phone',default:'(904) 906-9038'},{key:'workStart',label:'Default working hours start',type:'time',default:'09:00'},{key:'workEnd',label:'Default working hours end',type:'time',default:'17:00'},{key:'documentOwners',label:'Designated document reviewers (empty uses scoped role policy)',type:'members'},{key:'contentOwners',label:'Designated content reviewers (empty uses scoped role policy)',type:'members'},{key:'lender.name',label:'Preferred Lender name',default:'Jeremy McDonald'},{key:'lender.phone',label:'Preferred Lender phone',default:'(904) 442-3213'},{key:'lender.email',label:'Preferred Lender email',type:'email',default:'jeremy@mcdonald-mtg.com'},{key:'lender.website',label:'Preferred Lender website',type:'url',default:'https://www.mcdonald-mtg.com'},{key:'lender.individualNmls',label:'Individual NMLS',default:'1195266'},{key:'lender.companyNmls',label:'Loan Factory NMLS',default:'320841'}]},
people:{title:'People and access',effect:'Role changes and deactivation affect the next authenticated request. You cannot modify your own role. Team and office boundaries stay server enforced.',fields:[]},
leads:{title:'Lead operations',effect:'Synthetic stage thresholds feed Today and Command. Preview before saving. Historical activity remains unchanged.',fields:[{key:'sourceOptions',label:'Local lead source choices (comma separated)',default:'Website, Referral, ISA, Education, Meta, YouTube, Manual local entry'},...['New Lead','Attempting Contact','Connected','Appointment','Active Buyer','Active Seller','Under Contract','Closed','Long-Term Nurture'].map(stage=>({key:'stageLabels.'+stage,label:stage+' display label',default:stage})),{key:'enabled',label:'Enable synthetic policy evaluation',type:'checkbox',default:true},{key:'responseMinutes',label:'Response guideline (minutes)',type:'number',default:60,min:1,max:10080},{key:'graceMinutes',label:'Grace window (minutes)',type:'number',default:15,min:0,max:1440},{key:'routing.al',label:'Alabama initial recipient',type:'member',default:'u-vito'},{key:'routing.fl',label:'Florida initial recipient',type:'member',default:'u-sarah'},{key:'taskEstimateMinutes',label:'Default task estimate (minutes)',type:'number',default:30,min:5,max:180},{key:'followUpDays',label:'Inactive follow-up interval (days)',type:'number',default:7,min:1,max:365},{key:'escalationMinutes',label:'Synthetic overdue-task escalation delay (minutes)',type:'number',default:1440,min:0,max:10080},{key:'alertRecipient',label:'Local alert recipient',type:'member'},{key:'quietStart',label:'Lead-alert quiet hours start',type:'number',default:22,min:0,max:23},{key:'quietEnd',label:'Lead-alert quiet hours end',type:'number',default:7,min:0,max:23},{key:'stageDays.New Lead',label:'New Lead stage (days)',type:'number',default:2,min:1,max:365},{key:'stageDays.Attempting Contact',label:'Attempting Contact (days)',type:'number',default:7,min:1,max:365},{key:'stageDays.Connected',label:'Connected (days)',type:'number',default:14,min:1,max:365},{key:'stageDays.Active Buyer',label:'Active Buyer (days)',type:'number',default:45,min:1,max:365}]},
transactions:{title:'Transactions and documents',effect:'Document and deadline rules are configured in the transaction workspace. Signature execution requires an authorized local signing engine; no electronic signature is fabricated.',fields:[]},
ai:{title:'AI preferences',effect:'Provider, model, connection test, sharing permission and request caps are managed in the actual assistant boundary. No default paid inference.',fields:[]},
integrations:{title:'Integration management',effect:'See verified connection state, pause and disconnect in Integration Center. Setup alone never marks a service connected.',fields:[]},
marketing:{title:'Marketing policy',effect:'Require review and attribution for content. Version edits invalidate approval; live publishing remains blocked.',fields:[{key:'requireApproval',label:'Require review before scheduling',type:'checkbox',default:true},{key:'defaultAttribution',label:'Default attribution',default:'River City Real Estate Group'},{key:'defaultChannel',label:'Default composition channel',choices:['Email','Instagram','Facebook','YouTube','Print']},{key:'brandRules',label:'Brand guidance',default:'Use RCRE branding and verified facts. Review required.'}]},
academy:{title:'Classroom and Community',effect:'Use curriculum management to order, publish, restrict courses and create assignments. Restrictions apply to protected file requests as well as the catalog.',fields:[]},
website:{title:'Website and search',effect:'Website studio controls indexing per published page. Private, preview and synthetic routes remain excluded. Sitemap reflects published canonical content.',fields:[]},
audit:{title:'Audit and data',effect:'The review window filters the audit table and export. Records are retained; deletion requires an approved retention policy. Local health shows actual worker and storage status.',fields:[{key:'reviewDays',label:'Audit review window (days)',type:'number',min:1,max:3650,default:90},{key:'retentionNote',label:'Retention policy awaiting approval',default:'Records retained. No automatic deletion authorized.'}]},
}
export function SettingsWorkspace({actor,group='personal'}:{actor:PlatformActor;group?:string}){
const [resetKey,setResetKey]=useState(0);const [record,setRecord]=useState<any>({value:{},version:0}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[sessions,setSessions]=useState<any[]>([]),[preview,setPreview]=useState<any[]>([]),[person,setPerson]=useState('u-vito'),[role,setRole]=useState('agent'),[disabled,setDisabled]=useState(false),[members,setMembers]=useState<any[]>([]),[officeId,setOffice]=useState('al'),[teamId,setTeam]=useState('al')
const baseConfig=groups[group]??groups.personal;const config={...baseConfig,fields:baseConfig.fields.filter(f=>group!=='leads'||actor.role==='broker_owner'||!f.key.startsWith('routing.')||f.key==='routing.'+actor.officeId)}
const request=async(path:string,body?:any)=>{const r=await fetch('/api/platform/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
const load=async()=>{try{setRecord(await request('settings/'+group));if(group==='account')setSessions(await request('sessions'));if(['people','leads','brokerage'].includes(group))setMembers(await request('people'))}catch(e){setError(e instanceof Error?e.message:'Could not load settings')}}
useEffect(()=>{setError('');setNotice('');void load()},[group]);
const value=(key:string)=>key.split('.').reduce((v,k)=>v?.[k],record.value)
const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');try{const form=new FormData(e.currentTarget);const result=structuredClone(record.value);for(const field of config.fields){const v=field.type==='members'?form.getAll(field.key).join(','):field.type==='checkbox'?form.has(field.key):field.type==='number'?Number(form.get(field.key)):String(form.get(field.key)??'');const parts=field.key.split('.');let target=result;parts.slice(0,-1).forEach(k=>target=target[k]??(target[k]={}));target[parts.at(-1)!]=v}if(result.timezone)new Intl.DateTimeFormat('en-US',{timeZone:result.timezone});const saved=await request('settings/'+group,{value:result,version:record.version});setRecord(saved);if(group==='personal'){localStorage.setItem('rcre-theme',result.theme);document.documentElement.dataset.theme=result.theme;document.documentElement.dataset.largeText=String(result.largeText);document.documentElement.dataset.reducedMotion=String(result.reducedMotion)}setNotice('Saved. The setting is active locally.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}}
const destinations:Record<string,[string,string]>={transactions:['/transactions','Open transaction policies and templates'],ai:['/assistant','Open provider configuration'],integrations:['/integrations','Open Integration Center'],academy:['/training/manage','Manage curriculum and assignments'],website:['/admin/website','Open website studio'],audit:['/admin/audit','Inspect audit trail']}
const visible=Object.keys(groups).filter(k=>actor.role==='broker_owner'||['personal','account','ai'].includes(k)||(k==='leads'&&['managing_broker','team_leader'].includes(actor.role))||(k==='marketing'&&actor.role==='marketing_admin')||(k==='academy'&&actor.role==='trainer'))
return <div className="p-5 sm:p-8 lg:p-10 max-w-6xl"><h1 className="font-display text-4xl">Settings</h1><nav aria-label="Settings groups" className="flex flex-wrap gap-2 py-6 border-b border-hair">{visible.map(k=><Link key={k} href={'/settings/'+k} className={button+(group===k?' bg-ink-elevated text-brass-ink':'')}>{groups[k].title}</Link>)}</nav><h2 className="font-display text-2xl mt-8">{config.title}</h2><p className="max-w-3xl text-chalk-muted my-4">{config.effect}</p>{error&&<p role="alert" className="text-red-600 my-4">{error}</p>}{notice&&<p role="status" className="text-brass-ink my-4">{notice}</p>}
{group==='personal'&&<ProfilePhoto/>}{config.fields.length>0&&<form id="settings-form" key={record.version+group+resetKey} onSubmit={save} className="max-w-3xl"><div className="grid sm:grid-cols-2 gap-5">{config.fields.map(f=><label key={f.key} className="block text-sm"><span className="block mb-2 text-chalk-muted">{f.label}</span>{['member','members'].includes(f.type??'')?<select name={f.key} multiple={f.type==='members'} className={input} defaultValue={f.type==='members'?String(value(f.key)??'').split(',').filter(Boolean):value(f.key)??f.default??''}>{f.type==='member'&&<option value="">Your account / select recipient</option>}{members.filter(m=>!m.disabled&&(!f.key.startsWith('routing.')||(m.officeId===f.key.split('.')[1]&&['agent','team_leader'].includes(m.role)))).map(m=><option key={m.id} value={m.id}>{m.name} · {m.role.replaceAll('_',' ')}</option>)}</select>:f.choices?<select name={f.key} className={input} defaultValue={value(f.key)??f.default??f.choices[0]}>{f.choices.map(o=><option key={o}>{o}</option>)}</select>:f.type==='checkbox'?<input name={f.key} type="checkbox" defaultChecked={value(f.key)??f.default??false}/>:<input className={input} name={f.key} type={f.type??'text'} min={f.min} max={f.max} defaultValue={value(f.key)??f.default??(f.key==='name'?actor.name:'')}/>}</label>)}</div><div className="flex gap-3 mt-6"><button className={button}>Save settings</button><button type="button" className={button} onClick={()=>{setResetKey(k=>k+1);void load();setNotice('Unsaved changes discarded.')}}>Cancel changes</button></div></form>}
{destinations[group]&&<Link className={button+' inline-block mt-5'} href={destinations[group][0]}>{destinations[group][1]}</Link>}
{group==='leads'&&(actor.role==='broker_owner'||actor.officeId==='al')&&<LeadCampaign/>}{group==='leads'&&<section className="my-6"><button className={button} onClick={async()=>{try{const form=new FormData(document.getElementById('settings-form') as HTMLFormElement);const draft=structuredClone(record.value);for(const f of config.fields){const parts=f.key.split('.');let target=draft;for(const k of parts.slice(0,-1))target=target[k]??(target[k]={});target[parts.at(-1)!]=f.type==='checkbox'?form.has(f.key):f.type==='number'?Number(form.get(f.key)):String(form.get(f.key)??'')}setPreview(await request('policy-preview',{value:draft}))}catch(e){setError(String(e))}}}>Preview unsaved policy on synthetic records</button><button className={button+' ml-3'} onClick={async()=>{try{const result=await request('lead-alerts',{});setNotice(`${result.created} local alerts recorded; ${result.suppressed} suppressed by quiet hours.`)}catch(e){setError(String(e))}}}>Generate local alerts from saved policy</button>{preview.map(p=><p className="py-2 text-sm" key={p.contact.id}>{p.contact.firstName}: {p.reasons.join(' · ')}</p>)}</section>}
{group==='account'&&sessions.map(s=><div className="py-4 border-b border-hair flex justify-between gap-3" key={s.id}><div><p>Local session created {new Date(s.createdAt).toLocaleString()}</p><p className="text-sm text-chalk-muted">{s.revoked?'Revoked':'Expires '+new Date(s.expiresAt).toLocaleString()}</p></div><button disabled={s.revoked} className={button} onClick={async()=>{try{await request('sessions',{id:s.id});void load()}catch(e){setError(String(e))}}}>Revoke session</button></div>)}
{group==='people'&&<form className="space-y-4 max-w-xl" onSubmit={async e=>{e.preventDefault();try{await request('members',{id:person,role,disabled,officeId,teamId});setNotice('Membership updated for the next request.')}catch(e){setError(e instanceof Error?e.message:'Update failed')}}}><label className="block">Member<select className={input} value={person} onChange={e=>{setPerson(e.target.value);const m=members.find(m=>m.id===e.target.value);if(m){setRole(m.role);setDisabled(m.disabled);setOffice(m.officeId);setTeam(m.teamId)}}}>{members.filter(m=>m.id!==actor.id).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="block">Role<select className={input} value={role} onChange={e=>setRole(e.target.value)}>{['agent','team_leader','managing_broker','transaction_coordinator','marketing_admin','trainer'].map(r=><option key={r}>{r}</option>)}</select></label><label className="block">Office<select className={input} value={officeId} onChange={e=>setOffice(e.target.value)}><option value="al">Alabama</option><option value="fl">Florida</option><option value="all">Brokerage-wide eligible role</option></select></label><label className="block">Team<select className={input} value={teamId} onChange={e=>setTeam(e.target.value)}><option value="al">Alabama</option><option value="fl">Florida</option><option value="all">Brokerage-wide eligible role</option></select></label><label><input type="checkbox" checked={disabled} onChange={e=>setDisabled(e.target.checked)}/> Deactivate member</label><button className={button+' block'}>Save membership</button></form>}
{group==='people'&&<InvitationManager/>}{group==='audit'&&<div className="mt-5 text-sm"><p>Run from the canonical application directory:</p><code className="block my-2">npm run local:backup</code><code className="block my-2">npm run local:reset -- --confirm-local-reset</code><p>Stop the local app before reset or restore. Backups are stored inside RCRE/runtime/backups.</p></div>}
</div>}
