import {randomUUID} from 'node:crypto'
import {z} from 'zod'
import {requireActor,assertCapability,AccessError} from '@/lib/platform/auth'
import {canReadMarketing,canEditMarketing,audit} from '@/lib/platform/service'
import {readRecords,getRecord,putRecord,deleteRecord,transaction} from '@/lib/platform/store'
export const dynamic='force-dynamic'
export async function GET(){try{const a=await requireActor();assertCapability(a,'marketing');return Response.json(readRecords<any>('marketing_batches').filter(b=>canEditMarketing(a,b)).map(b=>({...b,contents:b.contentIds.map((id:string)=>getRecord<any>('marketing',id)).filter((r:any)=>r&&canReadMarketing(a,r)).map((r:any)=>({id:r.id,title:r.title,status:r.status,version:r.version}))})))}catch(e){return fail(e)}}
export async function POST(req:Request){try{const a=await requireActor();assertCapability(a,'marketing');const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==new URL(req.url).host)throw new AccessError('Origin mismatch');const body=await req.json();return Response.json(transaction(()=>{if(body.action==='pause'||body.action==='cancel'){const batch=getRecord<any>('marketing_batches',String(body.id));if(!batch||!canEditMarketing(a,batch))throw new AccessError('Batch not found',404);for(const id of batch.contentIds){const old=getRecord<any>('marketing',id);if(!old||!canEditMarketing(a,old))throw new AccessError();putRecord('marketing_history',{...old,id:randomUUID(),contentId:id,recordedAt:new Date().toISOString()});putRecord('marketing',{...old,status:body.action==='pause'?'paused':'canceled',version:old.version+1});deleteRecord('marketing_outbox',id)}audit(a,'marketing.batch-'+body.action,batch.id);return {updated:batch.contentIds.length}}const b=z.object({title:z.string().trim().min(1).max(200),ids:z.array(z.string()).min(1).max(30)}).parse(body);const copies=[...new Set(b.ids)].map(id=>{const old=getRecord<any>('marketing',id);if(!old||!canReadMarketing(a,old))throw new AccessError('Content not available',404);const r={...old,id:randomUUID(),ownerId:a.id,officeId:a.officeId,title:old.title+' — batch draft',version:1,status:'draft',approvedBy:null,approvedVersion:null,scheduleAt:undefined,listingId:undefined,sourceContentId:old.id};putRecord('marketing',r);return r.id});const batch={id:randomUUID(),organizationId:a.organizationId,ownerId:a.id,officeId:a.officeId,title:b.title,contentIds:copies,createdAt:new Date().toISOString()};putRecord('marketing_batches',batch);audit(a,'marketing.batch-created',batch.id);return batch}))}catch(e){return fail(e)}}
function fail(e:unknown){return Response.json({error:e instanceof Error?e.message:'Batch request failed'},{status:e instanceof AccessError?e.status:e instanceof z.ZodError?400:500})}
