import 'server-only'
import {getRecord,putRecord} from '@/lib/platform/store'
import type {ProviderAdapter,ProviderCapabilities,ProviderDescriptor,ProviderConnection,PropertySearchFilters,PropertyListing,PropertyImage,PropertyOpenHouse,ProviderCompliance,PropertyStatus} from './types'
const noCapabilities:ProviderCapabilities={activeListings:false,comingSoon:false,pending:false,closed:false,openHouses:false,history:false,members:false,offices:false,photos:false,virtualTours:false,documents:false,geographicFields:false,waterfront:false,newConstruction:false,land:false,farm:false,rental:false,manufacturedHomes:false,incrementalUpdates:false,mapBounds:false}
const catalog=[
{id:'realmls',name:'realMLS / Flexmls',systems:['Flexmls'],states:['FL' as const],accessPaths:['Spark API','RESO Web API'],credentialEnv:['REALMLS_API_KEY','REALMLS_CLIENT_ID','REALMLS_CLIENT_SECRET']},
{id:'stellar',name:'Stellar MLS',systems:['Bridge API','MLS Grid'],states:['FL' as const],accessPaths:['Bridge API','MLS Grid'],credentialEnv:['STELLAR_MLS_API_KEY','STELLAR_MLS_CLIENT_ID','STELLAR_MLS_CLIENT_SECRET']},
{id:'miami',name:'MIAMI REALTORS',systems:['TRESTLE','Bridge'],states:['FL' as const],accessPaths:['TRESTLE','Bridge API'],credentialEnv:['MIAMI_MLS_API_KEY','MIAMI_MLS_CLIENT_ID','MIAMI_MLS_CLIENT_SECRET']},
{id:'greater-alabama',name:'Greater Alabama MLS',systems:['Paragon','OpenMLS','RESO'],states:['AL' as const],accessPaths:['Approved RESO Web API','Approved provider feed'],credentialEnv:['GALMLS_API_KEY','GALMLS_CLIENT_ID','GALMLS_CLIENT_SECRET']},
]
function hasCredentials(names:string[]){return names.some(name=>Boolean(process.env[name]?.trim()))}
export function providerCatalog(organizationId='rcre-local'):ProviderDescriptor[]{return catalog.map(provider=>{const saved=getRecord<any>('mls_provider_state',organizationId+':'+provider.id),credentialConfigured=hasCredentials(provider.credentialEnv),agreementApproved=saved?.agreementApproved===true,connected=saved?.lastConnectionOk===true&&credentialConfigured&&agreementApproved;const compliance:ProviderCompliance={status:agreementApproved?'approved':'pending',displayName:provider.name,photoMode:'not-approved',permittedStatuses:[] as PropertyStatus[],soldDisplayAllowed:null,indexing:'pending',...(saved?.compliance??{}),...(saved?.approvedAt?{approvedAt:saved.approvedAt}:{})};return{id:provider.id,name:provider.name,systems:provider.systems,states:provider.states,status:saved?.status==='disabled'?'disabled':connected?'connected':!credentialConfigured?'waiting_for_credentials':agreementApproved?'ready_for_connection':'waiting_for_agreement',accessPaths:provider.accessPaths,credentialConfigured,agreementApproved,mode:saved?.mode??'disabled',capabilities:{...noCapabilities,...saved?.capabilities},compliance,lastSuccessfulSync:saved?.lastSuccessfulSync,lastAttemptedSync:saved?.lastAttemptedSync,listingCount:saved?.listingCount,dataAgeMinutes:saved?.dataAgeMinutes,error:saved?.error}})}
export function providerById(id:string){return providerCatalog().find(p=>p.id===id)}
export function allCapabilitiesKnownFalse(){return{...noCapabilities}}
export class UnconfiguredProviderAdapter implements ProviderAdapter{constructor(readonly providerId:string,private readonly providerName:string){}async testConnection():Promise<ProviderConnection>{return{ok:false,providerId:this.providerId,checkedAt:new Date().toISOString(),message:this.providerName+' is waiting for its approved API adapter and access configuration.'}}async discoverCapabilities(){return{...noCapabilities}}async discoverMetadata(){return{providerId:this.providerId,discovery:'blocked until provider credentials, approved scope, and API metadata are available'}}async search(_filters:PropertySearchFilters){return{items:[] as PropertyListing[]}}async getListing(_id:string){return null}async getPhotos(_id:string){return[] as PropertyImage[]}async getOpenHouses(_id:string){return[] as PropertyOpenHouse[]}}
export function providerAdapters():ProviderAdapter[]{return catalog.map(p=>new UnconfiguredProviderAdapter(p.id,p.name))}
export function adapterFor(id:string){const provider=catalog.find(p=>p.id===id);return provider?new UnconfiguredProviderAdapter(provider.id,provider.name):null}
export function saveProviderCompliance(organizationId:string,providerId:string,compliance:Omit<ProviderCompliance,'status'|'displayName'|'approvedAt'>,approvedBy:string){const provider=catalog.find(p=>p.id===providerId);if(!provider)throw new Error('Provider not found');const key=organizationId+':'+providerId,old=getRecord<any>('mls_provider_state',key),now=new Date().toISOString(),state={...(old??{}),id:key,organizationId,providerId,agreementApproved:true,approvedBy,approvedAt:now,status:'ready_for_connection',mode:old?.mode??'disabled',compliance:{...compliance,status:'approved',displayName:provider.name,approvedAt:now},lastConnectionOk:false,error:undefined};putRecord('mls_provider_state',state);return state}
export function saveProviderConnection(organizationId:string,providerId:string,ok:boolean,message:string){const key=organizationId+':'+providerId,old=getRecord<any>('mls_provider_state',key),state={...(old??{id:key,organizationId,providerId}),lastAttemptedSync:new Date().toISOString(),lastConnectionOk:ok,status:ok?'connected':old?.status??'degraded',error:ok?undefined:message};putRecord('mls_provider_state',state);return state}
