import 'server-only'
import type {FieldMapping,ProviderAdapter,ProviderCapabilities,ProviderConnection,PropertyImage,PropertyListing,PropertyOpenHouse,PropertySearchFilters} from './types'
import {mapProviderRecord,mapResoListing} from './mapping'

export interface ResoWebApiAdapterConfig{
 providerId:string
 providerName:string
 serviceRoot:string
 listingsResource:string
 getAccessToken:()=>Promise<string>
 mappings?:FieldMapping[]
 idField?:string
 mediaResource?:string
 openHouseResource?:string
 mediaForeignKeyField?:string
 openHouseForeignKeyField?:string
 memberResource?:string
 officeResource?:string
 capabilityOverrides?:Partial<ProviderCapabilities>
 fetcher?:typeof fetch
 timeoutMs?:number
}
type ResoResponse={value?:Record<string,unknown>[];'@odata.count'?:number;'@odata.nextLink'?:string;['@odata.context']?:string}
const safeNumber=(v:unknown)=>Number.isFinite(Number(v))?Number(v):undefined
const esc=(v:string)=>v.replace(/'/g,"''")
const resoFields=['ListingKey','ListingKeyNumeric','ListingId','PropertyType','PropertySubType','StandardStatus','ListPrice','OriginalListPrice','ClosePrice','BedroomsTotal','BathroomsFull','BathroomsHalf','BathroomsTotalInteger','BathroomsTotalDecimal','LivingArea','LotSizeArea','LotSizeAcres','YearBuilt','Stories','GarageSpaces','ParkingTotal','StreetNumber','StreetName','UnitNumber','City','CountyOrParish','StateOrProvince','PostalCode','SubdivisionName','Latitude','Longitude','PublicRemarks','Directions','SchoolDistrict','ElementarySchool','MiddleOrJuniorSchool','HighSchool','WaterfrontYN','PoolPrivateYN','NewConstructionYN','AssociationYN','AssociationFee','TaxAnnualAmount','ParcelNumber','ListingContractDate','ModificationTimestamp','PendingTimestamp','CloseDate','DaysOnMarket','CumulativeDaysOnMarket','VirtualTourURLUnbranded','ListOfficeName','ListAgentFullName']
export class ResoWebApiAdapter implements ProviderAdapter{
 readonly providerId:string
 private readonly fetcher:typeof fetch
 private readonly root:string
 private metadataFields=new Set<string>()
 private statusValues=new Set<string>()
 private capabilityState:ProviderCapabilities={activeListings:false,comingSoon:false,pending:false,closed:false,openHouses:false,history:false,members:false,offices:false,photos:false,virtualTours:false,documents:false,geographicFields:false,waterfront:false,newConstruction:false,land:false,farm:false,rental:false,manufacturedHomes:false,incrementalUpdates:false,mapBounds:false}
 constructor(private readonly config:ResoWebApiAdapterConfig){this.providerId=config.providerId;this.fetcher=config.fetcher??fetch;const parsed=new URL(config.serviceRoot);if(parsed.protocol!=='https:'&&process.env.NODE_ENV==='production')throw new Error('MLS API root must use HTTPS');this.root=parsed.toString().replace(/\/$/,'')}
 private async headers(){const token=await this.config.getAccessToken();if(!token)throw new Error('Provider access token is unavailable');return {Authorization:'Bearer '+token,Accept:'application/json'}}
 private url(resource:string,params:Record<string,string|number|boolean|undefined>={}){const url=new URL(resource.replace(/^\//,''),this.root+'/');for(const [key,value] of Object.entries(params))if(value!==undefined)url.searchParams.set(key,String(value));return url}
 private async read(url:URL):Promise<Response>{const headers=await this.headers();return this.fetcher(url,{method:'GET',headers,cache:'no-store',signal:AbortSignal.timeout(this.config.timeoutMs??10000)})}
 async testConnection():Promise<ProviderConnection>{const checkedAt=new Date().toISOString();try{const response=await this.read(this.url('$metadata'));if(!response.ok)return{ok:false,providerId:this.providerId,checkedAt,message:'The provider metadata endpoint returned HTTP '+response.status+'.'};const xml=await response.text();this.readMetadata(xml);return{ok:true,providerId:this.providerId,checkedAt,message:'Provider metadata endpoint responded. Listing sample and compliance checks are still required.'}}catch{return{ok:false,providerId:this.providerId,checkedAt,message:'The provider metadata endpoint could not be reached with the configured credentials.'}}}
 async discoverMetadata(){const response=await this.read(this.url('$metadata'));if(!response.ok)throw new Error('Provider metadata discovery failed with HTTP '+response.status+'.');const xml=await response.text();this.readMetadata(xml);return{providerId:this.providerId,serviceRoot:this.root,availableFields:[...this.metadataFields].sort(),standardStatuses:[...this.statusValues].sort(),discoveredAt:new Date().toISOString()}}
 private readMetadata(xml:string){this.metadataFields=new Set([...xml.matchAll(/<Property\s+[^>]*Name=["']([^"']+)["']/g)].map(match=>match[1]!));this.statusValues=new Set();const enumBlock=xml.match(/<EnumType\s+[^>]*Name=["']StandardStatus["'][^>]*>([\s\S]*?)<\/EnumType>/)?.[1]??'';for(const match of enumBlock.matchAll(/<Member\s+[^>]*Name=["']([^"']+)["']/g))this.statusValues.add(match[1]!);this.capabilityState=this.deriveCapabilities()}
 private deriveCapabilities():ProviderCapabilities{const has=(field:string)=>this.metadataFields.has(field),hasStatus=(...values:string[])=>values.some(value=>this.statusValues.has(value));return{activeListings:hasStatus('Active'),comingSoon:hasStatus('ComingSoon','Coming Soon'),pending:hasStatus('Pending'),closed:hasStatus('Closed'),openHouses:Boolean(this.config.openHouseResource),history:has('ModificationTimestamp'),members:Boolean(this.config.memberResource),offices:Boolean(this.config.officeResource),photos:Boolean(this.config.mediaResource),virtualTours:has('VirtualTourURLUnbranded')||has('VirtualTourURLBranded'),documents:false,geographicFields:has('Latitude')&&has('Longitude'),waterfront:has('WaterfrontYN'),newConstruction:has('NewConstructionYN'),land:false,farm:false,rental:false,manufacturedHomes:false,incrementalUpdates:has('ModificationTimestamp'),mapBounds:has('Latitude')&&has('Longitude'),...this.config.capabilityOverrides}}
 async discoverCapabilities(){if(!this.metadataFields.size)await this.discoverMetadata();return {...this.capabilityState}}
 private buildFilter(f:PropertySearchFilters){const terms:string[]=[];const eqString=(field:string,value:string)=>terms.push(field+" eq '"+esc(value)+"'");if(f.state)eqString('StateOrProvince',f.state);if(f.city)eqString('City',f.city);if(f.county)eqString('CountyOrParish',f.county);if(f.postalCode)eqString('PostalCode',f.postalCode);if(f.subdivision)terms.push("contains(SubdivisionName,'"+esc(f.subdivision)+"')");if(f.mlsListingId)eqString('ListingId',f.mlsListingId);if(f.minPrice!==undefined)terms.push('ListPrice ge '+f.minPrice);if(f.maxPrice!==undefined)terms.push('ListPrice le '+f.maxPrice);if(f.minBeds!==undefined)terms.push('BedroomsTotal ge '+f.minBeds);if(f.minBaths!==undefined)terms.push('BathroomsTotalInteger ge '+f.minBaths);if(f.propertyType)eqString('PropertyType',f.propertyType);if(f.propertySubType)eqString('PropertySubType',f.propertySubType);if(f.minLivingArea!==undefined)terms.push('LivingArea ge '+f.minLivingArea);if(f.maxLivingArea!==undefined)terms.push('LivingArea le '+f.maxLivingArea);if(f.minLotArea!==undefined)terms.push('LotSizeArea ge '+f.minLotArea);if(f.minLotAcres!==undefined)terms.push('LotSizeAcres ge '+f.minLotAcres);if(f.minYearBuilt!==undefined)terms.push('YearBuilt ge '+f.minYearBuilt);if(f.maxYearBuilt!==undefined)terms.push('YearBuilt le '+f.maxYearBuilt);if(f.minGarageSpaces!==undefined)terms.push('GarageSpaces ge '+f.minGarageSpaces);if(f.pool!==undefined)terms.push('PoolPrivateYN eq '+f.pool);if(f.waterfront!==undefined)terms.push('WaterfrontYN eq '+f.waterfront);if(f.newConstruction!==undefined)terms.push('NewConstructionYN eq '+f.newConstruction);if(f.status)eqString('StandardStatus',f.status);if(f.maxDaysOnMarket!==undefined)terms.push('DaysOnMarket le '+f.maxDaysOnMarket);if(f.priceReduced)terms.push('OriginalListPrice gt ListPrice');if(f.bounds)terms.push('Latitude ge '+f.bounds.south+' and Latitude le '+f.bounds.north+' and Longitude ge '+f.bounds.west+' and Longitude le '+f.bounds.east);if(f.query){const q=esc(f.query);terms.push("(contains(City,'"+q+"') or contains(CountyOrParish,'"+q+"') or contains(PostalCode,'"+q+"') or contains(StreetName,'"+q+"') or contains(ListingId,'"+q+"'))")}return terms.join(' and ')}
 private cursorUrl(cursor:string|undefined,base:URL){if(!cursor?.startsWith('url:'))return base;const next=new URL(cursor.slice(4)),root=new URL(this.root+'/');if(next.origin!==root.origin||!next.pathname.startsWith(root.pathname))throw new Error('Provider pagination returned a URL outside its approved service root.');return next}
 async search(filters:PropertySearchFilters,cursor?:string){const pageSize=Math.max(1,Math.min(100,filters.pageSize??24)),page=Math.max(1,filters.page??1),skip=cursor?safeNumber(cursor):(page-1)*pageSize;const sortMap={newest:'ListingContractDate desc',updated:'ModificationTimestamp desc','price-asc':'ListPrice asc','price-desc':'ListPrice desc',beds:'BedroomsTotal desc',baths:'BathroomsTotalInteger desc','living-area':'LivingArea desc','days-on-market':'DaysOnMarket asc'} as const;const order=sortMap[filters.sort??'newest'];const url=this.url(this.config.listingsResource,{'$filter':this.buildFilter(filters)||undefined,'$top':pageSize,'$skip':skip,'$count':true,'$orderby':order});const response=await this.read(this.cursorUrl(cursor,url));if(!response.ok)throw new Error('Provider listing search failed with HTTP '+response.status+'.');const body=await response.json() as ResoResponse;const mappings=this.config.mappings??[];const items=(body.value??[]).map((raw,index)=>{const key=String(raw[this.config.idField??'ListingKey']??raw.ListingId??'unknown-'+index);const id=this.providerId+':'+key;const mapped=mappings.length?mapProviderRecord(raw,mappings,{id,providerId:this.providerId,providerName:this.config.providerName,mlsListingId:String(raw.ListingId??key)}):mapResoListing(raw,{id,providerId:this.providerId,providerName:this.config.providerName,mlsListingId:String(raw.ListingId??key)});return {...mapped,mlsSystem:this.config.providerName,providerExtensions:{...raw},fixture:false}});const nextLink=body['@odata.nextLink'];let nextCursor:string|undefined;if(nextLink){const next=new URL(nextLink,this.root+'/'),root=new URL(this.root+'/');if(next.origin!==root.origin||!next.pathname.startsWith(root.pathname))throw new Error('Provider pagination returned a URL outside its approved service root.');nextCursor='url:'+next.toString()}return{items,nextCursor,total:body['@odata.count']}}
 async getListing(id:string){const prefix=this.providerId+':';const key=id.startsWith(prefix)?id.slice(prefix.length):id;const response=await this.read(this.url(this.config.listingsResource,{'$filter':(this.config.idField??'ListingKey')+" eq '"+esc(key)+"'",'$top':1}));if(!response.ok)throw new Error('Provider listing detail failed with HTTP '+response.status+'.');const body=await response.json() as ResoResponse;const raw=body.value?.[0];if(!raw)return null;return mapResoListing(raw,{id:this.providerId+':'+key,providerId:this.providerId,providerName:this.config.providerName,mlsListingId:String(raw.ListingId??key)})}
 async getPhotos(id:string):Promise<PropertyImage[]>{if(!this.config.mediaResource||!this.config.mediaForeignKeyField)return[];const key=id.split(':').slice(1).join(':');const response=await this.read(this.url(this.config.mediaResource,{'$filter':this.config.mediaForeignKeyField+" eq '"+esc(key)+"'",'$orderby':'Order asc','$top':50}));if(!response.ok)throw new Error('Provider photo metadata failed with HTTP '+response.status+'.');const body=await response.json() as ResoResponse;return(body.value??[]).map((item,i)=>({id:String(item.MediaKey??item.id??i),url:String(item.MediaURL??item.MediaUrl??''),order:safeNumber(item.Order)??i,caption:typeof item.ShortDescription==='string'?item.ShortDescription:undefined,mediaType:typeof item.MediaType==='string'?item.MediaType:undefined,sourceUpdatedAt:typeof item.ModificationTimestamp==='string'?item.ModificationTimestamp:undefined})).filter(photo=>/^https:\/\//.test(photo.url))}
 async getOpenHouses(id:string):Promise<PropertyOpenHouse[]>{if(!this.config.openHouseResource||!this.config.openHouseForeignKeyField)return[];const key=id.split(':').slice(1).join(':');const response=await this.read(this.url(this.config.openHouseResource,{'$filter':this.config.openHouseForeignKeyField+" eq '"+esc(key)+"'",'$orderby':'OpenHouseDate desc','$top':50}));if(!response.ok)throw new Error('Provider open house query failed with HTTP '+response.status+'.');const body=await response.json() as ResoResponse;return(body.value??[]).map((item,i)=>({id:String(item.OpenHouseKey??i),startAt:String(item.OpenHouseDate??''),...(item.OpenHouseEndTime?{endAt:String(item.OpenHouseEndTime)}:{}),timezone:typeof item.TimeZone==='string'?item.TimeZone:undefined,remarks:typeof item.OpenHouseRemarks==='string'?item.OpenHouseRemarks:undefined})).filter(item=>Boolean(item.startAt))}
 async getMembers(){if(!this.config.memberResource)return[];const response=await this.read(this.url(this.config.memberResource,{'$top':100}));if(!response.ok)throw new Error('Provider member lookup failed with HTTP '+response.status+'.');return((await response.json() as ResoResponse).value??[])}
 async getOffices(){if(!this.config.officeResource)return[];const response=await this.read(this.url(this.config.officeResource,{'$top':100}));if(!response.ok)throw new Error('Provider office lookup failed with HTTP '+response.status+'.');return((await response.json() as ResoResponse).value??[])}
 async getMarketStatus(){return{providerId:this.providerId,metadataFields:this.metadataFields.size,checkedAt:new Date().toISOString()}}
 async syncSince(timestamp:string,cursor?:string){const url=this.url(this.config.listingsResource,{'$filter':"ModificationTimestamp ge datetime'"+esc(timestamp)+"'",'$top':100,'$skip':cursor?safeNumber(cursor):0,'$orderby':'ModificationTimestamp asc'});const response=await this.read(this.cursorUrl(cursor,url));if(!response.ok)throw new Error('Provider incremental query failed with HTTP '+response.status+'.');const body=await response.json() as ResoResponse;const items=(body.value??[]).map((raw,index)=>{const key=String(raw[this.config.idField??'ListingKey']??raw.ListingId??'unknown-'+index);return mapResoListing(raw,{id:this.providerId+':'+key,providerId:this.providerId,providerName:this.config.providerName,mlsListingId:String(raw.ListingId??key)})});const nextLink=body['@odata.nextLink'];let nextCursor:string|undefined;if(nextLink){const next=new URL(nextLink,this.root+'/'),root=new URL(this.root+'/');if(next.origin!==root.origin||!next.pathname.startsWith(root.pathname))throw new Error('Provider pagination returned a URL outside its approved service root.');nextCursor='url:'+next.toString()}return{items,deletedIds:[],nextCursor,checkpoint:items.at(-1)?.modificationTimestamp}}
}
