import {requireActor,AccessError} from '@/lib/platform/auth'
import {getRecord,putRecord,deleteRecord} from '@/lib/platform/store'
import {audit} from '@/lib/platform/service'
export const dynamic='force-dynamic'
export async function GET(){try{const a=await requireActor(),r=getRecord<any>('profile_photos',a.organizationId+':'+a.id);if(!r)throw new AccessError('No photo',404);return new Response(new Uint8Array(Buffer.from(r.bytes,'base64')),{headers:{'Content-Type':r.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}catch(e){return fail(e)}}
export async function POST(req:Request){try{const a=await requireActor();origin(req);if(Number(req.headers.get('content-length'))>2200000)throw new AccessError('Photo must be under 2 MB',413);const f=(await req.formData()).get('photo');if(!(f instanceof File)||f.size>2*1024*1024)throw new AccessError('Choose a PNG or JPEG under 2 MB',400);const bytes=Buffer.from(await f.arrayBuffer());const png=f.type==='image/png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpeg=f.type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!png&&!jpeg)throw new AccessError('Invalid PNG or JPEG file',400);putRecord('profile_photos',{id:a.organizationId+':'+a.id,mime:f.type,bytes:bytes.toString('base64'),updatedAt:Date.now()});audit(a,'profile.photo-saved',a.id);return Response.json({saved:true})}catch(e){return fail(e)}}
export async function DELETE(req:Request){try{origin(req);const a=await requireActor();deleteRecord('profile_photos',a.organizationId+':'+a.id);audit(a,'profile.photo-removed',a.id);return Response.json({removed:true})}catch(e){return fail(e)}}
function origin(req:Request){const o=req.headers.get('origin');if(o&&new URL(o).host!==new URL(req.url).host)throw new AccessError('Origin mismatch')}
function fail(e:unknown){return Response.json({error:e instanceof Error?e.message:'Photo request failed'},{status:e instanceof AccessError?e.status:500})}
