import {describe,it,expect} from 'vitest'
import {PERSONAS} from '../../src/lib/platform/auth'
import {saveAsset,assetBytes,listAssets,localDispatch} from '../../src/lib/platform/library'
import {dayPlan,acceptDayBlock,workInstant} from '../../src/lib/platform/day-plan'
import {createTask,createAppointment,saveSetting,getSetting} from '../../src/lib/platform/service'
import {putRecord,getRecord} from '../../src/lib/platform/store'
const agent=PERSONAS[0],other=PERSONAS[1],owner=PERSONAS.find(a=>a.role==='broker_owner')!
describe('Private library and day planning',()=>{
it('preserves exact bytes and version ancestry, rejects disguised uploads and cross-user access',()=>{const bytes=Buffer.from('%PDF-1.7\nSynthetic fixture');const first=saveAsset(agent,'synthetic.pdf','application/pdf',bytes);const next=saveAsset(agent,'revised.pdf','application/pdf',Buffer.from('%PDF-1.7\nRevised'),first.id);expect(next.previousId).toBe(first.id);expect(next.version).toBe(2);expect(assetBytes(agent,first.id).bytes.equals(bytes)).toBe(true);expect(()=>assetBytes(other,first.id)).toThrow();expect(listAssets({...owner,organizationId:'unrelated'})).toHaveLength(0);expect(()=>saveAsset(agent,'fake.pdf','application/pdf',Buffer.from('<script>bad</script>'))).toThrow()})
it('processes only exact approved due versions and is idempotent',()=>{putRecord('marketing',{id:'local-due',ownerId:owner.id,organizationId:owner.organizationId,status:'scheduled',approvedVersion:2});putRecord('marketing_outbox',{id:'local-due',organizationId:owner.organizationId,version:2,scheduledAt:'2000-01-01',state:'scheduled locally'});expect(localDispatch(owner).processed).toBe(1);expect(localDispatch(owner).processed).toBe(0);expect(getRecord<any>('marketing_outbox','local-due').state).toBe('ready for authorized external delivery');expect(()=>localDispatch(agent)).toThrow()})
it('converts working hours across daylight-saving boundaries',()=>{expect(new Date(workInstant('2098-01-15','09:00','America/New_York')).getUTCHours()).toBe(14);expect(new Date(workInstant('2098-07-15','09:00','America/New_York')).getUTCHours()).toBe(13)})
it('fits tasks around commitments and never moves an appointment',()=>{const previous=getSetting(agent,'personal');saveSetting(agent,'personal',{timezone:'America/New_York',workStart:'09:00',workEnd:'11:00'},previous.version);const task=createTask(agent,{title:'Plan acceptance',dueAt:'2098-01-15T12:00:00Z'});createAppointment(agent,{title:'Client commitment',startsAt:'2098-01-15T14:00:00Z',endsAt:'2098-01-15T15:00:00Z'});const plan=dayPlan(agent,'2098-01-15');expect(plan.blocks.every(b=>Date.parse(b.startsAt)>=Date.parse('2098-01-15T15:00:00Z'))).toBe(true);expect(plan.blocks.length).toBeGreaterThan(0);const block=plan.blocks[0];const saved=acceptDayBlock(agent,'2098-01-15',block.key);expect(saved.kind).toBe('proposed block');expect(dayPlan(agent,'2098-01-15').blocks.some(b=>b.key===block.key)).toBe(false)})
})

it('completing a task updates its linked proposed calendar block',async()=>{const service=await import('../../src/lib/platform/service');const t=service.createTask(agent,{title:'Linked calendar completion',dueAt:'2099-06-01T12:00:00Z'});const a=service.createAppointment(agent,{title:t.title,startsAt:'2099-06-01T12:00:00Z',endsAt:'2099-06-01T12:30:00Z',kind:'proposed block',taskId:t.id});service.completeTask(agent,t.id,t.version,true);expect(service.listAppointments(agent).find(e=>e.id===a.id)?.status).toBe('completed')})
