import {describe,it,expect,afterAll} from 'vitest'
import {PDFDocument,degrees,PDFName} from 'pdf-lib'
import {randomUUID} from 'node:crypto'
import {createTransaction,uploadDocument,documents} from '../../src/lib/services/transactions'
import {inspectDocument,prepareSigning,reviewSigning,previewPDF,UnconfiguredDocumenso} from '../../src/lib/services/document-services'
import {readRecords,deleteRecord,putRecord} from '../../src/lib/platform/store'
import type {PlatformActor} from '../../src/lib/platform/auth'
const org='pdf-test-'+randomUUID();const actor:PlatformActor={id:'pdf-agent',userId:'pdf-agent',organizationId:org,role:'agent',name:'Synthetic PDF Agent',market:'Florida',officeId:'fl',teamId:'fl'}
const t=createTransaction(actor,{address:'Synthetic PDF test property',client:'Synthetic PDF Client'})
const recipients=[{name:'Synthetic Signer',email:'signer@example.invalid',order:1}]
let documentId=''
afterAll(()=>{for(const kind of ['transaction_records','document_records','document_signatures'])for(const r of readRecords<{id:string;organizationId:string}>(kind))if(r.organizationId===org)deleteRecord(kind,r.id)})
describe('Actual PDF inspection and unsigned placement',()=>{
 it('reads actual page sizes and rotation from a valid PDF',async()=>{const pdf=await PDFDocument.create();pdf.addPage([612,792]).drawText('SYNTHETIC UNSIGNED DOCUMENT');const rotated=pdf.addPage([400,600]);rotated.setRotation(degrees(90));rotated.drawText('Rotated synthetic page');const doc=uploadDocument(actor,t.id,'synthetic-two-page.pdf','application/pdf',Buffer.from(await pdf.save()));documentId=doc.id;const result=await inspectDocument(actor,t.id,doc.id);expect(result.pages).toEqual([{page:1,width:612,height:792,rotation:0},{page:2,width:600,height:400,rotation:90}]);expect(result.document.sha256).toBe(doc.sha256)})
 it('rejects nonexistent pages and boxes extending off the actual page',async()=>{await expect(prepareSigning(actor,t.id,{documentId,recipients,fields:[{recipient:0,page:3,x:20,y:80}]})).rejects.toThrow('does not exist');await expect(prepareSigning(actor,t.id,{documentId,recipients,fields:[{recipient:0,page:1,x:80,y:80}]})).rejects.toThrow('fit inside');await expect(prepareSigning(actor,t.id,{documentId,recipients,fields:[{recipient:-1,page:1,x:20,y:80}]})).rejects.toThrow('recipient')})
 it('creates a single-page unsigned normalized preview and preserves source bytes',async()=>{const before=documents(actor,t.id).find(d=>d.id===documentId)!;const result=await previewPDF(actor,t.id,documentId,2,[{recipient:0,page:2,x:20,y:80}],recipients);const pdf=await PDFDocument.load(result.bytes);expect(pdf.getPageCount()).toBe(1);expect(pdf.getPage(0).getSize()).toEqual({width:600,height:400});expect(pdf.getPage(0).node.has(PDFName.of('Annots'))).toBe(false);expect(pdf.getTitle()).toContain('Unsigned');expect(documents(actor,t.id).find(d=>d.id===documentId)!.base64).toBe(before.base64)})
 it('hash-binds preparation to its inspected PDF and exact fields; rejects tampering and replay',async()=>{const p=await prepareSigning(actor,t.id,{documentId,recipients,fields:[{recipient:0,page:1,x:20,y:80}]});expect(p.documentVersion).toBe(1);expect(p.pages).toHaveLength(2);putRecord('document_signatures',{...p,fields:[{recipient:0,page:1,x:30,y:80}]});await expect(reviewSigning(actor,t.id,p.id)).rejects.toThrow('changed');putRecord('document_signatures',p);const reviewed=await reviewSigning(actor,t.id,p.id);expect(reviewed.state).toBe('reviewed');expect(reviewed.version).toBe(2);await expect(reviewSigning(actor,t.id,p.id)).rejects.toThrow('not found');expect((await new UnconfiguredDocumenso().status()).available).toBe(false)})
 it('rejects malformed PDFs and cross-organization inspection',async()=>{const bad=uploadDocument(actor,t.id,'invalid.pdf','application/pdf',Buffer.from('%PDF-1.4 malformed'));await expect(inspectDocument(actor,t.id,bad.id)).rejects.toThrow('Cannot inspect');await expect(inspectDocument({...actor,organizationId:'unrelated'},t.id,documentId)).rejects.toThrow('denied')})
})
