import {it,expect} from 'vitest'
import {PERSONAS} from '../../src/lib/platform/auth'
import {putRecord,readRecords,getRecord} from '../../src/lib/platform/store'
import {recruitAction,prospect} from '../../src/lib/platform/recruiting'
import {redeem,recover} from '../../src/lib/platform/access'
const owner=PERSONAS.find(a=>a.role==='broker_owner')!,agent=PERSONAS[0]
it('keeps recruiting tasks confidential and rejects stale events',()=>{putRecord('recruits',{id:'test-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Synthetic Recruit',version:1});const r=recruitAction(owner,'test-recruit',{kind:'task',version:1,text:'Internal follow-up',dueAt:'2098-01-01T10:00:00Z'});expect(r.events[0].done).toBe(false);expect(()=>recruitAction(owner,r.id,{kind:'note',version:1,text:'Stale'})).toThrow();expect(()=>prospect(agent,r.id)).toThrow();expect(()=>prospect({...owner,organizationId:'elsewhere'},r.id)).toThrow()})
it('converts Joined to a one-use captured invitation and supports recovery without sending',()=>{putRecord('recruits',{id:'joined-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Joined',name:'Synthetic New Agent',version:1});recruitAction(owner,'joined-recruit',{kind:'onboard',version:1,email:'invite-acceptance@example.test'});const mail=readRecords<any>('local_mail').find(m=>m.recipient==='invite-acceptance@example.test');const token=mail.url.split('/').pop();expect(redeem(token)).toMatch(/^[a-f0-9]{64}$/);expect(()=>redeem(token)).toThrow();const member=readRecords<any>('members').find(m=>m.email==='invite-acceptance@example.test');expect(member.role).toBe('agent');recover(member.email);expect(readRecords<any>('local_mail').filter(m=>m.recipient===member.email)).toHaveLength(2)})

it('requires learner consent before linking and hides progress after revocation',async()=>{const {getSetting,saveSetting}=await import('../../src/lib/platform/service');putRecord('recruits',{id:'consent-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Consent Synthetic',version:1});expect(()=>recruitAction(owner,'consent-recruit',{kind:'link-account',accountId:agent.id,version:1})).toThrow('opt in');const prefs=getSetting(agent,'personal');saveSetting(agent,'personal',{...prefs.value,shareRecruiting:true},prefs.version);const linked=recruitAction(owner,'consent-recruit',{kind:'link-account',accountId:agent.id,version:1});expect(linked.learning.consented).toBe(true);const current=getSetting(agent,'personal');saveSetting(agent,'personal',{...current.value,shareRecruiting:false},current.version);expect(prospect(owner,'consent-recruit').learning).toBeNull()})
