import {it,expect,vi} from 'vitest'
import {z} from 'zod'
import {PERSONAS} from '../../src/lib/platform/auth'
import {putRecord,readRecords,getRecord,deleteRecord,DurableStoreUnavailableError} from '../../src/lib/platform/store'
import {recruitAction,prospect,recruitingFailure} from '../../src/lib/platform/recruiting'
import {redeem,recover} from '../../src/lib/platform/access'
const owner=PERSONAS.find(a=>a.role==='broker_owner')!,agent=PERSONAS[0]
it('keeps recruiting tasks confidential and rejects stale events',()=>{putRecord('recruits',{id:'test-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Synthetic Recruit',version:1});const r=recruitAction(owner,'test-recruit',{kind:'task',version:1,text:'Internal follow-up',dueAt:'2098-01-01T10:00:00Z'});expect(r.events[0].done).toBe(false);expect(()=>recruitAction(owner,r.id,{kind:'note',version:1,text:'Stale'})).toThrow();expect(()=>prospect(agent,r.id)).toThrow();expect(()=>prospect({...owner,organizationId:'elsewhere'},r.id)).toThrow()})
it('converts Joined to a one-use captured invitation and supports recovery without sending',()=>{putRecord('recruits',{id:'joined-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Joined',name:'Synthetic New Agent',version:1});recruitAction(owner,'joined-recruit',{kind:'onboard',version:1,email:'invite-acceptance@example.test'});const mail=readRecords<any>('local_mail').find(m=>m.recipient==='invite-acceptance@example.test');const token=mail.url.split('/').pop();expect(redeem(token)).toMatch(/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/);expect(()=>redeem(token)).toThrow();const member=readRecords<any>('members').find(m=>m.email==='invite-acceptance@example.test');expect(member.role).toBe('agent');recover(member.email);expect(readRecords<any>('local_mail').filter(m=>m.recipient===member.email)).toHaveLength(2)})

it('requires learner consent before linking and hides progress after revocation',async()=>{const {getSetting,saveSetting}=await import('../../src/lib/platform/service');putRecord('recruits',{id:'consent-recruit',organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Consent Synthetic',version:1});expect(()=>recruitAction(owner,'consent-recruit',{kind:'link-account',accountId:agent.id,version:1})).toThrow('opt in');const prefs=getSetting(agent,'personal');saveSetting(agent,'personal',{...prefs.value,shareRecruiting:true},prefs.version);const linked=recruitAction(owner,'consent-recruit',{kind:'link-account',accountId:agent.id,version:1});expect(linked.learning.consented).toBe(true);const current=getSetting(agent,'personal');saveSetting(agent,'personal',{...current.value,shareRecruiting:false},current.version);expect(prospect(owner,'consent-recruit').learning).toBeNull()})

it('scopes recruiting reads and writes to a leader market and ignores forged ownership fields',()=>{const leader=PERSONAS.find(a=>a.role==='team_leader')!;const id='scope-recruit-'+Date.now();putRecord('recruits',{id,organizationId:owner.organizationId,officeId:'al',stage:'New inquiry',name:'Scope Synthetic',version:1});const otherOffice={id:id+'-fl',organizationId:owner.organizationId,officeId:'fl',stage:'New inquiry',name:'Other Office',version:1};putRecord('recruits',otherOffice);expect(()=>prospect(leader,otherOffice.id)).toThrow('Prospect not found');expect(()=>prospect(agent,id)).toThrow();const changed=recruitAction(leader,id,{kind:'stage',stage:'Contacted',version:1,organizationId:'attacker-org',officeId:'fl',ownerId:'u-julio',role:'broker_owner'});expect(changed.organizationId).toBe(owner.organizationId);expect(changed.officeId).toBe('al');expect(changed.ownerId).toBeUndefined();expect(changed.stage).toBe('Contacted');expect(changed.events.at(-1)).toMatchObject({organizationId:owner.organizationId,officeId:'al',actorId:leader.id,actorRole:leader.role,kind:'stage'});const auditRow=readRecords<any>('audit').find(a=>a.action==='recruit.stage'&&a.resource===id);expect(auditRow).toMatchObject({organizationId:owner.organizationId,actorId:leader.id,actorRole:leader.role,officeId:'al'});for(const e of readRecords<any>('recruit_events').filter(e=>e.prospectId===id||e.prospectId===otherOffice.id))deleteRecord('recruit_events',e.id);deleteRecord('recruits',id);deleteRecord('recruits',otherOffice.id);if(auditRow)deleteRecord('audit',auditRow.id)})

it('does not create a local invite or mark a prospect onboarded in production mode',()=>{const id='production-invite-'+Date.now();putRecord('recruits',{id,organizationId:owner.organizationId,officeId:'fl',stage:'Joined',name:'Production Gate Synthetic',version:1});const tokenCount=readRecords<any>('access_tokens').length;const mailCount=readRecords<any>('local_mail').length;try{vi.stubEnv('NODE_ENV','production');expect(()=>recruitAction(owner,id,{kind:'onboard',version:1,email:'production-gate@example.test'})).toThrow('Google identity and invitation delivery are not configured');expect(getRecord<any>('recruits',id)?.onboardedAt).toBeUndefined();expect(readRecords<any>('access_tokens')).toHaveLength(tokenCount);expect(readRecords<any>('local_mail')).toHaveLength(mailCount)}finally{vi.unstubAllEnvs()}for(const e of readRecords<any>('recruit_events').filter(e=>e.prospectId===id))deleteRecord('recruit_events',e.id);for(const e of readRecords<any>('audit').filter(e=>e.action.startsWith('recruit.')&&e.resource===id))deleteRecord('audit',e.id);deleteRecord('recruits',id)})

it('rejects cross-prospect task completion and preserves task history',()=>{const first='task-recruit-a-'+Date.now(),second='task-recruit-b-'+Date.now();putRecord('recruits',{id:first,organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Task A',version:1});putRecord('recruits',{id:second,organizationId:owner.organizationId,officeId:'fl',stage:'Considering',name:'Task B',version:1});const withTask=recruitAction(owner,first,{kind:'task',version:1,text:'Private follow-up',dueAt:'2098-01-01T10:00:00Z'});const task=withTask.events.find((e:any)=>e.kind==='task')!;expect(()=>recruitAction(owner,second,{kind:'complete',version:1,taskId:task.id})).toThrow('Task not found');expect(getRecord<any>('recruit_events',task.id)?.done).toBe(false);for(const id of [first,second]){for(const e of readRecords<any>('recruit_events').filter(e=>e.prospectId===id))deleteRecord('recruit_events',e.id);for(const e of readRecords<any>('audit').filter(e=>e.action.startsWith('recruit.')&&e.resource===id))deleteRecord('audit',e.id);deleteRecord('recruits',id)}})

it('maps durable-store failure to a safe unavailable response and malformed actions to client errors',()=>{expect(recruitingFailure(new DurableStoreUnavailableError())).toEqual({status:503,message:'Recruiting is unavailable until durable brokerage storage is configured.'});expect(recruitingFailure(new Error('postgres://secret-host with private data'))).toEqual({status:500,message:'Unable to access recruiting records.'});expect(recruitingFailure((()=>{try{z.string().parse(7)}catch(error){return error}})())).toEqual({status:400,message:'Review the recruiting action fields and try again.'})})
