import 'server-only'
import {randomBytes,createHash,randomUUID} from 'node:crypto'
import {getRecord,putRecord,readRecords,transaction} from './store'
import {PERSONAS,assertCapability,type PlatformActor,type PlatformRole,createSession,AccessError} from './auth'
import {audit} from './service'
const hash=(s:string)=>createHash('sha256').update(s).digest('hex')
export function invite(a:PlatformActor,input:{name:string;email:string;role:PlatformRole;officeId:'al'|'fl'}){assertCapability(a,'settings.people');if(!input.email.endsWith('.test'))throw new AccessError('Use a synthetic .test address in the local demo',400);const id=randomUUID(),token=randomBytes(32).toString('hex');const actor:PlatformActor={id,userId:id,organizationId:a.organizationId,role:input.role,name:input.name,officeId:input.officeId,teamId:input.officeId,market:input.officeId==='al'?'Alabama':'Florida'};putRecord('access_tokens',{id:hash(token),actor,email:input.email,expiresAt:Date.now()+86400000,used:false,kind:'invite'});putRecord('local_mail',{id:randomUUID(),organizationId:a.organizationId,recipient:input.email,subject:'Local RCRE invitation',url:'/access/'+token,status:'captured locally, not sent',createdAt:new Date().toISOString()});audit(a,'invitation.created',id);return {status:'captured locally'}}
export function recover(email:string){const m=readRecords<any>('members').find(m=>m.email===email);if(m?.actor){const token=randomBytes(32).toString('hex');putRecord('access_tokens',{id:hash(token),actor:m.actor,email,expiresAt:Date.now()+1800000,used:false,kind:'recovery'});putRecord('local_mail',{id:randomUUID(),organizationId:m.actor.organizationId,recipient:email,subject:'Local access recovery',url:'/access/'+token,status:'captured locally, not sent',createdAt:new Date().toISOString()})}return {message:'If this synthetic account exists, an access link was captured in the owner’s local mailbox. No email was sent.'}}
export function redeem(token:string){return transaction(()=>{const record=getRecord<any>('access_tokens',hash(token));if(!record||record.used||record.expiresAt<Date.now())throw new AccessError('This local access link expired or was already used',400);const existing=getRecord<any>('members',record.actor.id);if(existing?.disabled)throw new AccessError('Membership inactive');putRecord('members',{...existing,id:record.actor.id,actor:record.actor,role:existing?.role??record.actor.role,email:record.email,disabled:false});putRecord('access_tokens',{...record,used:true});return createSession(record.actor.id)})}
