import 'server-only'
import {randomUUID,createHash} from 'node:crypto'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import path from 'node:path'
import {z} from 'zod'
import {AccessError,assertCapability,type PlatformActor} from './auth'
import {getRecord,putRecord,readRecords,storageRoot,transaction,deleteRecord} from './store'
import {audit,canEditMarketing,canReadMarketing} from './service'
export interface LibraryAsset {id:string;organizationId:string;ownerId:string;name:string;mime:string;size:number;sha256:string;version:number;previousId:string|null;createdAt:string;archived:boolean;source:string;license:string;tags:string;market:string;audience:string;contentId?:string}
const directory=path.join(storageRoot,'library-assets')
export function listAssets(a:PlatformActor){assertCapability(a,'marketing');return readRecords<LibraryAsset>('library_assets').filter(r=>canEditMarketing(a,r)||readRecords<any>('marketing').some(c=>canReadMarketing(a,c)&&c.assetIds?.includes(r.id)))}
export function assetFor(a:PlatformActor,id:string){const r=listAssets(a).find(r=>r.id===id);if(!r)throw new AccessError('Asset not found',404);return r}
export function saveAsset(a:PlatformActor,name:string,mime:string,bytes:Buffer,previousId?:string,metadata:unknown={}){return transaction(()=>{const meta=z.object({source:z.string().max(1000).default('Not supplied — rights review required'),license:z.string().max(500).default('Not supplied'),tags:z.string().max(500).default(''),market:z.enum(['Both markets','Alabama','Florida']).default('Both markets'),audience:z.string().max(500).default('Not specified'),contentId:z.string().max(100).default('')}).parse(metadata);assertCapability(a,'marketing');if(bytes.length===0||bytes.length>20*1024*1024)throw new AccessError('Choose a file between 1 byte and 20 MB',400);const valid=mime==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':mime==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:mime==='video/mp4'?bytes.subarray(4,8).toString()==='ftyp':false;if(!valid)throw new AccessError('Only verified PDF, PNG, JPEG and MP4 files are accepted',400);const old=previousId?assetFor(a,previousId):null;if(old&&!canEditMarketing(a,old))throw new AccessError('Copy approved media into your own asset before replacing it');const linked=meta.contentId?getRecord<any>('marketing',meta.contentId):null;if(meta.contentId&&(!linked||!canEditMarketing(a,linked)))throw new AccessError('Related content is outside your edit scope',404);const r:LibraryAsset={...meta,id:randomUUID(),organizationId:a.organizationId,ownerId:old?.ownerId??a.id,name:path.basename(name).replace(/[\r\n\x00-\x1f]/g,'').slice(0,180)||'asset',mime,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),version:(old?.version??0)+1,previousId:old?.id??null,createdAt:new Date().toISOString(),archived:false};mkdirSync(directory,{recursive:true,mode:0o700});writeFileSync(path.join(directory,r.id),bytes,{mode:0o600,flag:'wx'});putRecord('library_assets',r);if(linked){putRecord('marketing_history',{...linked,id:randomUUID(),contentId:linked.id,recordedAt:new Date().toISOString()});putRecord('marketing',{...linked,assetIds:[...(linked.assetIds??[]),r.id],status:'draft',approvedBy:null,approvedVersion:null,version:linked.version+1});deleteRecord('marketing_outbox',linked.id)}audit(a,'library.uploaded',r.id);return r})}
export function assetBytes(a:PlatformActor,id:string){const asset=assetFor(a,id);return {asset,bytes:readFileSync(path.join(directory,asset.id))}}
export function archiveAsset(a:PlatformActor,id:string){const old=assetFor(a,id);if(!canEditMarketing(a,old))throw new AccessError('You cannot archive another owner’s media');putRecord('library_assets',{...old,archived:true});audit(a,'library.archived',id);return {archived:true}}
export function localDispatch(a:PlatformActor){assertCapability(a,'marketing');if(a.role==='agent')throw new AccessError('Reviewer access required');return transaction(()=>{let count=0;for(const item of readRecords<any>('marketing_outbox')){if(item.organizationId!==a.organizationId||item.state!=='scheduled locally'||Date.parse(item.scheduledAt)>Date.now())continue;const content=getRecord<any>('marketing',item.id);if(!content||!canEditMarketing(a,content)||content.status!=='scheduled'||content.approvedVersion!==item.version)continue;putRecord('marketing_outbox',{...item,state:'ready for authorized external delivery',processedAt:new Date().toISOString()});audit(a,'marketing.prepared-local-delivery',item.id);count++}return {processed:count,externalMessagesSent:0}})}
