import 'server-only'
import {randomUUID} from 'node:crypto'
import {z} from 'zod'
import {type PlatformActor,assertCapability,AccessError,directory} from './auth'
import {readRecords,getRecord,putRecord,transaction} from './store'
import {audit,seed,createAppointment,getSetting} from './service'
import {progressFor} from '../academy-service'
import {invite} from './access'
export function prospects(a:PlatformActor){assertCapability(a,'recruiting');seed();return readRecords<any>('recruits').filter(r=>r.organizationId===a.organizationId&&(a.role==='broker_owner'||r.officeId===a.officeId))}
export function prospect(a:PlatformActor,id:string){const r=prospects(a).find(r=>r.id===id);if(!r)throw new AccessError('Prospect not found',404);const linked=r.linkedActorId?directory(a.organizationId).find(p=>p.id===r.linkedActorId&&(a.role==='broker_owner'||p.officeId===a.officeId)):null;const shared=linked&&getSetting(linked,'personal').value.shareRecruiting===true;const learning=shared?{consented:true,completedLessons:progressFor(linked).completedLessonIds.length,communityPosts:readRecords<any>('community_post').filter(p=>p.organizationId===a.organizationId&&p.ownerId===linked.id&&!p.draft).length,publicPreviewViews:readRecords<any>('consented_preview_events').filter(p=>p.organizationId===a.organizationId&&p.ownerId===linked.id).length,lastRecordedAt:getRecord<any>('academy_progress',`${a.organizationId}:${linked.id}`)?.updatedAt??null}:null;const linkableAccounts=directory(a.organizationId).filter(p=>!p.disabled&&(a.role==='broker_owner'||p.officeId===a.officeId)&&getSetting(p,'personal').value.shareRecruiting===true).map(p=>({id:p.id,name:p.name}));return {...r,learning,linkableAccounts,events:readRecords<any>('recruit_events').filter(e=>e.prospectId===id&&e.organizationId===a.organizationId)}}
export function recruitAction(a:PlatformActor,id:string,b:any){return transaction(()=>{const r=prospect(a,id);if(r.version!==b.version)throw new AccessError('Prospect changed; refresh before saving',409);const text=z.string().trim().min(1).max(5000);let event:any={id:randomUUID(),prospectId:id,organizationId:a.organizationId,actorId:a.id,at:new Date().toISOString(),kind:b.kind};if(b.kind==='link-account'){const member=directory(a.organizationId).find(p=>p.id===b.accountId&&!p.disabled&&(a.role==='broker_owner'||p.officeId===a.officeId));if(!member)throw new AccessError('Account is outside your scope',404);if(getSetting(member,'personal').value.shareRecruiting!==true)throw new AccessError('The learner must opt in from Personal settings first',403);r.linkedActorId=member.id;event.text='Linked learning activity with the learner’s current consent'}else if(b.kind==='stage'){const stage=z.enum(['New inquiry','Contacted','Meeting scheduled','Considering','Joined','Paused','Rejected','Do not contact','Withdrawn']).parse(b.stage);event.text='Stage changed from '+r.stage+' to '+stage;r.stage=stage}else if(b.kind==='note'||b.kind==='call')event.text=text.parse(b.text);else if(b.kind==='task'){event.text=text.parse(b.text);event.dueAt=z.string().datetime().parse(b.dueAt);event.done=false}else if(b.kind==='complete'){const task=getRecord<any>('recruit_events',b.taskId);if(!task||task.prospectId!==id||task.organizationId!==a.organizationId||task.kind!=='task')throw new AccessError('Task not found',404);putRecord('recruit_events',{...task,done:true});event.text='Completed recruiting task'}else if(b.kind==='meeting'){const meeting=createAppointment(a,{title:'Recruiting: '+r.name,startsAt:b.startsAt,endsAt:b.endsAt,location:text.parse(b.location||'Local meeting')});event.text=meeting.title;event.appointmentId=meeting.id;event.startsAt=meeting.startsAt}else if(b.kind==='onboard'){if(r.stage!=='Joined')throw new AccessError('Move the prospect to Joined before onboarding',409);if(r.onboardedAt)throw new AccessError('Invitation already created',409);invite(a,{name:r.name,email:z.string().email().parse(b.email),role:'agent',officeId:r.officeId==='al'?'al':'fl'});event.text='Agent invitation captured in local mailbox; no email sent';r.onboardedAt=event.at}else throw new AccessError('Unknown action',400);putRecord('recruit_events',event);const {events,learning,linkableAccounts,...next}=r;putRecord('recruits',{...next,version:r.version+1});audit(a,'recruit.'+b.kind,id);return prospect(a,id)})}
