import {z} from 'zod'
const optionalText=z.string().max(1000).optional()
export const settingsSchema:Record<string,z.ZodTypeAny>={
audit:z.object({reviewDays:z.number().int().min(1).max(3650),retentionNote:z.string().max(2000)}).strict(),
personal:z.object({name:optionalText,email:z.string().email().or(z.literal('')).optional(),phone:optionalText,market:z.enum(['Florida','Alabama']).optional(),timezone:z.enum(['America/New_York','America/Chicago','America/Denver','America/Los_Angeles']).optional(),workStart:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/).optional(),workEnd:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/).optional(),theme:z.enum(['light','dark']).optional(),reducedMotion:z.boolean().optional(),largeText:z.boolean().optional(),quietStart:z.number().int().min(0).max(23).optional(),quietEnd:z.number().int().min(0).max(23).optional(),calendarView:z.enum(['week','day']).optional(),inAppNotifications:z.boolean().optional(),shareRecruiting:z.boolean().optional(),calendarReminders:z.boolean().optional(),reminderMinutes:z.number().int().min(0).max(1440).optional()}).strict().refine(v=>!v.workStart||!v.workEnd||v.workEnd>v.workStart,'Work end must follow start'),
leads:z.object({sourceOptions:z.string().max(1000).optional(),stageLabels:z.record(z.string().trim().min(1).max(80)).optional(),enabled:z.boolean(),synthetic:z.boolean().optional(),responseMinutes:z.number().min(1).max(10080),graceMinutes:z.number().min(0).max(1440),stageDays:z.record(z.number().min(1).max(365)).optional(),routing:z.object({al:z.string(),fl:z.string()}).optional(),taskEstimateMinutes:z.number().int().min(5).max(180).optional(),followUpDays:z.number().int().min(1).max(365).optional(),alertRecipient:z.string().max(100).optional(),escalationMinutes:z.number().int().min(0).max(10080).optional(),quietStart:z.number().int().min(0).max(23).optional(),quietEnd:z.number().int().min(0).max(23).optional()}).strict(),
brokerage:z.object({displayName:optionalText,legalName:optionalText,publicEmail:z.string().email().or(z.literal('')).optional(),publicPhone:optionalText,alOfficeAddress:optionalText,flOfficeAddress:optionalText,flPhone:optionalText,workStart:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/).optional(),workEnd:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/).optional(),documentOwners:optionalText,contentOwners:optionalText,lender:z.object({name:z.string().min(1).max(200),phone:z.string().min(1).max(80),email:z.string().email(),website:z.string().url(),individualNmls:z.string().regex(/^\d+$/),companyNmls:z.string().regex(/^\d+$/)})}).strict(),
marketing:z.object({requireApproval:z.literal(true),defaultAttribution:z.string().max(500),defaultChannel:z.enum(['Email','Instagram','Facebook','YouTube','Print']),brandRules:z.string().max(2000)}).strict(),
}
