import {randomUUID,createHash} from 'node:crypto'
import {PDFDocument,PDFName,rgb,degrees,StandardFonts} from 'pdf-lib'
import type {PlatformActor} from '@/lib/platform/auth'
import {putRecord,readRecords,transaction} from '@/lib/platform/store'
import {documents,requireTransaction,hash} from './transactions'
export const SIGNATURE_WIDTH_PERCENT=24,SIGNATURE_HEIGHT_PERCENT=7
export interface PDFPageInfo {page:number;width:number;height:number;rotation:number}
export interface SignaturePreparation {id:string;transactionId:string;organizationId:string;ownerId:string;documentId:string;documentHash:string;documentVersion:number;pages:PDFPageInfo[];recipients:{name:string;email:string;order:number}[];fields:{recipient:number;page:number;x:number;y:number}[];state:'prepared'|'reviewed'|'blocked';version:number;reviewedBy?:string;payloadHash?:string;updatedAt:string}
export interface SigningAdapter {status():Promise<{available:boolean;reason:string}>;createRequest(preparation:SignaturePreparation):Promise<{remoteId:string;signerUrls:string[]}>;verifyCompletion(remoteId:string):Promise<{completed:boolean;evidenceHash:string|null}>}
export interface DocumentProcessingAdapter {extractText(bytes:Buffer):Promise<string>}
export class UnconfiguredDocumenso implements SigningAdapter {
 async status(){return {available:false,reason:'No project-contained Documenso engine, API key, signer session or callback verification is configured. Actual signing is blocked.'}}
 async createRequest(_p:SignaturePreparation):Promise<{remoteId:string;signerUrls:string[]}>{throw new Error((await this.status()).reason)}
 async verifyCompletion(_id:string){return {completed:false,evidenceHash:null}}
}
export class UnconfiguredStirling implements DocumentProcessingAdapter {async extractText(_bytes:Buffer):Promise<string>{throw new Error('Stirling PDF extraction unavailable: a project-contained verified service is required. Upload plain text excerpts for local inspection coordination.')}}
export async function inspectPDF(bytes:Uint8Array){let pdf:PDFDocument;try{pdf=await PDFDocument.load(bytes,{updateMetadata:false})}catch{throw new Error('Cannot inspect this PDF. Use a valid, unencrypted PDF.')}
 let sourcePages;try{sourcePages=pdf.getPages()}catch{throw new Error('Cannot inspect this PDF. Its page tree is invalid.')}
 const pages=sourcePages.map((p,i)=>{const crop=p.getCropBox(),rotation=((p.getRotation().angle%360)+360)%360;if(![0,90,180,270].includes(rotation)||!Number.isFinite(crop.width)||!Number.isFinite(crop.height)||crop.width<=0||crop.height<=0||crop.width>14400||crop.height>14400)throw new Error('Unsupported PDF page dimensions or rotation');return {page:i+1,width:rotation%180?crop.height:crop.width,height:rotation%180?crop.width:crop.height,rotation}})
 if(!pages.length||pages.length>2000)throw new Error('PDF must contain 1–2000 pages');return {pdf,pages}
}
export async function inspectDocument(a:PlatformActor,id:string,documentId:string){requireTransaction(a,id);const document=documents(a,id).find(d=>d.id===documentId);if(!document||document.mime!=='application/pdf')throw new Error('Select an authorized PDF version');if(createHash('sha256').update(Buffer.from(document.base64,'base64')).digest('hex')!==document.sha256&&hash(document.base64)!==document.sha256)throw new Error('Document content no longer matches its recorded hash');const inspected=await inspectPDF(Buffer.from(document.base64,'base64'));return {...inspected,document}}
export function validateSignaturePlacement(pages:PDFPageInfo[],recipients:SignaturePreparation['recipients'],fields:SignaturePreparation['fields']){if(!recipients.length||recipients.length>20||!fields.length||fields.length>100)throw new Error('Provide 1–20 recipients and 1–100 fields');if(recipients.some(r=>!r.name.trim()||!/^\S+@\S+\.\S+$/.test(r.email)||!Number.isInteger(r.order)||r.order<1))throw new Error('Each recipient needs a valid name, email and positive signing order');if(new Set(recipients.map(r=>r.email.toLowerCase())).size!==recipients.length)throw new Error('Each signer must have a distinct email');for(const f of fields){if(!Number.isInteger(f.recipient)||f.recipient<0||f.recipient>=recipients.length)throw new Error('Each field must refer to a recipient');if(!Number.isInteger(f.page)||!pages.some(p=>p.page===f.page))throw new Error('Signature page does not exist in the selected PDF');if(!Number.isFinite(f.x)||!Number.isFinite(f.y)||f.x<0||f.y<0||f.x+SIGNATURE_WIDTH_PERCENT>100||f.y+SIGNATURE_HEIGHT_PERCENT>100)throw new Error('The complete signature box must fit inside the selected page')}if(recipients.some((_,i)=>!fields.some(f=>f.recipient===i)))throw new Error('Every recipient needs at least one signature field')}
const fingerprint=(p:Pick<SignaturePreparation,'documentId'|'transactionId'|'documentHash'|'documentVersion'|'pages'|'recipients'|'fields'>)=>hash(JSON.stringify({transactionId:p.transactionId,documentId:p.documentId,documentHash:p.documentHash,documentVersion:p.documentVersion,pages:p.pages,recipients:p.recipients,fields:p.fields}))
export function signingPreparations(a:PlatformActor,id:string){requireTransaction(a,id);return readRecords<SignaturePreparation>('document_signatures').filter(s=>s.transactionId===id&&s.organizationId===a.organizationId)}
export async function prepareSigning(a:PlatformActor,id:string,input:{documentId:string;recipients:SignaturePreparation['recipients'];fields:SignaturePreparation['fields']}){const {document:d,pages}=await inspectDocument(a,id,input.documentId);validateSignaturePlacement(pages,input.recipients,input.fields);const p:SignaturePreparation={...input,id:randomUUID(),transactionId:id,organizationId:a.organizationId,ownerId:a.userId,documentHash:d.sha256,documentVersion:d.version,pages,state:'prepared',version:1,updatedAt:new Date().toISOString()};p.payloadHash=fingerprint(p);return putRecord('document_signatures',p)}
export async function reviewSigning(a:PlatformActor,id:string,prepId:string){const original=signingPreparations(a,id).find(p=>p.id===prepId);if(!original||original.state!=='prepared')throw new Error('Prepared signature request not found');const {document,pages}=await inspectDocument(a,id,original.documentId);return transaction(()=>{const p=signingPreparations(a,id).find(v=>v.id===prepId);if(!p||p.state!=='prepared'||p.version!==original.version)throw new Error('Preparation changed. Reload and review again');if(p.documentHash!==document.sha256||p.documentVersion!==document.version||p.payloadHash!==fingerprint(p)||JSON.stringify(p.pages)!==JSON.stringify(pages))throw new Error('PDF or placement changed. Prepare and review again');validateSignaturePlacement(pages,p.recipients,p.fields);return putRecord('document_signatures',{...p,state:'reviewed',version:p.version+1,reviewedBy:a.userId,updatedAt:new Date().toISOString()})})}
/** Builds an unsigned, annotation-free single-page visual copy. Original bytes remain immutable. */
export async function previewPDF(a:PlatformActor,id:string,documentId:string,pageNumber:number,fields:SignaturePreparation['fields']=[],recipients:SignaturePreparation['recipients']=[]){const {document,pdf,pages}=await inspectDocument(a,id,documentId);const info=pages.find(p=>p.page===pageNumber);if(!info)throw new Error('PDF page does not exist');if(fields.length)validateSignaturePlacement(pages,recipients,fields);const original=pdf.getPage(pageNumber-1),crop=original.getCropBox(),preview=await PDFDocument.create();const embedded=original.node.Contents()?await preview.embedPage(original,{left:crop.x,bottom:crop.y,right:crop.x+crop.width,top:crop.y+crop.height}):undefined;const page=preview.addPage([info.width,info.height]);const rotation=info.rotation;if(embedded)page.drawPage(embedded,{x:rotation===180?info.width:rotation===270?info.width:0,y:rotation===90?info.height:rotation===180?info.height:0,rotate:degrees(-rotation)});const font=await preview.embedFont(StandardFonts.Helvetica);for(const f of fields.filter(f=>f.page===pageNumber)){const x=f.x/100*info.width,y=info.height-(f.y+SIGNATURE_HEIGHT_PERCENT)/100*info.height,w=SIGNATURE_WIDTH_PERCENT/100*info.width,h=SIGNATURE_HEIGHT_PERCENT/100*info.height;page.drawRectangle({x,y,width:w,height:h,color:rgb(1,.9,.58),opacity:.6,borderWidth:1,borderColor:rgb(.45,.3,.05)});page.drawText(`SIGNER ${f.recipient+1} - UNSIGNED`,{x:x+3,y:y+h/2,size:Math.min(9,w/16),font,color:rgb(.1,.1,.1)})}page.node.delete(PDFName.of('Annots'));page.node.delete(PDFName.of('AA'));preview.setTitle('Unsigned signature placement preview');return {bytes:await preview.save(),documentHash:document.sha256,documentVersion:document.version}}
