import {projectFubDeal} from './transactions'
import {createHash,randomUUID} from 'node:crypto'
import {z} from 'zod'
import {directory,assertCapability,type PlatformActor} from '@/lib/platform/auth'
import {readRecords,getRecord,putRecord,transaction} from '@/lib/platform/store'
import type {Contact,Task,Appointment} from '@/lib/platform/service'
import {verifyFubSignature,computeFubSignature} from '@/lib/fub/signature'
import {runBackfill,type BackfillResource} from '@/lib/sync/backfill'
import type {SyncStateRow} from '@/lib/domain-types'
import {routeEvent,isSupportedEvent} from '@/lib/fub/webhook'
import {normalizePerson,normalizeTask,normalizeAppointment,normalizeDeal,normalizeCall,normalizeEmail,normalizeTextMessage,deriveTimestamps,type ActivityDraft} from '@/lib/fub/normalize'
export interface FubDelivery {id:string;organizationId:string;event:string;resourceIds:number[];eventCreated:string;receivedAt:string;payloadHash:string;state:'queued'|'running'|'completed'|'failed'|'ignored';attempts:number;duplicates:number;nextAttemptAt:string;leaseUntil?:string;completedAt?:string;error?:string}
interface Fixture {id:string;organizationId:string;kind:string;resourceId:number;record:Record<string,any>;updatedAt:string}
const eventRoute=(name:string)=>name.startsWith('events')?{kind:'events',deleted:/Deleted$/.test(name)}:routeEvent(name)
const ORG='rcre-local';const key=(s:string)=>createHash('sha256').update(s).digest('hex');const safeKinds=['people','calls','textMessages','emails','appointments','deals','tasks','emEvents','events']
const payloadSchema=z.object({eventId:z.string().min(1).max(200),event:z.string().min(1).max(100),eventCreated:z.string().datetime({offset:true}),resourceIds:z.array(z.number().int().positive()).max(100)}).passthrough()
export function localFubEnabled(){return process.env.RCRE_APP_MODE==='local' || process.env.NODE_ENV!=='production'}
function ownerOnly(a:PlatformActor){assertCapability(a,'settings.integrations');if(a.organizationId!==ORG)throw new Error('Organization denied');if(!localFubEnabled())throw new Error('FUB local protocol facility unavailable outside local mode')}
function localMode(){if(!localFubEnabled())throw new Error('Local FUB protocol mode disabled')}
export function ingestLocalFub(raw:string,signature:string|null,systemKey=process.env.RCRE_FUB_LOCAL_TEST_KEY){localMode();if(!systemKey)throw new Error('Local FUB webhook secret is not configured; external connection remains disabled');if(Buffer.byteLength(raw)>100000)throw new Error('Webhook payload too large');if(!verifyFubSignature(raw,signature,systemKey))throw new Error('Invalid FUB signature');const payload=payloadSchema.parse(JSON.parse(raw));return transaction(()=>{const now=new Date().toISOString();const minute=now.slice(0,16);const rate=getRecord<{id:string;count:number}>('fub_rate',minute)||{id:minute,count:0};if(rate.count>=120)throw new Error('Local intake rate limit exceeded; retry after 60 seconds');putRecord('fub_rate',{...rate,count:rate.count+1});const id=`${ORG}:${payload.eventId}`;const old=getRecord<FubDelivery>('fub_deliveries',id);if(old){putRecord('fub_deliveries',{...old,duplicates:old.duplicates+1});return {status:'duplicate',eventId:payload.eventId}}const routed=eventRoute(payload.event);const supported=isSupportedEvent(payload.event)||(routed.deleted&&safeKinds.includes(routed.kind));const row:FubDelivery={id,organizationId:ORG,event:payload.event,resourceIds:payload.resourceIds,eventCreated:payload.eventCreated,receivedAt:now,payloadHash:key(raw),state:supported?'queued':'ignored',attempts:0,duplicates:0,nextAttemptAt:now};putRecord('fub_deliveries',row);return {status:supported?'accepted':'ignored',eventId:payload.eventId}})}
export function saveFixture(a:PlatformActor,kind:string,record:Record<string,any>){ownerOnly(a);if(!safeKinds.includes(kind)||!Number.isSafeInteger(record.id)||record.id<=0)throw new Error('Known resource and positive FUB ID required');if(JSON.stringify(record).length>30000)throw new Error('Synthetic fixture too large');const id=`${ORG}:${kind}:${record.id}`;const {body,message,note,background,...safe}=record;return putRecord<Fixture>('fub_fixtures',{id,organizationId:ORG,kind,resourceId:record.id,record:safe,updatedAt:new Date().toISOString()})}
export function mapLocalFubUser(a:PlatformActor,fubUserId:number,userId:string){ownerOnly(a);const p=directory(a.organizationId).find(p=>p.id===userId&&p.role==='agent'&&!p.disabled);if(!p||!Number.isSafeInteger(fubUserId)||fubUserId<1)throw new Error('Valid synthetic FUB user and local agent required');return putRecord('fub_user_mappings',{id:`${ORG}:${fubUserId}`,organizationId:ORG,fubUserId,userId})}
function resolveUser(id:number|undefined|null){if(!id)return null;const userId=getRecord<{userId:string}>('fub_user_mappings',`${ORG}:${id}`)?.userId;return directory(ORG).find(p=>p.id===userId&&!p.disabled&&p.role==='agent')?.id||null}
function activeOwner(userId:string|null|undefined){const owner=directory(ORG).find(p=>p.id===userId&&!p.disabled&&p.role==='agent');if(!owner)throw new Error('FUB assignee has no active approved local mapping');return owner}
const personId=(id:number)=>`fub-local-people-${id}`
function project(kind:string,record:Record<string,any>,eventCreated:string){const id=Number(record.id);const deleted=getRecord<{deletedAt:string}>('fub_tombstones',`${ORG}:${kind}:${id}`);if(deleted)return;if(record.personId&&getRecord('fub_tombstones',`${ORG}:people:${Number(record.personId)}`))return;if(kind==='people'){const n=normalizePerson(ORG,{...record,id},resolveUser);const owner=activeOwner(n.assignedUserId);if(!owner)throw new Error('FUB assignee has no approved local mapping');const old=getRecord<Contact>('contacts',personId(id));if(!n.fubCreatedAt)throw new Error('Source person creation date is missing; original receipt time cannot be invented');const created=n.fubCreatedAt;const next={...old,id:personId(id),organizationId:ORG,officeId:owner.officeId,ownerId:owner.id,version:(old?.version||0)+1,fubId:id,fubPersonId:id,sourceSystem:'fub-local-fixture',sourceDeleted:false,firstName:n.firstName||'Synthetic',lastName:n.lastName||'',initials:`${(n.firstName||'S')[0]}${(n.lastName||'')[0]||''}`,email:n.emails[0]?.value||'',phone:n.phones[0]?.value||'',stage:(n.stage||'New Lead') as Contact['stage'],source:n.source||'FUB local fixture',tags:n.tags,location:owner.market,receivedAt:old?.receivedAt||created,stageEnteredAt:old?.stage===n.stage?old.stageEnteredAt:n.fubUpdatedAt||eventCreated,firstTouchAt:old?.firstTouchAt||null,lastTouchAt:old?.lastTouchAt||null,lastInboundAt:old?.lastInboundAt||null,lastOutboundAt:old?.lastOutboundAt||null,timeline:old?.timeline||[],reasons:old?.reasons||[],priority:old?.priority||null};putRecord('contacts',next);if(old&&old.ownerId!==owner.id)putRecord('assignment_history',{id:randomUUID(),organizationId:ORG,contactId:next.id,originalRecipient:old.ownerId,from:old.ownerId,to:owner.id,at:n.fubUpdatedAt||eventCreated,actorId:'fub-local-worker'});return}
 const contact=record.personId?getRecord<Contact>('contacts',personId(Number(record.personId))):null;if(!contact)throw new Error('Referenced person must be imported before this resource');const owner=activeOwner(contact.ownerId);if(kind==='tasks'){const taskOwner=record.assignedUserId!=null?activeOwner(resolveUser(record.assignedUserId)):owner;const n=normalizeTask(ORG,contact.id,taskOwner.id,{...record,id});if(!n.dueAt)throw new Error('Task due date unknown; do not invent a deadline');const old=getRecord<Task>('tasks',`fub-local-tasks-${id}`);putRecord('tasks',{id:`fub-local-tasks-${id}`,organizationId:ORG,officeId:taskOwner.officeId,ownerId:taskOwner.id,contactId:contact.id,title:n.title,dueAt:n.dueAt||eventCreated,done:n.isCompleted,version:(old?.version||0)+1,fubId:id,sourceSystem:'fub-local-fixture'});return}
 if(kind==='appointments'){const n=normalizeAppointment(ORG,contact.id,owner.id,{...record,id});if(!n.startsAt||!n.endsAt||Date.parse(n.endsAt)<=Date.parse(n.startsAt))throw new Error('Appointment start and end required');const old=getRecord<Appointment>('appointments',`fub-local-appointments-${id}`);putRecord('appointments',{id:`fub-local-appointments-${id}`,organizationId:ORG,officeId:owner.officeId,ownerId:owner.id,contactId:contact.id,title:n.title||'Synthetic FUB appointment',startsAt:n.startsAt,endsAt:n.endsAt,location:n.location||'',kind:'appointment',createdAt:typeof record.created==='string'&&Number.isFinite(Date.parse(record.created))?new Date(record.created).toISOString():undefined,status:['held','missed','canceled','completed','planned'].includes(String(n.outcome).toLowerCase())?String(n.outcome).toLowerCase():undefined,sourceOutcome:n.outcome,version:(old?.version||0)+1,fubId:id,sourceSystem:'fub-local-fixture'});return}
 if(kind==='deals'){const dealOwner=record.ownerId!=null?activeOwner(resolveUser(record.ownerId)):owner;const deal={id:`fub-local-deals-${id}`,...normalizeDeal(ORG,contact.id,dealOwner.id,{...record,id}),sourceSystem:'fub-local-fixture'};putRecord('fub_deals',deal);projectFubDeal(dealOwner,contact,deal);return}
 const timestamp=record.occurred||record.created;const engagementKinds:Record<string,ActivityDraft['kind']>={'Viewed Property':'property_view','Saved Property':'property_saved','Registration':'registration','Inquiry':'inquiry','Property Inquiry':'inquiry','General Inquiry':'inquiry',open:'em_open',click:'em_click'};const engagement=(kind==='events'||kind==='emEvents')&&timestamp&&Number.isFinite(Date.parse(timestamp))?{organizationId:ORG,personId:contact.id,userId:resolveUser(record.userId),sourceSystem:'fub',metadata:{},kind:engagementKinds[record.type]||'other' as const,direction:'inbound' as const,occurredAt:new Date(timestamp).toISOString(),summary:`Recorded ${String(record.type||'engagement').slice(0,100)}`,fubResourceType:kind,fubResourceId:id}:null;const activity=engagement|| (kind==='calls'?normalizeCall(ORG,contact.id,resolveUser(record.userId),{...record,id}):kind==='emails'?normalizeEmail(ORG,contact.id,resolveUser(record.userId),{...record,id}):kind==='textMessages'?normalizeTextMessage(ORG,contact.id,resolveUser(record.userId),{...record,id}):null);if(!activity)throw new Error(`Resource ${kind} needs a verified normalizer; retained queued evidence, no invented activity`);putRecord('fub_activity',{id:`${ORG}:${kind}:${id}`,...activity});const activities=readRecords<ActivityDraft&{id:string}>('fub_activity').filter(v=>v.organizationId===ORG&&v.personId===contact.id);const derived=deriveTimestamps(activities,contact);const timeline=activities.map(v=>({at:v.occurredAt,kind:v.kind==='text'?'sms':v.kind==='em_open'?'email_open':v.kind==='em_click'?'link_click':v.kind,direction:v.direction==='inbound'?'in':v.direction==='outbound'?'out':'system',label:v.summary||v.kind,fubActivityId:v.id}));putRecord('contacts',{...contact,...derived,version:contact.version+1,timeline:[...contact.timeline.filter(v=>!(v as any).fubActivityId),...timeline]})}
function tombstone(kind:string,id:number,event:FubDelivery){const oldTombstone=getRecord<{deletedAt:string}>('fub_tombstones',`${ORG}:${kind}:${id}`);const deletedAt=[event.eventCreated,oldTombstone?.deletedAt||''].sort().at(-1)!;putRecord('fub_tombstones',{id:`${ORG}:${kind}:${id}`,organizationId:ORG,kind,resourceId:id,eventId:event.id,deletedAt});const collection=kind==='people'?'contacts':kind==='tasks'?'tasks':kind==='appointments'?'appointments':kind==='deals'?'fub_deals':null;const affected=new Set<string>();if(collection){const rid=kind==='people'?personId(id):`fub-local-${kind}-${id}`;const old=getRecord<any>(collection,rid);if(old){affected.add(rid);putRecord(collection,{...old,sourceDeleted:true,sourceDeletedAt:deletedAt,version:(old.version||0)+1,...(kind==='people'?{tags:[...new Set([...(old.tags||[]),'FUB source deleted — retained local history'])]}:{})})}}for(const collection of ['tasks','appointments','transaction_records'])for(const record of readRecords<any>(collection)){const matches=kind==='people'&&record.contactId===personId(id)||kind==='deals'&&collection==='transaction_records'&&record.fubDealId===id;if(record.organizationId===ORG&&matches){affected.add(record.id);putRecord(collection,{...record,sourceDeleted:true,sourceDeletedAt:deletedAt,version:(record.version||0)+1,...(collection==='transaction_records'?{status:'archived'}:{})})}}for(const notification of readRecords<any>('notifications'))if(notification.organizationId===ORG&&([notification.taskId,notification.appointmentId,notification.resourceId,notification.contactId].some(id=>affected.has(id))||[...affected].some(id=>String(notification.id).includes(':'+id+':'))))putRecord('notifications',{...notification,suppressed:true,reason:'FUB source deleted; retained audit only'})}

export function drainLocalFub(a:PlatformActor,limit=10){ownerOnly(a);if(getRecord<{paused:boolean}>('fub_control',ORG)?.paused)throw new Error('Local worker paused');const selected=transaction(()=>{const now=new Date().toISOString();const rows=readRecords<FubDelivery>('fub_deliveries').filter(j=>j.organizationId===ORG&&((j.state==='queued'&&j.nextAttemptAt<=now)||(j.state==='running'&&(j.leaseUntil||'')<now))).slice(0,Math.max(1,Math.min(limit,25)));return rows.map(j=>putRecord('fub_deliveries',{...j,state:'running' as const,attempts:j.attempts+1,leaseUntil:new Date(Date.now()+60000).toISOString()}))});const results=[];for(const job of selected){try{transaction(()=>{const {kind,deleted}=eventRoute(job.event);for(const id of job.resourceIds){if(deleted){tombstone(kind,id,job);continue}const fixture=getRecord<Fixture>('fub_fixtures',`${ORG}:${kind}:${id}`);if(!fixture)throw new Error(`Authoritative local fixture unavailable: ${kind}/${id}. No FUB network request attempted.`);project(kind,fixture.record,job.eventCreated)}const completedAt=new Date().toISOString();putRecord('fub_deliveries',{...job,state:'completed',completedAt,error:undefined});putRecord('fub_checkpoints',{id:`${ORG}:${kind}`,organizationId:ORG,resource:kind,eventId:job.id,eventCreated:[job.eventCreated,getRecord<{eventCreated:string}>('fub_checkpoints',`${ORG}:${kind}`)?.eventCreated||''].sort().at(-1),completedAt,coverage:'local synthetic fixture records only'})});results.push({id:job.id,state:'completed'})}catch(e){const failed={...job,state:job.attempts>=5?'failed' as const:'queued' as const,error:(e as Error).message,nextAttemptAt:new Date(Date.now()+Math.min(3600000,2**job.attempts*1000)).toISOString()};putRecord('fub_deliveries',failed);results.push({id:job.id,state:failed.state,error:failed.error})}}return results}
export function retryLocalFub(a:PlatformActor,id:string){ownerOnly(a);const job=getRecord<FubDelivery>('fub_deliveries',id);if(!job||job.organizationId!==a.organizationId||!['queued','failed'].includes(job.state))throw new Error('Retryable local delivery not found');return putRecord('fub_deliveries',{...job,state:'queued',nextAttemptAt:new Date().toISOString(),error:undefined})}
export function setFubPaused(a:PlatformActor,paused:boolean){ownerOnly(a);return putRecord('fub_control',{id:ORG,organizationId:ORG,paused,updatedAt:new Date().toISOString()})}
export function fubSummary(a:PlatformActor){ownerOnly(a);const deliveries=readRecords<FubDelivery>('fub_deliveries').filter(j=>j.organizationId===a.organizationId);return {agents:directory(a.organizationId).filter(p=>p.role==='agent'&&!p.disabled).map(p=>({id:p.id,name:p.name,market:p.market})),mode:'local-protocol-fixtures',connected:false,externalWrites:false,webhookConfigured:!!process.env.RCRE_FUB_LOCAL_TEST_KEY,paused:!!getRecord<{paused:boolean}>('fub_control',ORG)?.paused,counts:{queued:deliveries.filter(j=>j.state==='queued').length,running:deliveries.filter(j=>j.state==='running').length,failed:deliveries.filter(j=>j.state==='failed').length,completed:deliveries.filter(j=>j.state==='completed').length,duplicates:deliveries.reduce((n,j)=>n+j.duplicates,0)},lastSuccess:deliveries.filter(j=>j.completedAt).map(j=>j.completedAt!).sort().at(-1)||null,deliveries:deliveries.slice(-50),checkpoints:readRecords<{organizationId:string}>('fub_checkpoints').filter(c=>c.organizationId===a.organizationId),dependency:'Production FUB remains disconnected. Explicit sandbox/production authorization, account/system credentials, approved field ownership and webhook registration required.'}}
export function enqueueSyntheticFub(a:PlatformActor,input:{eventId:string;event:string;resourceIds:number[]}){ownerOnly(a);const localKey=process.env.RCRE_FUB_LOCAL_TEST_KEY;if(!localKey)throw new Error('Set RCRE_FUB_LOCAL_TEST_KEY in the private local environment first');const raw=JSON.stringify({...input,eventCreated:new Date().toISOString()});return ingestLocalFub(raw,computeFubSignature(raw,localKey),localKey)}

export async function reconcileLocalFub(a:PlatformActor,restart=false){ownerOnly(a);if(getRecord<{paused:boolean}>('fub_control',ORG)?.paused)throw new Error('Local worker paused');const resources:BackfillResource[]=['users','teams','stages','pipelines','people','tasks','appointments','deals','calls','textMessages','emails','events'];if(restart)for(const row of readRecords<SyncStateRow&{id:string}>('fub_backfill_state').filter(s=>s.organizationId===ORG))putRecord('fub_backfill_state',{...row,lastCursor:null,lastOffset:null,backfillStatus:'pending',recordsSeen:0});const report=await runBackfill({organizationId:ORG,resources,pageLimit:25,client:{async getPage(path,query){const kind=path.slice(1);const rows=readRecords<Fixture>('fub_fixtures').filter(f=>f.organizationId===ORG&&f.kind===kind&&(!query.personId||f.record.personId===query.personId)).sort((a,b)=>a.resourceId-b.resourceId);const offset=Number(query.next||0);return {items:rows.slice(offset,offset+25).map(f=>f.record),next:offset+25<rows.length?String(offset+25):null,rateLimit:{remaining:250,windowSeconds:10}}}},store:{async load(resource){return getRecord<SyncStateRow>('fub_backfill_state',`${ORG}:${resource}`)},async save(row){putRecord('fub_backfill_state',{id:`${ORG}:${row.resource}`,...row})}},async sink(resource,items){transaction(()=>{for(const row of items)project(resource,row as Record<string,any>,new Date().toISOString())})},async personIds(){return readRecords<Fixture>('fub_fixtures').filter(f=>f.organizationId===ORG&&f.kind==='people').map(f=>f.resourceId)},now:()=>new Date().toISOString(),sleep:async()=>{},shouldStop:()=>!!getRecord<{paused:boolean}>('fub_control',ORG)?.paused});putRecord('fub_reconciliation',{id:randomUUID(),organizationId:ORG,at:new Date().toISOString(),report,mode:'local fixtures; no network requests'});return report}
