import {randomUUID} from 'node:crypto'
import {getRecord,putRecord,readRecords,deleteRecord,transaction} from '@/lib/platform/store'
import {guides,articles,communities,publicAgents,publicRoutes} from '@/lib/public/content'
import {publishedPages,archivedPublicPaths,resolvePublicProfile,getLender} from '@/lib/public/server'
import {metroArticles,metroJournals,metroRoutes} from '@/lib/public/metro-journal'
export type PublicSource={title:string;href:string;text:string}
export type PublicChatMessage={id:string;prompt:string;answer:string;mode:'guide'|'ai';state:'pending'|'complete'|'failed';error?:string;sources:PublicSource[];at:string}
type Chat={id:string;generation:string;messages:PublicChatMessage[];updatedAt:string}
const MAX_AGE=30*86400000
const inflight=new Map<string,AbortController>()
// The public site uses deterministic retrieval until it can share the approved
// server-side openrouter/free boundary. Ignore local or alternate model settings.
export function publicChatConfig(){return {model:'',enabled:false as const}}
export function publicChatCookieSecure(){return process.env.NODE_ENV==='production'}
export function publicChatHistory(visitor:string):Chat{const old=getRecord<Chat>('public_chat',visitor);if(old&&Date.parse(old.updatedAt)<=Date.now()-MAX_AGE)deleteRecord('public_chat',visitor);const row=old&&Date.parse(old.updatedAt)>Date.now()-MAX_AGE?old:{id:visitor,generation:randomUUID(),messages:[],updatedAt:new Date().toISOString()};return {...row,messages:row.messages.map(m=>m.state==='pending'&&!inflight.has(visitor)?{...m,state:'failed',error:'The local request was interrupted. Retry when ready.'}:m)}}
export function clearPublicChat(visitor:string){inflight.get(visitor)?.abort();const row={id:visitor,generation:randomUUID(),messages:[],updatedAt:new Date().toISOString()};putRecord('public_chat',row);return row}
function limit(visitor:string){transaction(()=>{const window=Math.floor(Date.now()/60000);for(const row of readRecords<{id:string}>('public_chat_rate')){const minute=Number(row.id.split(':').at(-1));if(Number.isFinite(minute)&&minute<window-1)deleteRecord('public_chat_rate',row.id)}for(const [id,cap] of [[`visitor:${visitor}`,8],['site',60]] as const){const key=`${id}:${window}`;const r=getRecord<{id:string;count:number}>('public_chat_rate',key)||{id:key,count:0};if(r.count>=cap)throw new Error('Please wait a minute before sending another question.');putRecord('public_chat_rate',{...r,count:r.count+1})}})}
export async function publicKnowledge():Promise<PublicSource[]>{const archived=new Set(await archivedPublicPaths());const base:PublicSource[]=[{title:'Find an RCRE agent',href:'/team',text:'Meet RCRE real estate agents serving Alabama and Florida.'},{title:'Alabama real estate',href:'/markets/alabama',text:'Explore Alabama communities and connect with an RCRE professional.'},{title:'Florida real estate',href:'/markets/florida',text:'Explore Florida communities and connect with an RCRE professional.'},{title:'Search homes',href:'/home-search/listings',text:'Explore the local property search. Verify property details and current availability with your agent.'},{title:'Contact RCRE',href:'/contact',text:'Contact the RCRE team to discuss buying, selling, or a move.'},...metroJournals.map(m=>({title:m.name+' journal',href:'/blog/metros/'+m.slug,text:m.description+' '+m.evidenceNote})),...[...articles,...metroArticles].map(a=>({title:a.title,href:'/blog/'+a.slug,text:[a.description,...a.sections.map(s=>s.title+'. '+s.text)].join('\n')})),...guides.map(g=>({title:g.title,href:'/'+g.slug,text:[g.description,...g.sections.map(s=>s.title+'. '+s.text)].join('\n')})),...communities.map(c=>({title:c.name,href:'/neighborhoods/'+c.slug,text:JSON.stringify(c)})),...publicAgents.flatMap(a=>{const p=resolvePublicProfile('/agent/'+a.slug);return p?[{title:p.name,href:'/agent/'+a.slug,text:`${p.name}. ${p.market}. ${p.bio}. Public contact: ${p.phone}; ${p.email}`}]:[]})];const l=await getLender();base.push({title:'Preferred lender · '+l.name,href:'/financing',text:`${l.name}. Phone ${l.phone}. Email ${l.email}. Individual NMLS ${l.individualNmls}; company NMLS ${l.companyNmls}. You may choose any lender. Financing is subject to qualification and approval; this chat does not provide lending approval or rates.`});const published=await publishedPages();const redirects=new Set(published.filter(p=>p.published?.redirectTo).map(p=>p.id));for(const p of published){if(redirects.has(p.id)||!(publicRoutes.includes(p.id)||metroRoutes.includes(p.id)||/^\/(blog|resources|pages)\/[a-z0-9]+(?:[a-z0-9/-]*[a-z0-9])?$/.test(p.id)))continue;const v=p.published!;const i=base.findIndex(b=>b.href===p.id);const row={title:v.title,href:p.id,text:v.description+'\n'+v.body};if(i>=0)base[i]=row;else base.push(row)}return base.filter(b=>!archived.has(b.href)&&!redirects.has(b.href)).map(b=>({...b,text:b.text.slice(0,12000)}))}
function relevant(prompt:string,all:PublicSource[]){const stop=new Set(['the','and','for','which','with','that','what','where','can','could','would','about','are','have','has','how','your','you']);const terms=(prompt.toLowerCase().match(/[a-z0-9]{3,}/g)||[]).filter(t=>!stop.has(t));const score=(s:PublicSource)=>terms.reduce((n,t)=>n+(s.title.toLowerCase().includes(t)?8:0)+(s.text.toLowerCase().includes(t)?1:0)+(s.href.includes(t)?4:0),0);const ranked=all.map(s=>({s,n:score(s)})).filter(r=>r.n>0).sort((a,b)=>b.n-a.n);return (ranked.length?ranked.slice(0,4).map(r=>r.s):all.filter(s=>['/team','/buying','/selling','/contact'].includes(s.href))).slice(0,4)}
export async function askPublicChat(visitor:string,prompt:string,retryId?:string){if(inflight.has(visitor))throw new Error('A response is already in progress.');const old=publicChatHistory(visitor);if(retryId){const retry=old.messages.find(m=>m.id===retryId);if(!retry)throw new Error('That question is not in this visitor history.');prompt=retry.prompt}prompt=prompt.trim();if(!prompt||prompt.length>1200)throw new Error('Enter a question of 1–1200 characters.');limit(visitor);const controller=new AbortController();inflight.set(visitor,controller);const message:PublicChatMessage={id:randomUUID(),prompt,answer:'',mode:'guide',state:'pending',sources:[],at:new Date().toISOString()};const row={...old,messages:[...old.messages.slice(-19),message],updatedAt:new Date().toISOString()};putRecord('public_chat',row);try{message.sources=relevant(prompt,await publicKnowledge());message.answer='Site guide — these published RCRE pages may help:\n\n'+message.sources.map(s=>s.title+'\n'+s.text.slice(0,200)+(s.text.length>200?'…':'')).join('\n\n');message.state='complete'}catch{message.state='failed';message.error=controller.signal.aborted?'Request canceled.':'The site guide is temporarily unavailable. Open a published page below or retry.';message.answer=''}finally{if(inflight.get(visitor)===controller)inflight.delete(visitor)}const latest=getRecord<Chat>('public_chat',visitor);if(latest?.generation===row.generation){putRecord('public_chat',{...row,messages:row.messages.map(m=>m.id===message.id?message:m),updatedAt:new Date().toISOString()})}return publicChatHistory(visitor)}
