import {getSetting} from '../platform/service'
import { randomUUID, createHash } from 'node:crypto'
import { readRecords, getRecord, putRecord, transaction } from '@/lib/platform/store'
import { PERSONAS } from '@/lib/platform/auth'
import type { PlatformActor } from '@/lib/platform/auth'
import { calculateDeadline, type DeadlineTerm } from './deadlines'
export interface TransactionRecord {id:string; organizationId:string; ownerId:string; officeId:string; teamId:string; tcId:string; market:string; address:string; representation:'buyer'|'seller'|'unknown'; client:string; lender:string; title:string; closingDate:string; status:'active'|'pending_signature'|'closed'|'archived'; version:number; deadlines:DeadlineTerm[]; checklist:{id:string;label:string;done:boolean}[]; comments:{id:string;author:string;body:string;at:string}[]; updatedAt:string;sourceDeleted?:boolean;contactId?:string;fubDealId?:number;sourceSystem?:string;sourceDetails?:{title:string|null;stage:string|null;status:string|null;projectedClosingDate:string|null;recordedClosedAt:string|null;contractTerms:string}}
export interface DocumentRecord {id:string;transactionId:string;name:string;mime:string;base64:string;version:number;sha256:string;createdAt:string;ownerId:string;organizationId:string;scanStatus:'synthetic_unscanned';text:string}
export interface InspectionDraft {id:string;transactionId:string;organizationId:string;ownerId:string;body:string;version:number;sourceDocumentId:string;sourceHash:string;items:{number:number;passage:string}[];state:'drafted'|'awaiting_approval'|'completed_locally';approval?:{actorId:string;hash:string;version:number;expiresAt:string;consumedAt:string};createdAt:string;reviewExpiresAt?:string}
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex')
export function permitted(a:PlatformActor,t:TransactionRecord) {return t.organizationId===a.organizationId && (a.role==='broker_owner'||(a.role==='managing_broker'&&t.officeId===a.officeId)||(a.role==='team_leader'&&t.teamId===a.teamId)||t.ownerId===a.userId||t.tcId===a.userId)}
export function ensureTransactions(a:PlatformActor) {if(!['agent','team_leader','managing_broker','broker_owner','transaction_coordinator'].includes(a.role))throw new Error('Transaction access denied')}
export function listTransactions(a:PlatformActor) {ensureTransactions(a);seedTransactions(); return readRecords<TransactionRecord>('transaction_records').filter(t=>!t.sourceDeleted&&permitted(a,t)).sort((x,y)=>nextDeadline(x).localeCompare(nextDeadline(y)))}
export function nextDeadline(t:TransactionRecord) {return t.deadlines.map(d=>calculateDeadline(d).date).filter((d):d is string=>!!d).sort()[0]||'9999'}
export function requireTransaction(a:PlatformActor,id:string) {ensureTransactions(a);const t=getRecord<TransactionRecord>('transaction_records',id);if(!t||!permitted(a,t))throw new Error('Transaction not found or access denied');return t}
export function createTransaction(a:PlatformActor,input:Partial<TransactionRecord>) {ensureTransactions(a);if(!input.address?.trim()||!input.client?.trim())throw new Error('Property and synthetic client are required');const t:TransactionRecord={id:randomUUID(),organizationId:a.organizationId,ownerId:a.userId,officeId:a.officeId,teamId:a.teamId,tcId:a.role==='transaction_coordinator'?a.userId:'',market:a.market,address:input.address.trim().slice(0,200),client:input.client.trim().slice(0,100),representation:input.representation==='seller'?'seller':'buyer',lender:'',title:'',closingDate:input.closingDate||'',status:'active',version:1,deadlines:[],checklist:[...transactionPolicy(a).checklist,...transactionPolicy(a).documentRequirements.map(label=>`Document: ${label}`)].map(label=>({id:randomUUID(),label,done:false})),comments:[],updatedAt:new Date().toISOString()};return putRecord('transaction_records',t)}
export function updateTransaction(a:PlatformActor,id:string,version:number,patch:Partial<TransactionRecord>) {return transaction(()=>{const t=requireTransaction(a,id);if(t.version!==version)throw new Error('Conflict: refresh to review the latest version');const next={...t};for(const key of ['client','address','lender','title','closingDate','status','deadlines','checklist'] as const)if(patch[key]!==undefined)Object.assign(next,{[key]:patch[key]});putRecord('transaction_history',{id:randomUUID(),transactionId:id,organizationId:a.organizationId,actorId:a.userId,version:t.version,snapshot:t,at:new Date().toISOString()});next.version++;next.updatedAt=new Date().toISOString();return putRecord('transaction_records',next)})}
export function addComment(a:PlatformActor,id:string,body:string) {if(!body.trim()||body.length>4000)throw new Error('Comment must contain 1–4000 characters');return transaction(()=>{const t=requireTransaction(a,id);t.comments.push({id:randomUUID(),body,author:a.name,at:new Date().toISOString()});t.version++;t.updatedAt=new Date().toISOString();return putRecord('transaction_records',t)})}
export function documents(a:PlatformActor,id:string) {requireTransaction(a,id);return readRecords<DocumentRecord>('document_records').filter(d=>d.transactionId===id)}
export function uploadDocument(a:PlatformActor,id:string,name:string,mime:string,bytes:Buffer,replaceId?:string) {requireTransaction(a,id);if(bytes.length===0||bytes.length>5*1024*1024)throw new Error('Use a synthetic PDF or plain text file up to 5 MB');if(!['application/pdf','text/plain'].includes(mime))throw new Error('Only PDF and plain text files are accepted');if(mime==='application/pdf'&&bytes.subarray(0,5).toString()!=='%PDF-')throw new Error('Invalid PDF header');const old=replaceId?documents(a,id).find(d=>d.id===replaceId):null;if(replaceId&&!old)throw new Error('Document version not found');const d:DocumentRecord={id:randomUUID(),transactionId:id,name:name.replace(/[^\w. -]/g,'_').slice(0,120),mime,base64:bytes.toString('base64'),version:old?old.version+1:1,sha256:createHash('sha256').update(bytes).digest('hex'),createdAt:new Date().toISOString(),ownerId:a.userId,organizationId:a.organizationId,scanStatus:'synthetic_unscanned',text:mime==='text/plain'?bytes.toString('utf8'):''};return putRecord('document_records',d)}
export function drafts(a:PlatformActor,id:string) {requireTransaction(a,id);return readRecords<InspectionDraft>('transaction_drafts').filter(d=>d.transactionId===id)}
export function saveDraft(a:PlatformActor,id:string,input:{id?:string;version?:number;documentId:string;numbers:number[];body?:string}) {return transaction(()=>{const t=requireTransaction(a,id);const doc=documents(a,id).find(d=>d.id===input.documentId);if(!doc?.text)throw new Error('Select a plain text report. PDF extraction requires a verified processing service.');const passages=doc.text.split(/\r?\n/).map(line=>{const m=line.match(/^\s*(\d+)[.)]\s+(.+)$/);return m?{number:Number(m[1]),passage:m[2]}:null}).filter((v):v is {number:number;passage:string}=>!!v);const items=passages.filter(i=>input.numbers.includes(i.number));if(!items.length)throw new Error('Select at least one numbered source item');const old=input.id?drafts(a,id).find(d=>d.id===input.id):null;if(input.id&&(!old||old.version!==input.version))throw new Error('Draft version conflict');const d:InspectionDraft={id:old?.id||randomUUID(),transactionId:id,organizationId:a.organizationId,ownerId:a.userId,body:input.body||`Please review the following inspection observations for ${t.address}. These are source excerpts for coordination, not proposed contract terms or legal remedies.\n\n${items.map(i=>`${i.number}. ${i.passage}`).join('\n')}\n\nPlease confirm the appropriate next steps with the responsible licensed professional.`,version:(old?.version||0)+1,sourceDocumentId:doc.id,sourceHash:doc.sha256,items,state:'drafted',createdAt:new Date().toISOString()};return putRecord('transaction_drafts',d)})}
export function reviewDraft(a:PlatformActor,id:string,draftId:string,version:number,action:'submit'|'approve') {return transaction(()=>{requireTransaction(a,id);const d=drafts(a,id).find(v=>v.id===draftId);if(!d||d.version!==version)throw new Error('Draft version changed; review again');if(action==='submit'){if(d.state==='completed_locally')throw new Error('Already recorded');d.state='awaiting_approval';d.reviewExpiresAt=new Date(Date.now()+transactionPolicy(a).reviewHours*3600000).toISOString()}else{const owners=String(getSetting(a,'brokerage').value.documentOwners??'').split(',').map(s=>s.trim()).filter(Boolean);if(owners.length&&!owners.includes(a.id))throw new Error('Brokerage policy requires a designated document reviewer');if(d.state!=='awaiting_approval'||d.approval?.consumedAt)throw new Error('Approval is not pending or was already consumed');if(!d.reviewExpiresAt||Date.parse(d.reviewExpiresAt)<=Date.now())throw new Error('Review expired; revise and submit again');if(transactionPolicy(a).separateReviewer&&d.ownerId===a.userId)throw new Error('Policy requires a different authorized reviewer');const now=new Date().toISOString();d.approval={actorId:a.userId,hash:hash(d.body),version:d.version,expiresAt:new Date(Date.now()+86400000).toISOString(),consumedAt:now};d.state='completed_locally';putRecord('transaction_outbox',{id:randomUUID(),transactionId:id,organizationId:a.organizationId,ownerId:a.userId,draftId:d.id,version:d.version,body:d.body,payloadHash:hash(d.body),approvedBy:a.userId,createdAt:now,status:'completed_locally',recipient:'Assigned transaction coordinator — local review outbox only'})}return putRecord('transaction_drafts',d)})}

export function seedTransactions(){transaction(()=>{if(getRecord('transaction_seed','v1'))return;for(const ownerId of ['u-sarah','u-vito']){const a=PERSONAS.find(p=>p.id===ownerId)!;const t=createTransaction(a,{address:ownerId==='u-sarah'?'100 Demonstration Lane, Jacksonville':'200 Example Avenue, Birmingham',client:ownerId==='u-sarah'?'Jamie Example (synthetic)':'Taylor Sample (synthetic)',representation:'buyer',closingDate:'2026-10-02'});t.tcId=ownerId==='u-sarah'?'u-tc':'';t.deadlines=[{id:randomUUID(),label:'Inspection review',sourceTerm:'Synthetic demonstration contract, section 8: ten calendar days after effective date. Not a state template.',effectiveDate:'2026-09-08',days:10,convention:'calendar',timezone:ownerId==='u-sarah'?'America/New_York':'America/Chicago',holidays:[],confirmed:true}];putRecord('transaction_records',t);uploadDocument(a,t.id,'synthetic-inspection.txt','text/plain',Buffer.from('1. Kitchen sink: slow drip observed at supply connection.\n2. Roof: loose flashing observed above rear porch.\n3. Garage: safety reverse sensor did not respond during test.'))}putRecord('transaction_seed',{id:'v1'})})}
export function assignTransaction(a:PlatformActor,id:string,ownerId:string,tcId:string){return transaction(()=>{const t=requireTransaction(a,id);if(!['broker_owner','managing_broker','team_leader'].includes(a.role))throw new Error('Assignment access denied');const owner=PERSONAS.find(p=>p.id===ownerId&&p.role==='agent'&&p.organizationId===a.organizationId);const tc=tcId?PERSONAS.find(p=>p.id===tcId&&p.role==='transaction_coordinator'&&p.organizationId===a.organizationId):null;if(!owner||(a.role!=='broker_owner'&&owner.officeId!==a.officeId)||(tcId&&(!tc||tc.officeId!==owner.officeId)))throw new Error('Assignment is outside authorized scope');putRecord('transaction_assignment_history',{id:randomUUID(),transactionId:id,organizationId:a.organizationId,actorId:a.userId,fromOwner:t.ownerId,toOwner:owner.id,fromTC:t.tcId,toTC:tc?.id||'',at:new Date().toISOString()});return putRecord('transaction_records',{...t,ownerId:owner.id,officeId:owner.officeId,teamId:owner.teamId,tcId:tc?.id||'',version:t.version+1,updatedAt:new Date().toISOString()})})}
export interface TransactionPolicy {id:string;organizationId:string;officeId:string;version:number;checklist:string[];documentRequirements:string[];reviewHours:number;separateReviewer:boolean;retentionNote:string}
export function transactionPolicy(a:PlatformActor):TransactionPolicy{ensureTransactions(a);return getRecord<TransactionPolicy>('transaction_policies',`${a.organizationId}:${a.officeId}`)||getRecord<TransactionPolicy>('transaction_policies',`${a.organizationId}:all`)||{id:`${a.organizationId}:${a.officeId}`,organizationId:a.organizationId,officeId:a.officeId,version:1,checklist:['Earnest money','Inspection','Appraisal','Financing','Title','HOA / condominium review','Insurance','Closing preparation','Post closing'],documentRequirements:['Executed agreement','Inspection report','Closing statement'],reviewHours:24,separateReviewer:false,retentionNote:'Retention policy requires brokerage approval; no automatic deletion enabled.'}}
export function saveTransactionPolicy(a:PlatformActor,input:Omit<TransactionPolicy,'id'|'organizationId'|'officeId'>){if(!['broker_owner','managing_broker','team_leader'].includes(a.role))throw new Error('Policy access denied');return transaction(()=>{const old={...transactionPolicy(a),id:`${a.organizationId}:${a.officeId}`,officeId:a.officeId};if(old.version!==input.version)throw new Error('Policy changed; refresh');return putRecord('transaction_policies',{...old,...input,version:old.version+1})})}

/** A source deal and local coordination record share one stable ID. No contract terms are inferred. */
export function projectFubDeal(a:PlatformActor,contact:{id:string;firstName:string;lastName:string},deal:{fubDealId:number;name:string|null;stage:string|null;status:string|null;projectedCloseOn:string|null;closedAt:string|null}){return transaction(()=>{const id=`fub-local-deal-${deal.fubDealId}`;const old=getRecord<TransactionRecord>('transaction_records',id);const policy=transactionPolicy(a);const record={...old,id,organizationId:a.organizationId,ownerId:a.userId,officeId:a.officeId,teamId:a.teamId,tcId:old?.tcId||'',market:a.market,address:old?.address||`Property details unconfirmed · ${deal.name||`FUB deal ${deal.fubDealId}`}`,client:`${contact.firstName} ${contact.lastName}`,representation:old?.representation||'unknown',lender:old?.lender||'',title:old?.title||'',closingDate:old?.closingDate||'',status:old?.status||'active',version:(old?.version||0)+1,deadlines:old?.deadlines||[],checklist:old?.checklist||['Confirm property and representation','Confirm signed agreement and effective date',...policy.checklist,...policy.documentRequirements.map(v=>`Document: ${v}`)].map(label=>({id:randomUUID(),label,done:false})),comments:old?.comments||[],updatedAt:new Date().toISOString(),contactId:contact.id,fubDealId:deal.fubDealId,sourceSystem:'fub-local-fixture',sourceDeleted:false,sourceDetails:{title:deal.name,stage:deal.stage,status:deal.status,projectedClosingDate:deal.projectedCloseOn,recordedClosedAt:deal.closedAt,contractTerms:'Unconfirmed — no deadline calculated from CRM stage or projected closing date'}};return putRecord('transaction_records',record)})}
