export type CinematicPhoto={src:string;alt:string;credit:string;sourceUrl:string;licenseUrl:string;sceneNote:string}
const licenseUrl='https://unsplash.com/license'
export const cinematicPhotos:Record<'living'|'kitchen'|'planning'|'coast'|'bedroom'|'entry',CinematicPhoto>={
 living:{src:'/brand/cinematic/blog-living.webp',alt:'Sunlit living room with a gray sofa, teal cushions, and a wooden coffee table',credit:'Nathan Fertig / Unsplash',sourceUrl:'https://unsplash.com/photos/brown-and-white-wooden-table-beside-sofa-chair-FBXuXp57eM0',licenseUrl,sceneNote:'Editorial interior photograph in Wooster, United States, 2017. Not an RCRE listing or a represented local property.'},
 kitchen:{src:'/brand/cinematic/blog-kitchen.webp',alt:'Bright modern kitchen with a central island, stools, and stainless steel appliances',credit:'Clay Banks / Unsplash',sourceUrl:'https://unsplash.com/photos/modern-kitchen-with-island-and-stainless-steel-appliances-J77Yzq9_Hcg',licenseUrl,sceneNote:'Editorial interior photograph in North Branch, New York, 2026. Not an RCRE listing or a represented local property.'},
 planning:{src:'/brand/cinematic/blog-planning.webp',alt:'Open lined notebook and a green pen on a warmly lit wooden desk',credit:'Clay Banks / Unsplash',sourceUrl:'https://unsplash.com/photos/open-notebook-with-pen-and-pencils-on-desk-n9AaeihA9HI',licenseUrl,sceneNote:'Editorial planning photograph in Callicoon, New York, 2025. No customer information or transaction documents are depicted.'},
 coast:{src:'/brand/cinematic/blog-coast.webp',alt:'Overhead photograph of deep blue ocean water and white breaking waves',credit:'Enrapture Captivating Media / Unsplash',sourceUrl:'https://unsplash.com/photos/aerial-photography-of-ocean-waves-nlwJDqiLQYE',licenseUrl,sceneNote:'Editorial ocean photograph at Vazon, Guernsey, 2017. This is not a Florida location or evidence about a property’s flood exposure.'},
 bedroom:{src:'/brand/cinematic/blog-bedroom.webp',alt:'Staged bedroom with gray walls, a large bed, hardwood floors, and a patterned rug',credit:'Francesca Tosolini / Unsplash',sourceUrl:'https://unsplash.com/photos/bedroom-with-dark-grey-walls-hCU4fimRW-c',licenseUrl,sceneNote:'Editorial real estate interior photograph, published 2019; location not established by the source page. Not an RCRE listing or a represented local property.'},
 entry:{src:'/brand/cinematic/blog-entry.webp',alt:'White historic house with a red front door and picket fence beneath autumn trees',credit:'Scott Webb / Unsplash',sourceUrl:'https://unsplash.com/photos/white-house-under-maple-trees-1ddol8rgUH8',licenseUrl,sceneNote:'Editorial historic house photograph at Fanshawe Pioneer Village, London, Canada, 2016. Not a home offered for sale in Alabama or Florida.'}
}
