export type MetroSource={label:string;url:string}
export type MetroJournal={slug:string;name:string;state:string;description:string;counties:string[];agentSlugs:string[];evidenceNote:string;sources:MetroSource[]}
export type MetroArticle={slug:string;metroSlug:string;title:string;description:string;category:string;readMinutes:number;sections:{title:string;text:string}[];sources:MetroSource[]}
const source=(label:string,path:string):MetroSource=>({label,url:'https://rcregroup.com'+path})
export const metroJournals:MetroJournal[]=[
 {slug:'birmingham',name:'Birmingham & Central Alabama',state:'Alabama',description:'From the first neighborhood shortlist to the final property walkthrough. Practical reading for Birmingham and the surrounding county markets.',counties:['jefferson-county','shelby-county','blount-county','st-clair-county'],agentSlugs:['taquilla-allen','julio-arango','lekeshia-jones','urban-garrett'],evidenceNote:'RCRE’s Alabama team directory and Birmingham office support this regional connection. County pages describe brokerage coverage, not a promise that every agent serves every address.',sources:[source('RCRE Alabama team','/team'),source('RCRE county directory','/neighborhoods')]},
 {slug:'jacksonville',name:'Jacksonville & Northeast Florida',state:'Florida',description:'River, coast, and communities in between. Make an informed move across Duval, Clay, St Johns, and Nassau counties.',counties:['duval-county','clay-county','st-johns-county','nassau-county'],agentSlugs:['alex-verastegui','delonda-allen','margie-olsen-alvarez','molly-plude','vito-lombardo','johann-velez','sarah-brockner'],evidenceNote:'These source biographies or profile locations identify Jacksonville, Northeast Florida, North Florida, or Ponte Vedra connections. Discuss address-specific representation and availability directly with the team.',sources:[source('RCRE neighborhood coverage','/neighborhoods'),source('Margie’s Northeast Florida biography','/agent/margie-olsen-alvarez'),source('Vito’s Ponte Vedra focus','/agent/vito-lombardo')]},
 {slug:'south-florida',name:'Miami & Fort Lauderdale',state:'Florida',description:'A closer look at property decisions in Miami-Dade and Broward. Start with the building, the documents, and the way you want to live.',counties:['miami-dade-county','broward-county'],agentSlugs:[],evidenceNote:'Miami-Dade and Broward are current RCRE neighborhood pages. The public roster does not establish a specific agent’s current South Florida base. Ask the brokerage to confirm the appropriate professional. Historical sales alone do not establish current agent coverage.',sources:[source('RCRE Miami-Dade coverage','/neighborhoods/miami-dade-county'),source('RCRE Broward coverage','/neighborhoods/broward-county'),source('RCRE team and historical transactions','/team')]}
]
const articles:Omit<MetroArticle,'sources'|'readMinutes'>[]=[
 {slug:'birmingham-neighborhood-shortlist',metroSlug:'birmingham',title:'Build a Birmingham shortlist around your actual week',description:'A practical way to compare Jefferson, Shelby, Blount, and St Clair without letting county-wide labels make the decision.',category:'Buying',sections:[
 {title:'Begin with three real destinations',text:'Before collecting favorite homes, write down the places you visit most often and when you need to be there. Include any regular evening or weekend commitments. Use those destinations to plan a first set of property visits. RCRE’s county directory spans Jefferson, Shelby, Blount, and St Clair; that is a starting geography, not a substitute for comparing the actual trip from each home.'},
 {title:'Tour the route as well as the house',text:'A good visit gives you two kinds of information: how the property works and how the location fits your routine. Travel your likely route at a representative time, then note parking, access, and the arrival experience. Compare what you observed using the same checklist for each address. Avoid treating a single unusually easy drive as the normal journey.'},
 {title:'Separate the address from the marketing label',text:'Record the property’s actual jurisdiction and ask which documents confirm taxes, utility arrangements, restrictions, and other recurring responsibilities. If school assignments matter to your search, verify them directly through the relevant district using the address. A subdivision name, postal city, or county-level statistic does not settle those questions.'},
 {title:'Bring back a usable shortlist',text:'Choose a few homes that meet the same basic requirements. For each, keep a short list of confirmed facts, open questions, and costs needing a quote. Discuss that list with your agent before changing the search. This makes it easier to tell whether you need a different location, a different property type, or simply better information about the homes already in front of you.'}]},
 {slug:'birmingham-seller-preparation',metroSlug:'birmingham',title:'Before the photographs: prepare your Birmingham home for a useful first impression',description:'Organize condition, paperwork, and access before deciding which cosmetic changes deserve your time.',category:'Selling',sections:[
 {title:'Start with a walkthrough, not a shopping list',text:'Walk through the property with your agent and separate maintenance concerns from presentation choices. Discuss what a buyer will need to understand about the home’s condition. A fresh visual presentation cannot answer a question about a roof, system, or past repair. The right preparation depends on the property, competing homes, and your timeline rather than a universal renovation formula.'},
 {title:'Make the paperwork easy to find',text:'Gather the records you already have: service invoices, warranties, improvement information, association contacts, and documents related to known work. Identify missing records early. Keep sensitive personal information out of a public marketing folder. Your agent can help identify which materials belong in a controlled transaction workspace and which details are useful in a property presentation.'},
 {title:'Plan for real showing conditions',text:'Think through the practical experience of arriving, entering, and moving through the home. Agree on how much notice you need, when visits work, and how access will be managed. The plan should be workable for your household and clear to the team arranging appointments. Test it before photography and showings begin so that the marketing schedule does not outrun the preparation.'},
 {title:'Review the complete offer',text:'Once offers arrive, place price alongside financing, conditions, requested concessions, dates, and the steps needed to reach closing. Use the same comparison format each time. A headline number alone does not explain the work or uncertainty attached to an offer. Keep the decision grounded in the written terms and obtain the appropriate professional advice for questions beyond your agent’s role.'}]},
 {slug:'jacksonville-river-coast-home-search',metroSlug:'jacksonville',title:'River, coast, or inland: make a Northeast Florida comparison you can use',description:'Compare the property and ownership questions that matter across the Jacksonville region.',category:'Buying',sections:[
 {title:'Use the region as a starting point',text:'RCRE’s Northeast Florida coverage includes Duval, Clay, St Johns, and Nassau. Begin with the places your routine requires, then consider how far you want to travel for the other parts of your life. A river-area home, a coastal search, and an inland property may all fit different versions of the same budget. Put actual addresses into the comparison before choosing a broad label.'},
 {title:'Ask for address-specific information',text:'For each serious candidate, request the documents and professional quotes relevant to the property. Ask about known condition issues, flood information, insurance, association responsibilities, and any district assessments. Do not assume two homes with similar asking prices carry the same recurring costs. Keep a record of where each number came from and whether it is an estimate or confirmed for that home.'},
 {title:'Bring the journey into the decision',text:'Plan a visit that includes your likely route to work and other regular destinations. Use representative times where possible. Note how the property’s access and layout fit your ordinary day rather than only the experience of a weekend tour. Remote buyers can give their agent a specific walkthrough checklist and request follow-up views of features that matter to them.'},
 {title:'Choose the next question, not just the favorite photo',text:'After touring, identify the uncertainty that would most change your decision. It might be an ownership expense, repair question, association obligation, or route you have not tested. Resolve that issue before expanding the shortlist indefinitely. The goal is a well-supported choice, with your preferences separated from facts that still need confirmation.'}]},
 {slug:'northeast-florida-relocation-calendar',metroSlug:'jacksonville',title:'A calmer relocation starts with one shared calendar',description:'Coordinate a Northeast Florida move around the dates you actually know, with room for the decisions still ahead.',category:'Relocation',sections:[
 {title:'Mark the fixed dates first',text:'Start with confirmed work, travel, current housing, and moving commitments. Separate them from hoped-for dates. Give your agent the timeline and explain which parts are flexible. RCRE’s Northeast Florida biographies include military relocation experience, but each move has its own requirements. A useful plan starts with your situation rather than an assumed standard schedule.'},
 {title:'Build a remote-tour brief',text:'Write down the questions that photographs are unlikely to answer. Include storage, access, room relationships, outdoor maintenance, and features needed for daily routines. Ask for a consistent tour sequence so you can compare homes fairly. Keep a separate place for questions about disclosures, condition, and ownership documents; a video tour is not a substitute for those investigations.'},
 {title:'Give each milestone an owner',text:'Track the next action, who is handling it, and what information is needed. Keep the property search, financing conversation, inspection planning, and move arrangements connected without putting sensitive documents into ordinary inquiry forms. Confirm which dates come from an executed agreement and which are still planning assumptions.'},
 {title:'Keep a contingency conversation open',text:'Ask early what happens if a property does not fit, a closing date changes, or a document takes longer than expected. Consider temporary arrangements only after checking their current terms and availability. Revisit the plan when a material fact changes. An organized relocation does not eliminate uncertainty; it makes the next decision easier to see.'}]},
 {slug:'miami-fort-lauderdale-building-questions',metroSlug:'south-florida',title:'In a South Florida condo search, investigate the building as carefully as the unit',description:'A document-first approach to comparing homes in Miami-Dade and Broward.',category:'Buying',sections:[
 {title:'Create two parallel checklists',text:'One checklist covers the unit: layout, condition, storage, access, and the way you will use the space. The other covers the building and association. RCRE lists Miami-Dade and Broward in its public neighborhood coverage. For a particular property, ask the brokerage to confirm the professional who can help you assemble the relevant information and coordinate the right questions.'},
 {title:'Request the current document package',text:'Ask which association documents, budgets, meeting records, assessments, maintenance information, and applicable reports are available for review. Have the appropriate professionals explain what matters to your proposed purchase. Requirements can depend on the building and transaction, so avoid relying on a generic online summary as a substitute for current documents and qualified advice.'},
 {title:'Compare the whole ownership picture',text:'Put the asking price beside association charges, property taxes, insurance estimates, known assessments, and other costs you have verified. Note the date and source of each figure. Ask what can change and which responsibilities belong to the owner or association. A visually similar unit in another building may come with a different set of obligations.'},
 {title:'Connect the rules to your intended use',text:'Explain how you intend to occupy and use the property. Request the relevant written rules and verify any restrictions that could affect that plan. Do not infer rental permission, parking rights, pet rules, or renovation approval from a listing photograph or a neighboring unit. Resolve those questions before treating a home as a match.'}]},
 {slug:'south-florida-relocation-shortlist',metroSlug:'south-florida',title:'Miami-Dade or Broward? Compare your destinations before comparing headlines',description:'Build a South Florida search around the places, property types, and responsibilities that fit your move.',category:'Relocation',sections:[
 {title:'Choose the anchors of your week',text:'Write down the destinations your move depends on and the times you expect to travel. A county name is too broad to describe that experience. Build an initial search around actual addresses and your preferred property type. RCRE’s South Florida county pages offer a route into the conversation; they do not establish that every agent is based in every community.'},
 {title:'Keep the same comparison sheet',text:'For each candidate, capture space, condition, access, recurring ownership expenses, and open questions. If you are considering both a condominium and a detached home, make the different maintenance responsibilities explicit. Compare verified documents and quotes rather than assuming the lower asking price is the simpler ownership choice.'},
 {title:'Separate past transactions from today’s plan',text:'A brokerage’s historical transactions can show where it has worked. They do not confirm current availability, a particular agent’s location, or the right person for your proposed purchase. Ask who would represent you, how the local work will be handled, and what the communication plan looks like. Get those practical details clear at the start.'},
 {title:'Make the next visit answer something',text:'Design each visit around an unresolved question: the commute, building access, a room’s function, or the surrounding services you personally use. Record what you observed and what still needs independent verification. Bring that list into the next conversation instead of relying on a broad impression of which county ought to fit.'}]}
]
export const metroArticles:MetroArticle[]=articles.map(a=>({...a,readMinutes:Math.max(2,Math.ceil(a.sections.reduce((n,s)=>n+s.text.split(/\s+/).length,0)/200)),sources:metroJournals.find(m=>m.slug===a.metroSlug)!.sources}))
export const metroRoutes=[...metroJournals.map(m=>'/blog/metros/'+m.slug),...metroArticles.map(a=>'/blog/'+a.slug)]

// Explicit editorial geography; a title keyword alone never assigns a custom story.
export const legacyArticleMetro:Record<string,string>={
 'st-johns-countys-fall-season-is-running-on-four-different-clocks-this-year':'jacksonville',
 'duval-countys-insurance-market-is-recovering-older-homes-are-still-being-left-behind':'jacksonville',
 'what-alabamas-buyer-beware-law-means-for-a-jefferson-county-home-inspection':'birmingham',
 'jefferson-countys-trail-network-hit-175-miles-heres-the-part-that-still-isnt-finished':'birmingham',
 'where-duval-countys-fall-2026-restaurant-wave-is-actually-landing':'jacksonville',
 'whats-new-on-the-over-the-mountain-table-this-summer':'birmingham',
 'first-time-homebuyer-steps-in-clay-county':'jacksonville',
 'cdd-vs-hoa-fees-in-clay-county-whats-the-difference':'jacksonville',
 'military-relocation-to-duval-county-housing-guide':'jacksonville',
 'getting-your-clay-county-home-market-ready-this-spring':'jacksonville',
 'understanding-cdd-and-hoa-communities-in-st-johns-county':'jacksonville',
 'clay-county-vs-duval-county-choosing-your-next-home':'jacksonville'
}
type JournalOverride={title:string;description:string;body:string;redirectTo?:string}
export function journalStories(legacy:{slug:string;title:string;description:string;category:string;sections:{title:string;text:string}[]}[],overrides:Record<string,JournalOverride>={},hidden:string[]=[]):MetroArticle[]{
 const rows:MetroArticle[]=[...metroArticles,...legacy.filter(a=>!metroArticles.some(m=>m.slug===a.slug)).map(a=>({...a,metroSlug:legacyArticleMetro[a.slug]||'brokerage',readMinutes:Math.max(2,Math.ceil(a.sections.map(s=>s.text).join(' ').split(/\s+/).length/200)),sources:[]}))];
 for(const [path,p] of Object.entries(overrides)){if(!/^\/blog\/[a-z0-9]+(?:[a-z0-9/-]*[a-z0-9])?$/.test(path)||path.startsWith('/blog/metros/'))continue;const slug=path.slice(6);if(!rows.some(a=>a.slug===slug))rows.push({slug,metroSlug:'brokerage',title:p.title,description:p.description,category:'Brokerage',readMinutes:Math.max(1,Math.ceil(p.body.split(/\s+/).length/200)),sections:[],sources:[]})}
 return rows.filter(a=>!hidden.includes('/blog/'+a.slug)&&!overrides['/blog/'+a.slug]?.redirectTo).map(a=>({...a,title:overrides['/blog/'+a.slug]?.title||a.title,description:overrides['/blog/'+a.slug]?.description||a.description}));
}
