import {describe,it,expect,afterEach,vi} from 'vitest'
import {randomUUID} from 'node:crypto'
import {askPublicChat,clearPublicChat,publicChatHistory,publicKnowledge,publicChatConfig} from '../src/lib/services/public-chat'
import {putRecord,deleteRecord} from '../src/lib/platform/store'
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();for(const id of ['/buying','/selling','/crm/private-secret'])deleteRecord('public_content',id)})
describe('public chat knowledge and visitor boundary',()=>{
 it('uses only published public pages, respects archives, and isolates visitor histories',async()=>{vi.stubEnv('RCRE_PUBLIC_CHAT_MODEL','');putRecord('public_content',{id:'/buying',status:'draft',body:'SECRET DRAFT',published:{title:'Published buying',description:'Approved buying description',body:'APPROVED PUBLIC TEXT'}});putRecord('public_content',{id:'/selling',status:'archived',published:{title:'Archived selling',body:'ARCHIVED SECRET'}});putRecord('public_content',{id:'/crm/private-secret',status:'published',published:{title:'PRIVATE CRM',body:'PRIVATE SECRET'}});const sources=await publicKnowledge();expect(JSON.stringify(sources)).toContain('APPROVED PUBLIC TEXT');expect(JSON.stringify(sources)).not.toContain('SECRET');expect(sources.some(s=>s.href==='/selling')).toBe(false);const a=randomUUID(),b=randomUUID();const net=vi.fn();vi.stubGlobal('fetch',net);const result=await askPublicChat(a,'buying');expect(result.messages[0].mode).toBe('guide');expect(result.messages[0].state).toBe('complete');expect(result.messages[0].sources.some(s=>s.href==='/buying')).toBe(true);expect(publicChatHistory(a).messages).toHaveLength(1);expect(publicChatHistory(b).messages).toHaveLength(0);await expect(askPublicChat(b,'',result.messages[0].id)).rejects.toThrow('visitor history');expect(net).not.toHaveBeenCalled();clearPublicChat(a);expect(publicChatHistory(a).messages).toHaveLength(0)})
 it('rejects huge prompts, throttles a visitor, and rejects remote model labels',async()=>{vi.stubEnv('RCRE_PUBLIC_CHAT_MODEL','some-cloud-model');expect(publicChatConfig().enabled).toBe(false);const id=randomUUID();await expect(askPublicChat(id,'x'.repeat(1201))).rejects.toThrow('1200');for(let i=0;i<8;i++)await askPublicChat(id,'Florida');await expect(askPublicChat(id,'again')).rejects.toThrow('wait a minute')})
 it('executes configured local protocol with public context only and reports failures without fallback',async()=>{vi.stubEnv('RCRE_PUBLIC_CHAT_MODEL','existing-model');const net=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({models:[{name:'existing-model'}]}))).mockResolvedValueOnce(new Response(JSON.stringify({message:{content:'Look at the published buying guide.'}})));vi.stubGlobal('fetch',net);const row=await askPublicChat(randomUUID(),'buying');expect(row.messages[0].mode).toBe('ai');expect(row.messages[0].answer).toContain('published buying');expect(net.mock.calls.map(c=>c[0])).toEqual(['http://127.0.0.1:11434/api/tags','http://127.0.0.1:11434/api/chat']);const request=JSON.parse(net.mock.calls[1][1].body);expect(request.messages[0].content).toContain('PUBLISHED WEBSITE EXCERPTS');expect(request.tools).toBeUndefined();net.mockRejectedValue(new Error('offline'));const failed=await askPublicChat(randomUUID(),'Florida');expect(failed.messages[0].state).toBe('failed');expect(failed.messages[0].answer).toBe('');expect(failed.messages[0].error).toContain('No other provider');expect(net).toHaveBeenCalledTimes(3)})
 it('clearing an in-flight model request cannot recreate visitor history',async()=>{vi.stubEnv('RCRE_PUBLIC_CHAT_MODEL','existing-model');let resolveTags!:(r:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(resolve=>{resolveTags=resolve})));const id=randomUUID();const pending=askPublicChat(id,'buying');while(!resolveTags)await new Promise(resolve=>setTimeout(resolve,0));clearPublicChat(id);resolveTags(new Response(JSON.stringify({models:[]})));await pending;expect(publicChatHistory(id).messages).toEqual([])})
})

describe('anonymous HTTP session boundary',()=>{it('uses a private HttpOnly visitor cookie and rejects cross-origin mutation',async()=>{const {NextRequest}=await import('next/server');const route=await import('../src/app/api/public/chat/route');const first=await route.GET(new NextRequest('http://localhost:3200/api/public/chat'));const cookie=first.headers.get('set-cookie')!;expect(cookie).toContain('HttpOnly');expect(cookie.toLowerCase()).toContain('samesite=strict');expect(first.headers.get('cache-control')).toBe('no-store');const blocked=await route.POST(new NextRequest('http://localhost:3200/api/public/chat',{method:'POST',headers:{origin:'https://other.invalid','Content-Type':'application/json'},body:JSON.stringify({prompt:'hello'})}));expect(blocked.status).toBe(403);const unknown=await route.POST(new NextRequest('http://localhost:3200/api/public/chat',{method:'POST',headers:{cookie:cookie.split(';')[0],'Content-Type':'application/json'},body:JSON.stringify({action:'retry',messageId:'another-visitors-message'})}));expect(unknown.status).toBe(429);expect((await unknown.json()).error).toContain('visitor history')})})


describe('published journal discovery',()=>{it('includes metro and custom public reading, removes redirects, and prunes old rate windows',async()=>{const {readRecords}=await import('../src/lib/platform/store');vi.stubEnv('RCRE_PUBLIC_CHAT_MODEL','');const paths=['/pages/chat-custom','/resources/chat-custom','/blog/chat-custom','/buying'];try{for(const id of paths)putRecord('public_content',{id,status:'published',published:{title:'Custom published reading',description:'Current public description',body:'CURRENT CUSTOM KNOWLEDGE',...(id==='/buying'?{redirectTo:'/selling'}:{})}});const sources=await publicKnowledge();expect(sources.some(s=>s.href==='/blog/metros/birmingham')).toBe(true);expect(sources.some(s=>s.href==='/blog/birmingham-neighborhood-shortlist')).toBe(true);for(const href of paths.slice(0,3))expect(sources.some(s=>s.href===href&&s.text.includes('CURRENT CUSTOM'))).toBe(true);expect(sources.some(s=>s.href==='/buying')).toBe(false);const stale='visitor:stale:1';putRecord('public_chat_rate',{id:stale,count:8});await askPublicChat(randomUUID(),'Birmingham');expect(readRecords<{id:string}>('public_chat_rate').some(r=>r.id===stale)).toBe(false)}finally{for(const id of paths)deleteRecord('public_content',id)}})})
