import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { requireActor } from '@/lib/platform/auth'
import * as tx from '@/lib/services/transactions'
import { PERSONAS } from '@/lib/platform/auth'
import { signingPreparations,prepareSigning,reviewSigning } from '@/lib/services/document-services'
import { readRecords } from '@/lib/platform/store'
export const runtime='nodejs'; export const dynamic='force-dynamic'
const deadline=z.object({id:z.string(),label:z.string().min(1).max(100),sourceTerm:z.string().max(2000),effectiveDate:z.string(),days:z.number().int().min(0).max(730).nullable(),convention:z.enum(['calendar','business']),timezone:z.string(),holidays:z.array(z.string()).max(100),confirmed:z.boolean(),override:z.string().optional(),overrideReason:z.string().optional()})
const patch=z.object({client:z.string().min(1).max(100).optional(),address:z.string().min(1).max(200).optional(),lender:z.string().max(200).optional(),title:z.string().max(200).optional(),closingDate:z.string().optional(),status:z.enum(['active','pending_signature','closed','archived']).optional(),deadlines:z.array(deadline).max(100).optional(),checklist:z.array(z.object({id:z.string(),label:z.string().min(1).max(100),done:z.boolean()})).max(100).optional()})
function fail(e:unknown){const message=e instanceof Error?e.message:'Request failed';return NextResponse.json({error:message},{status:/denied|not found|Unauthorized|sign in/i.test(message)?403:400})}
export async function GET(req:NextRequest){try{const a=await requireActor();const id=req.nextUrl.searchParams.get('id');if(!id)return NextResponse.json({transactions:tx.listTransactions(a),policy:tx.transactionPolicy(a),canManagePolicy:['broker_owner','managing_broker','team_leader'].includes(a.role)});const t=tx.requireTransaction(a,id);const docs=tx.documents(a,id);const file=req.nextUrl.searchParams.get('document');if(file){const d=docs.find(v=>v.id===file);if(!d)throw new Error('Document not found');return new NextResponse(Buffer.from(d.base64,'base64'),{headers:{'Content-Type':d.mime,'Content-Disposition':`attachment; filename="${d.name}"`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'none'; sandbox"}})}return NextResponse.json({transaction:t,assignmentOptions:PERSONAS.filter(p=>p.organizationId===a.organizationId&&(a.role==='broker_owner'||p.officeId===a.officeId)).map(p=>({id:p.id,name:p.name,role:p.role})),canAssign:['broker_owner','managing_broker','team_leader'].includes(a.role),signatures:signingPreparations(a,id),documents:docs.map(({base64,...d})=>d),drafts:tx.drafts(a,id),outbox:readRecords<{id:string;transactionId:string}>('transaction_outbox').filter(v=>v.transactionId===id),services:{signing:'Unavailable: project-isolated Documenso engine, API credential and verified callbacks required.',processing:'Unavailable: project-isolated Stirling PDF engine required. Plain text inspection excerpts work locally.'}})}catch(e){return fail(e)}}
export async function POST(req:NextRequest){try{const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==req.headers.get('host'))throw new Error('Origin access denied');const a=await requireActor();if(req.headers.get('content-type')?.includes('multipart/form-data')){const size=Number(req.headers.get('content-length')||0);if(!size||size>5*1024*1024+65536)throw new Error('Upload requires a declared size below 5 MB plus form metadata');const data=await req.formData();const file=data.get('file');if(!(file instanceof File))throw new Error('File required');const d=tx.uploadDocument(a,String(data.get('id')),file.name,file.type,Buffer.from(await file.arrayBuffer()),String(data.get('replaceId')||'')||undefined);return NextResponse.json({document:{...d,base64:undefined}})}const b=await req.json();let result;switch(b.action){case 'policy':result=tx.saveTransactionPolicy(a,z.object({version:z.number().int(),checklist:z.array(z.string().min(1).max(100)).min(1).max(50),documentRequirements:z.array(z.string().min(1).max(100)).max(50),reviewHours:z.number().int().min(1).max(168),separateReviewer:z.boolean(),retentionNote:z.string().max(2000)}).parse(b.input));break;case 'create':result=tx.createTransaction(a,patch.extend({representation:z.enum(['buyer','seller']).optional()}).parse(b.input));break;case 'update':result=tx.updateTransaction(a,String(b.id),Number(b.version),patch.parse(b.patch));break;case 'comment':result=tx.addComment(a,String(b.id),z.string().min(1).max(4000).parse(b.body));break;case 'draft':result=tx.saveDraft(a,String(b.id),z.object({id:z.string().optional(),version:z.number().optional(),documentId:z.string(),numbers:z.array(z.number().int()).min(1),body:z.string().min(1).max(20000).optional()}).parse(b.input));break;case 'submit':case 'approve':result=tx.reviewDraft(a,String(b.id),String(b.draftId),Number(b.version),b.action);break;case 'assign':result=tx.assignTransaction(a,String(b.id),String(b.ownerId),String(b.tcId||''));break;case 'prepare-signing':result=await prepareSigning(a,String(b.id),z.object({documentId:z.string(),recipients:z.array(z.object({name:z.string().min(1).max(100),email:z.string().email(),order:z.number().int().min(1).max(20)})).min(1).max(20),fields:z.array(z.object({recipient:z.number().int().min(0).max(19),page:z.number().int().min(1).max(2000),x:z.number().min(0).max(100),y:z.number().min(0).max(100)})).min(1).max(100)}).parse(b.input));break;case 'review-signing':result=await reviewSigning(a,String(b.id),String(b.preparationId));break;case 'signature':throw new Error('Signing unavailable: configure and verify a local Documenso service before creating a signature request. No signing action occurred.');default:throw new Error('Unknown action')}return NextResponse.json({result})}catch(e){return fail(e)}}
