import {spawn} from 'node:child_process'
import net from 'node:net'
import {mkdirSync,realpathSync,existsSync,copyFileSync,unlinkSync,readdirSync} from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {randomBytes,createHash} from 'node:crypto'
import {readFileSync,writeFileSync} from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
const root=realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'))
if(path.basename(root)!=='RCRE')throw Error('Existing RCRE root required')
const runtime=path.join(root,'runtime');for(const d of ['tmp','cache','data','backups','logs'])mkdirSync(path.join(runtime,d),{recursive:true,mode:0o700})
const command=process.argv[2]??'dev',dbfile=path.join(runtime,'data/platform.sqlite')
async function requireStopped(){for(const port of new Set([3200,Number(process.env.RCRE_PORT??3200)])){const active=await new Promise(resolve=>{const socket=net.createConnection({host:'127.0.0.1',port});socket.setTimeout(1000);socket.once('connect',()=>{socket.destroy();resolve(true)});socket.once('error',()=>resolve(false));socket.once('timeout',()=>{socket.destroy();resolve(false)})});if(active)throw Error('Stop the local app before reset or restore (port '+port+' is active)')}}
if(['reset','restore','check-stopped'].includes(command))await requireStopped()
if(command==='check-stopped'){console.log('No local server is listening; this check made no data changes')}
else if(command==='backup'){const db=new DatabaseSync(dbfile);const name=path.join(runtime,'backups',`platform-${Date.now()}.sqlite`);db.exec(`VACUUM INTO '${name.replaceAll("'","''")}'`);db.close();const bundle=name.replace(/\.sqlite$/,'.files');mkdirSync(bundle,{mode:0o700});const files=[];function copyTree(source,target,relative){if(!realpathSync(source).startsWith(root+path.sep))throw Error('Backup source outside RCRE');mkdirSync(target,{recursive:true,mode:0o700});for(const entry of readdirSync(source,{withFileTypes:true})){if(entry.isSymbolicLink())throw Error('Backup does not follow symlinks');const src=path.join(source,entry.name),dest=path.join(target,entry.name),rel=path.join(relative,entry.name);if(entry.isDirectory())copyTree(src,dest,rel);else if(entry.isFile()){copyFileSync(src,dest);files.push({path:rel,sha256:createHash('sha256').update(readFileSync(dest)).digest('hex')})}}}for(const dir of ['community-attachments','academy-uploads','library-assets'])if(existsSync(path.join(runtime,dir)))copyTree(path.join(runtime,dir),path.join(bundle,dir),dir);writeFileSync(path.join(bundle,'manifest.json'),JSON.stringify({createdAt:new Date().toISOString(),database:path.basename(name),databaseSha256:createHash('sha256').update(readFileSync(name)).digest('hex'),files,immutableTrainingAssets:'Retain the RCRE training-assets directory separately'},null,2));console.log(name);console.log('Mutable asset bundle: '+bundle)}
else if(command==='reset'){if(!process.argv.includes('--confirm-local-reset'))throw Error('Stop the server; pass --confirm-local-reset');if(existsSync(dbfile))unlinkSync(dbfile);for(const ext of ['-wal','-shm'])if(existsSync(dbfile+ext))unlinkSync(dbfile+ext);console.log('Local demo database reset. Restart to seed synthetic records.')}
else if(command==='restore'){const name=process.argv[3];if(!name||!process.argv.includes('--confirm-local-restore'))throw Error('Stop server; supply backup filename and --confirm-local-restore');const source=realpathSync(path.join(runtime,'backups',path.basename(name)));if(!source.startsWith(path.join(runtime,'backups')+path.sep))throw Error('Invalid backup');const db=new DatabaseSync(source,{readOnly:true});if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Invalid database');db.close();copyFileSync(source,dbfile);for(const ext of ['-wal','-shm'])if(existsSync(dbfile+ext))unlinkSync(dbfile+ext);console.log('Local backup restored')}
else {const workerKeyFile=path.join(runtime,'data/local-worker-key');if(!existsSync(workerKeyFile))writeFileSync(workerKeyFile,randomBytes(32).toString('hex'),{mode:0o600});const keyFile=path.join(runtime,'data/fub-local-test-key');if(!existsSync(keyFile))writeFileSync(keyFile,randomBytes(32).toString('hex'),{mode:0o600});const env={RCRE_LOCAL_WORKER_KEY:readFileSync(workerKeyFile,'utf8').trim(),RCRE_FUB_LOCAL_TEST_KEY:readFileSync(keyFile,'utf8').trim(),...process.env,TMPDIR:path.join(runtime,'tmp'),TMP:path.join(runtime,'tmp'),TEMP:path.join(runtime,'tmp'),npm_config_cache:path.join(runtime,'cache'),NEXT_TELEMETRY_DISABLED:'1',RCRE_APP_MODE:'local',RCRE_DATA_MODE:'fixtures',RCRE_ALLOW_FUB_WRITES:'false',RCRE_ALLOW_OUTBOUND_SEND:'false'};if(command==='build')env.RCRE_BUILD_DIR='.next-production';if(command==='start')env.RCRE_BUILD_DIR='.next-production';const args=[path.join(root,'apps/rcre-demo/node_modules/next/dist/bin/next'),command,...(['dev','start'].includes(command)?['-p',process.env.RCRE_PORT??'3200','--hostname','127.0.0.1']:[])];const child=spawn(process.execPath,args,{cwd:path.join(root,'apps/rcre-demo'),stdio:'inherit',env});const worker=['dev','start'].includes(command)?spawn(process.execPath,[path.join(root,'scripts/local-worker.mjs')],{cwd:root,stdio:'ignore',env}):null;child.on('exit',code=>{worker?.kill('SIGTERM');process.exit(code??0)});for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{worker?.kill(signal);child.kill(signal)})}
