import {NextRequest,NextResponse} from 'next/server'
import {requireActor,assertCapability,AccessError} from '@/lib/platform/auth'
import {audit} from '@/lib/platform/service'
import {providerCatalog,saveProviderCompliance} from '@/lib/property/providers'
import {z} from 'zod'
export const dynamic='force-dynamic'
const schema=z.object({providerId:z.string().min(1).max(80),approved:z.literal(true),agreementReference:z.string().trim().min(2).max(300),requiredAttribution:z.string().trim().min(1).max(2000),requiredDisclaimer:z.string().trim().min(1).max(6000),copyrightText:z.string().trim().min(1).max(2000),listingBrokerageRule:z.string().trim().min(1).max(2000),refreshIntervalHours:z.number().int().min(1).max(720),photoMode:z.enum(['remote','cached','local-derivative']),permittedStatuses:z.array(z.enum(['Active','Coming Soon','Pending','Closed','Withdrawn','Unknown'])).min(1).max(6),soldDisplayAllowed:z.boolean(),openHouseRules:z.string().trim().max(2000),indexing:z.enum(['allowed','noindex'])})
const failure=(e:unknown)=>NextResponse.json({error:e instanceof AccessError?e.message:'MLS settings could not be updated.'},{status:e instanceof AccessError?e.status:500,headers:{'Cache-Control':'no-store'}})
export async function GET(){try{const actor=await requireActor();assertCapability(actor,'settings.leads');return NextResponse.json({providers:providerCatalog(actor.organizationId),secretsExposed:false},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function PUT(req:NextRequest){try{const actor=await requireActor();assertCapability(actor,'settings.leads');const origin=req.headers.get('origin');if(origin&&origin!==req.nextUrl.origin)return NextResponse.json({error:'Cross-origin update denied.'},{status:403});const body=schema.parse(await req.json());const {providerId,approved,...compliance}=body;const state=saveProviderCompliance(actor.organizationId,providerId,compliance,actor.id);audit(actor,'mls.compliance_terms_recorded',providerId);return NextResponse.json({agreementApproved:state.agreementApproved,approvedAt:state.approvedAt,status:providerCatalog(actor.organizationId).find(p=>p.id===providerId)?.status},{headers:{'Cache-Control':'no-store'}})}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:'Add the exact approved agreement and display terms before saving.'},{status:400});return failure(e)}}
