import {NextRequest,NextResponse} from 'next/server'
import {requireActor,assertCapability,AccessError} from '@/lib/platform/auth'
import {readRecords,getRecord,putRecord,transaction} from '@/lib/platform/store'
import {dataMode} from '@/lib/config/env'
import {getRepository} from '@/lib/db'
import {listPublicContentForAdmin,publicContentMutationSchema,savePublicContent} from '@/lib/public/cms'
import {validatePublicRedirect} from '@/lib/public/redirects'
import {audit} from '@/lib/platform/service'
import {publicRoutes,type PublicContent,type PublishedContent} from '@/lib/public/content'
function fail(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Content could not be saved'},{status:e instanceof AccessError?e.status:400})}
export async function GET(){try{const a=await requireActor();assertCapability(a,'cms');if(dataMode()==='live')return NextResponse.json(await listPublicContentForAdmin(a,await getRepository()),{headers:{'Cache-Control':'private, no-store'}});return NextResponse.json(readRecords<PublicContent>('public_content').filter(r=>r.organizationId===a.organizationId||!r.organizationId&&a.organizationId==='rcre-local'),{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:NextRequest){try{const origin=req.headers.get('origin');if(!origin)throw new AccessError('Origin verification required',403);let parsedOrigin:string;try{parsedOrigin=new URL(origin).origin}catch{throw new AccessError('Origin verification required',403)}if(parsedOrigin!==req.nextUrl.origin)throw new AccessError('Cross-origin write denied',403);const a=await requireActor();assertCapability(a,'cms');const v=publicContentMutationSchema.parse(await req.json());if(dataMode()==='live')return NextResponse.json(await savePublicContent(a,v,await getRepository()),{headers:{'Cache-Control':'private, no-store'}});const result=transaction(()=>{const old=getRecord<PublicContent>('public_content',v.id);if(old?.organizationId&&old.organizationId!==a.organizationId)throw new AccessError();if((old?.revision??0)!==v.revision)throw new AccessError('This content changed in another session. Reload before saving.',409);if(v.redirectTo&&v.status!=='archived')validatePublicRedirect(v.id,v.redirectTo,readRecords<PublicContent>('public_content').filter(r=>!r.organizationId||r.organizationId===a.organizationId));if(v.profile&&!v.id.startsWith('/agent/'))throw new Error('Profile fields belong to an agent page.');if(v.schema&&!v.id.startsWith('/blog/'))throw new Error('Article schema fields belong to an article page.');const snapshot:PublishedContent={redirectTo:v.redirectTo,profile:v.profile,schema:v.schema,noIndex:v.noIndex,title:v.title,description:v.description,body:v.body,seoTitle:v.seoTitle,canonical:v.canonical,image:v.image,navigation:v.navigation};const r:PublicContent={...snapshot,id:v.id,organizationId:a.organizationId,status:v.status,revision:v.revision+1,history:[...(old?.history??[]),...(old?[{redirectTo:old.redirectTo,profile:old.profile,schema:old.schema,noIndex:old.noIndex,title:old.title,description:old.description,body:old.body,seoTitle:old.seoTitle,canonical:old.canonical,image:old.image,navigation:old.navigation,revision:old.revision}]:[])].slice(-40),published:v.status==='published'?snapshot:v.status==='archived'?undefined:old?.published};putRecord('public_content',r);audit(a,'website.'+v.status,v.id);return r});return NextResponse.json(result)}catch(e){return fail(e)}}
