import {NextRequest,NextResponse} from 'next/server'
import {z} from 'zod'
import {requireActor,assertCapability,AccessError} from '@/lib/platform/auth'
import {readRecords,getRecord,putRecord,transaction} from '@/lib/platform/store'
import {validatePublicRedirect} from '@/lib/public/redirects'
import {audit} from '@/lib/platform/service'
import {publicRoutes,type PublicContent,type PublishedContent} from '@/lib/public/content'
const allowedPath=(p:string)=>publicRoutes.includes(p)||/^\/(blog|resources|pages)\/[a-z0-9]+(?:[a-z0-9/-]*[a-z0-9])?$/.test(p)
const schema=z.object({redirectTo:z.string().max(240).optional(),profile:z.object({phone:z.string().min(1).max(80),email:z.string().email(),license:z.string().min(1).max(160),market:z.enum(['Alabama','Florida','Alabama & Florida'])}).optional(),schema:z.object({authorName:z.string().trim().max(180),datePublished:z.string().refine(s=>!s||/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Use a real calendar date.')}).optional(),noIndex:z.boolean().optional(),id:z.string().refine(allowedPath,'Use an existing public route or /blog, /resources, or /pages with a lowercase slug.'),revision:z.number().int().min(0),title:z.string().trim().min(1).max(180),description:z.string().trim().max(500),body:z.string().trim().min(1).max(50000),status:z.enum(['draft','published','archived']),seoTitle:z.string().max(180).optional(),canonical:z.string().refine(s=>!s||/^https:\/\/rcregroup\.com(?:\/[a-z0-9/_-]*)?$/.test(s),'Canonical must be an RCRE public URL.').optional(),image:z.object({src:z.enum(['','/brand/people/julio-arango.jpg','/brand/people/taquilla-allen.jpg','/brand/rcre-logo-dark.png','/brand/rcre-logo-light.png']),alt:z.string().max(250)}).refine(i=>!i.src||!!i.alt.trim(),'An image needs useful alternative text.').optional(),navigation:z.object({visible:z.boolean(),label:z.string().max(40),order:z.number().int().min(0).max(99)}).refine(n=>!n.visible||!!n.label.trim(),'Visible navigation needs a label.').optional()})
function fail(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Content could not be saved'},{status:e instanceof AccessError?e.status:400})}
export async function GET(){try{const a=await requireActor();assertCapability(a,'cms');return NextResponse.json(readRecords<PublicContent>('public_content').filter(r=>r.organizationId===a.organizationId||!r.organizationId&&a.organizationId==='rcre-local'),{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:NextRequest){try{if(req.headers.get('origin')&&req.headers.get('origin')!==req.nextUrl.origin)throw new AccessError('Cross-origin write denied');const a=await requireActor();assertCapability(a,'cms');const v=schema.parse(await req.json());const result=transaction(()=>{const old=getRecord<PublicContent>('public_content',v.id);if(old?.organizationId&&old.organizationId!==a.organizationId)throw new AccessError();if((old?.revision??0)!==v.revision)throw new AccessError('This content changed in another session. Reload before saving.',409);if(v.redirectTo&&v.status!=='archived')validatePublicRedirect(v.id,v.redirectTo,readRecords<PublicContent>('public_content').filter(r=>!r.organizationId||r.organizationId===a.organizationId));if(v.profile&&!v.id.startsWith('/agent/'))throw new Error('Profile fields belong to an agent page.');if(v.schema&&!v.id.startsWith('/blog/'))throw new Error('Article schema fields belong to an article page.');const snapshot:PublishedContent={redirectTo:v.redirectTo,profile:v.profile,schema:v.schema,noIndex:v.noIndex,title:v.title,description:v.description,body:v.body,seoTitle:v.seoTitle,canonical:v.canonical,image:v.image,navigation:v.navigation};const r:PublicContent={...snapshot,id:v.id,organizationId:a.organizationId,status:v.status,revision:v.revision+1,history:[...(old?.history??[]),...(old?[{redirectTo:old.redirectTo,profile:old.profile,schema:old.schema,noIndex:old.noIndex,title:old.title,description:old.description,body:old.body,seoTitle:old.seoTitle,canonical:old.canonical,image:old.image,navigation:old.navigation,revision:old.revision}]:[])].slice(-40),published:v.status==='published'?snapshot:v.status==='archived'?undefined:old?.published};putRecord('public_content',r);audit(a,'website.'+v.status,v.id);return r});return NextResponse.json(result)}catch(e){return fail(e)}}
